### ISSUE TITLE
LDAP - offer an admin account binding option and improve searchFilter

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6367] opened 2022-04-25 14:07 UTC
### Is your feature request related to a problem? Please describe.

Today's implementation for user lookup is simplistic: only user binding is available.

Many companies use a privileged user account (like a management account) to first bind to the LDAP server, then the app executes a search query to find users using a templatized user DN.

The ask is to introduce two new fields:
- `serviceAccountDN`
- `serviceAccountPassword`

This service account parameters will be used during the BIND operation

Once the LDAP session is authenticated, the ExtAuth server can proceed to an LDAP search using the recently introduced `searchFilter` to look for users. This parameter should allow for a placeholder where the username will be replaced.

Example:
`searchFilter: (&(mail=%s,ou=users,dc=myorg)(objectClass=person))`
where `%s` is replaced with the user name extracted from the Authorization header (basic auth)

The user password will be checked using a [simple bind](https://pkg.go.dev/github.com/go-ldap/ldap@v3.0.3+incompatible#Conn.SimpleBind) operation.

Also, a search base should be configurable, as in the ldapsearch CLI, with the `-b` arg
A new option called `searchBase` could be introduced.

**Comment by ashishb-solo** [comment] 2023-01-30 16:36
@bcollard I think this might be a duplicate of https://github.com/solo-io/ext-auth-service/issues/404 - it was fixed in [this pull request](https://github.com/solo-io/ext-auth-service/pull/424). If you have a chance, could you take a look at them and see if they align? Is there something the pull request that I linked does not provide that is being asked here?

Happy to talk about this directly as well. Thanks!

**Comment by bcollard** [comment] 2023-01-30 21:15
This looks similar. I'll let @Jimmmz or @imanollazkano follow up with the initial customer

**Comment by ashishb-solo** [comment] 2023-01-30 22:22
Thanks! I think I'm going to continue looking into this a little further though. As it currently stands, our [ldap configuration options](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#ldap) don't appear to expose the service account options, so I want to look at this just a little bit further for now. But your follow-ups will definitely be helpful, so do let me know how they go. Thanks again!

**Comment by anessi** [comment] 2023-01-31 06:45
@ashishb-solo while looking into this please also consider https://github.com/solo-io/gloo/issues/6368 and https://github.com/solo-io/gloo/issues/6366 because especially the first one prevents us from using the LDAP integration provided by Gloo. Thanks.

**Comment by nfuden** [comment] 2023-01-31 14:57
Given that those have separate issues lets deal with them there. For this one lets improve documentation for now

**Comment by ashishb-solo** [comment] 2023-02-01 19:47
This is already supported, but the documentation on it has not been written. I have provided the configuration details required to do this to the documentation team and will ask them to take it from here. Once they've taken care of it, I will ask them to close the issue.

**Comment by ashishb-solo** [comment] 2023-02-13 19:10
https://github.com/solo-io/gloo/pull/7823 got merged, so this can be closed now

**Closed by ashishb-solo** 2023-02-13 19:10 UTC
Labels: Type: Enhancement, Type: Docs, Area: extauth
