### ISSUE TITLE
Admission control for non-gloo resources

### ISSUE THREAD

**Issue by guydaichs** [solo-io/gloo#5100] opened 2021-08-02 09:59 UTC
**Is your feature request related to a problem? Please describe.**
It appears that the Gloo Edge validating webbooks are only validating `gateway.solo.io` CRDs: 

```
webhooks:
- admissionReviewVersions:
  rules:
  - apiGroups:
    - gateway.solo.io
    apiVersions:
    - v1
```

Proxy configuration can be corrupted by operations on core k8s resources referenced by Gloo resources. For example, deletion of TLS secrets referenced by virtual services will lead to warnings and errors, as mentioned [here](https://github.com/solo-io/gloo/issues/5079). 

**Describe the solution you'd like**
Admission control for relevant k8s resources, preventing invalid configuration. 

**Describe alternatives you've considered**
Implementing a validating webhook. 

**Additional context**
Since these resources are not controlled by Gloo, validation should be an optional addition to existing validations.

**Comment by chrisgaun** [comment] 2021-09-17 17:02
Duplicate of https://github.com/solo-io/gloo/issues/2797

@guydaichs This is a large Issue and we are currently in process of tackling it. The first piece can be found here https://github.com/solo-io/gloo/issues/5173

**Comment by chrisgaun** [comment] 2021-09-17 17:03
Closing this dupe

**Closed** 2021-09-17 17:03 UTC
Labels: Type: Enhancement

**Comment by chrisgaun** [comment] 2021-09-22 19:30
Duplicate of https://github.com/solo-io/gloo/issues/5366 

Decided that #2797 was about webhook validation for Gloo resources while this is for Kubernetes resources (TLS secrets being primary use case but also config maps, etc may apply in future)
