### ISSUE TITLE
enable automation of gloo-to-istio mTLS config

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1447] opened 2019-10-18 19:07 UTC
currently, users must manually configure options on the Gateway Proxy deployment as well as each invidiual Upstream in an Istio mesh to which Gloo routes: https://gloo.solo.io/gloo_integrations/service_mesh/gloo_istio_mtls/

We should provide the means to automate this.

Suggested implementation:

- helm chart values to mount the istio secrets (or sds socket) to the gateway proxy-
- an annotation on the k8s service which discovery can include in the generated upstream

**Comment by rickducott** [comment] 2020-02-11 04:24
Related to https://github.com/solo-io/gloo/issues/2111

**Comment by rickducott** [comment] 2020-02-11 22:46
Going to close as dupe of the other issue.

**Closed by rickducott** 2020-02-11 22:46 UTC
Labels: Type: Enhancement, Type: Roadmap
