### ISSUE TITLE
endpoints of cluster not refreshed after long running

### ISSUE THREAD

**Issue by benishak** [solo-io/gloo#660] opened 2019-04-04 10:37 UTC
Hi

Today I wanted to test gloo/envoy again and I got this error
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

so I checked http://localhost:19000/clusters and I found that it is having 417 endpoints for my service while I actually had 270 pods running for service.
Gloo and envoy pods were running for longer than 20h after I deleted all pods and recreated them it worked fine and I got the right endpoints

This seems to me that gloo did not remove endpoints of dead pods.

I couldn't see any errors in the gloo logs
I did not check how many endpoints gloo and discovery were reporting.

**Step to reproduce**
it might happen that after long running gloo might get stack and stop updating? but I think the way to reproduce this is to keep adding and removing pods many times simulating auto scaling activities

**Comment by benishak** [comment] 2019-04-05 13:16
![Screen Shot 2019-04-05 at 11 46 12](https://user-images.githubusercontent.com/5909357/55630284-9c085680-57b5-11e9-9eb2-c56e3643a9f0.png)

No Idea why I get so many 503 responses although I disabled circuit breaker completely
is there any rate limiting being enforced globally?

**Comment by benishak** [comment] 2019-04-05 13:19
![Screen Shot 2019-04-05 at 15 17 59](https://user-images.githubusercontent.com/5909357/55630497-1df87f80-57b6-11e9-84d9-60e0ef5ae078.png)

Also some how number of requests dropped from 12M rpm to 6M and 5XX spiked

**Comment by yuval-k** [comment] 2019-04-10 19:19
This one seems tricky - as you said that removing all the pods seemed to help - so it seems that gloo was able to detect the new pods after they were deleted. does this reproduce consistently?
Do you know if just restarting gloo would have helped? do you happen to have the gloo logs?
i can try and reproduce this, but might take me a bit of time to set it up.

**Comment by yuval-k** [comment] 2019-04-10 19:20
also - what version of gloo was used?

**Comment by yuval-k** [comment] 2019-04-10 19:23
also - did you see any errors in the envoy logs?

**Comment by benishak** [comment] 2019-04-10 19:49
The error in envoy was gRPC disconnect/reset timeout
it happened today with gloo 0.13.12 as well

**Comment by benishak** [comment] 2019-04-10 20:00
by removing pods i means gloo pods (discovery, gloo, gateway. gateway-proxy)

today when it happened, last update contained 320 upstreams while i had actually 600 up and ready, then http 503 spiked and it only worked fine when I restarted all gloo components

**Comment by yuval-k** [comment] 2019-04-10 20:34
so envoy failed to connect to the gloo XDS server?
I'm going to setup a cluster and load it to see if i can reproduce this.

**Comment by yuval-k** [comment] 2019-04-11 18:54
To make sure we are on the same page:

I've setup a cluster with latest gloo (i added some stats to hopefully get more insights)
i have a deployment that i keep changing from 100-300 pods.

I'm scaling my deployment to a value between 100 and 300 like so  `kubectl -n default scale deployment petstore --replicas=200`

And then I verify that `curl -s localhost:19000/stats?format=json|jq  '.stats[]|select(.name == "cluster.gloo-system.default-petstore-8080.membership_total")|.value` matches the value i used in the scale command.

so far its working - will let the cluster 'bake' for a few hours and try again.

**Comment by benishak** [comment] 2019-04-11 19:10
sounds good
could the Load on Envoy cause it to fail somehow to connect to gRPC?

**Comment by yuval-k** [comment] 2019-04-11 19:33
good question, as far as i'm aware it shouldn't - but if i can't reproduce it this way i will try to use a load tool and test under load.

**Comment by yuval-k** [comment] 2019-04-11 19:35
do you happen to have envoy logs in debug? that can help in understanding if its a load issue too

**Comment by yuval-k** [comment] 2019-04-11 19:35
actually under load they might be unreadable...

**Comment by yuval-k** [comment] 2019-04-11 19:36
do you have the envoy stats when this issue happens?

**Comment by benishak** [comment] 2019-04-11 19:42
I don't have logs
here are some stats that i captured during similar situation
https://github.com/envoyproxy/envoy/issues/6485#issuecomment-480288092

**Comment by benishak** [comment] 2019-04-11 19:43
when i test envoy again i will try to keep logs from all components when this eventually happens again.

**Comment by yuval-k** [comment] 2019-04-11 19:57
in those stats i do see non zero `update_failure` which means - Total API fetches that failed because of network errors. So the failure to update might be load related. I think our current plan still makes sense - if my cluster is still responsive tomorrow then it is more likely to be a load issue.

If it is load related - assuming it is network IO load (can verify that the CPU and RAM are not loaded?). a few things come to mind:
1. Depending on your hypervisor - get machines with more network IO
2. If (1) is not possible, maybe trying a higher amount smaller machines (i.e. to trick the hypervisor to provision more total network IO to envoy)
3. I do wonder if there's a way to tell linux that certain connections are more important than others - I'll have to do some research here.

**Comment by yuval-k** [comment] 2019-04-12 18:56
Re-tested my cluster today and it seems to work fine - so my guess would be load related issue.
If it cpu or memory load we can ask kuberentes to reserve more resources for the gloo pod;
if it is network load we'll have to figure out how can we allow for more network IO.
going to try network load testing soon

**Comment by benishak** [comment] 2019-04-12 19:22
makes sense
my environment was
Kubernetes AWS EKS 1.11 awsvpc cni
5 x c5n.9xlarge 
Envoy running as DaemonSet on all 5 nodes with hostNetwork=true, I reserved 26 Cores for it and system got 10 Cores
Gloo and Discovery run as Deployment with replica 1, they will run on one of the 5 nodes. Gloo does *not* use hostnetwork. 

On these runs only gloo components.

I will try running gloo with together with Envoy in one pod and change xds ip address to 127.0.0.1.

FYI I run telegraf as statsd daemon with Envoy in one pod/daemonset and did not see Envoy failing to send data to it.

Btw what is the role of discovery and how gloo and discovery talk with each other? i don't see discovery is exposing ports or being exposed as a service. 

I hope i was able to provide enough info. 

I cannot test envoy atm again because im still stuck finding a way to go around the lowecased headers.

**Comment by yuval-k** [comment] 2019-04-15 00:03
discovery and gloo do not interact directly; discover discovers upstreams and functions, writes them as upstream CRDs that can then be used in gloo for routing.. if you were to create the upstream crds yourself gloo wouldn't care (i.e. gloo is not 'aware' of the discovery pod).

I saw the issue about the headers.. unfortunately that's not a behavior we can change via extensions - as lower case headers are a core assumption inside envoy and from looking at the code I dont really see away around it.. only thing i can think of is an out of process approach.. what have you been trying so far?

**Comment by yuval-k** [comment] 2019-05-09 15:27
One thought is that this may be caused by a half open connection to the control plane. setting tcp keepalive can solve this.
to do this, a config block needs to be added to the static envoy config. see an example here:
https://github.com/solo-io/gloo/pull/708/files

**Comment by ilevine** [comment] 2019-07-16 14:50
Hi @benishak,
The cause is most likely a half open connection disconnecting envoy from the control plane. This is solved in recent versions of gloo by adding a default tcpKeepAlive options. and can also be tuned to your specific environments.

Closing for now, please re-open if needed

**Closed by ilevine** 2019-07-16 14:50 UTC
Labels: Area: envoy, Size: S, Type: bug

**Comment by hunshcn** [comment] 2023-05-24 02:09
I seem to have triggered a similar problem on 1.10.23.
The following is the gateway-proxy log.
```
[2023-05-23 10:45:30.257][6][warning][misc] [external/envoy/source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.config.cluster.v3.Cluster Using deprecated option 'envoy.config.cluster.v3.Cluster.http2_protocol_options' from file cluster.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
[2023-05-23 10:45:30.278][6][info][upstream] [external/envoy/source/common/upstream/cds_api_helper.cc:30] cds: add 21527 cluster(s), remove 5 cluster(s)
[2023-05-23 10:45:30.433][6][info][upstream] [external/envoy/source/common/upstream/cds_api_helper.cc:67] cds: added/updated 0 cluster(s), skipped 21527 unmodified cluster(s)
[2023-05-23 20:09:26.871][6][warning][config] [external/envoy/source/common/config/grpc_stream.h:160] StreamAggregatedResources gRPC config stream closed: 13,
[2023-05-23 21:17:59.499][6][warning][config] [external/envoy/source/common/config/grpc_stream.h:160] StreamAggregatedResources gRPC config stream closed: 13,
```
stuck more than 1 day
