### ISSUE TITLE
Prevent HTTP Passthrough Auth from Inserting Empty Headers into Request

### ISSUE THREAD

**Issue by ben-taussig-solo** [solo-io/gloo#8391] opened 2023-06-15 14:33 UTC
### Gloo Edge Version

1.14.x (latest stable)

### Kubernetes Version

None

### Describe the bug

 - With HTTP Passthrough auth configured, and and AWS upstream, an empty header (`'':''`) is inserted into the request sent to AWS
 - This prevents the Authorization signature used to validate the request in AWS from being computed properly, resulting in a 502 being thrown

### Steps to reproduce the bug

See discussion here for reproduction steps: https://github.com/solo-io/gloo/issues/8275

### Expected Behavior

 - When a request is made with HTTP Passthrough auth configured, we should not add an empty header to the outgoing request
 - https://github.com/solo-io/gloo/issues/8275 is closed when the work is completed

### Additional Context

See here for more info: https://github.com/solo-io/gloo/issues/8275

**Comment by sheidkamp** [comment] 2023-08-10 13:03
Root cause is here:
https://github.com/solo-io/ext-auth-service/blob/master/pkg/config/passthrough/http/http_auth_service.go#L298-L319

We `make` a slice that can hold all the allowed headers, but only copy (by index) ones that have values in the auth response, so we can have nil entries in the slice of headers to append to the request.

**Comment by sheidkamp** [comment] 2023-08-24 13:34
This fix will be included in GlooEE v1.14.9

**Closed** 2023-08-24 13:41 UTC
Labels: Type: Bug, Enterprise, Area: extauth, release/1.14
