### ISSUE TITLE
enable dynamic creation of host-based route/virtualservice when upstream is dynmamically created

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2400] opened 2020-02-11 15:55 UTC
Add a config option to enable the following: When an upstream is dynamically discovered and created then also create a / prefix route and virtualservice with a domain that matches the host in the upstream. This would remove the need for manual or external creation of routes/virtualservices for purely host-based routing.

**Comment by bdecoste** [comment] 2020-02-12 01:02
New config would look something like this:

```
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  name: default
  namespace: gloo-system
spec:
  discovery:
    fdsMode: BLACKLIST
    dynamicVirtualService:
      enabled: true
      domainSuffix: example.com

```

Which would create this for every discovered upstream:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - ‘petstore.example.com’
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: petstore
            namespace: gloo-system
```

**Comment by rickducott** [comment] 2020-02-12 02:56
Would be good to include the upstream yaml here too; in particular, looking for the source of truth for “petstore” - don’t think we can rely on the upstream name since discovery writes it differently.

**Comment by ilackarms** [comment] 2020-02-12 12:34
hey @bdecoste @rickducott i believe this is a duplicate of https://github.com/solo-io/gloo/issues/2308

**Comment by rickducott** [comment] 2020-02-12 13:19
Ok, closing in favor of that one. Thanks!

**Closed by rickducott** 2020-02-12 13:19 UTC
Labels: Area: Discovery, Type: Enhancement
