### ISSUE TITLE
ability to mask sensitive data in logs

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2486] opened 2020-02-22 13:55 UTC
DLP?

**Comment by yuval-k** [comment] 2020-02-24 16:55
we need this on the access log level; 
there is a way to extend a filter to allow modifying the headers before logging. so we can add that as a type of transformation. 
we need to validate that this indeed works and that no upstream envoy changes are needed.

**Comment by jahvon** [comment] 2021-04-29 19:43
Duplicate of https://github.com/solo-io/gloo/issues/4282

**Closed** 2021-05-25 15:17 UTC
Labels: Type: Enhancement
