### ISSUE TITLE
Deleting virtual service&route&upstream leaves fragments in Envoy config

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#1558] opened 2019-10-30 23:47 UTC
**Describe the bug**
After creating a "weather" upstream and route/virtualservice and then removing the route and deleting the virtualservice&upstream the Envoy config still contains references to "weather". 

This only occurs when "weather" is the only route. When a new route is added then all references to "weather" in the Envoy config are removed. 

**To Reproduce**
1. glooctl create upstream static --name weather --static-hosts api.openweathermap.org
2. glooctl add route --name weather --path-exact /boston-weather --dest-name weather --prefix-rewrite "/data/2.5/weather?q=Boston&APPID=5b8354119b9b297f9d84de9d819adee2"
3. glooctl remove route --name weather
4. glooctl delete virtualservice weather
5. glooctl delete upstream weather
6. See below for Envoy config output

**Expected behavior**
No references to "weather" would remain after route is removed and virtualservice&upstream are deleted. 

**Additional context**
# wget -O /dev/stdout http://127.0.0.1:19000/config_dump
Connecting to 127.0.0.1:19000 (127.0.0.1:19000)
{
 "configs": [
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.BootstrapConfigDump",
   "bootstrap": {
    "node": {
     "id": "gateway-proxy-v2-5fc9f846b9-nmbcw.gloo-system",
     "cluster": "gateway",
     "metadata": {
      "role": "gloo-system~gateway-proxy-v2"
     },
     "build_version": "527e4d010c6b993d343a337c2752070478649452/1.12.0-dev/Distribution/RELEASE/BoringSSL"
    },
    "static_resources": {
     "listeners": [
      {
       "name": "prometheus_listener",
       "address": {
        "socket_address": {
         "address": "0.0.0.0",
         "port_value": 8081
        }
       },
       "filter_chains": [
        {
         "filters": [
          {
           "name": "envoy.http_connection_manager",
           "config": {
            "codec_type": "auto",
            "http_filters": [
             {
              "name": "envoy.router",
              "config": {}
             }
            ],
            "stat_prefix": "prometheus",
            "route_config": {
             "name": "prometheus_route",
             "virtual_hosts": [
              {
               "routes": [
                {
                 "route": {
                  "cluster": "admin_port_cluster"
                 },
                 "match": {
                  "path": "/ready",
                  "headers": [
                   {
                    "name": ":method",
                    "exact_match": "GET"
                   }
                  ]
                 }
                },
                {
                 "match": {
                  "headers": [
                   {
                    "name": ":method",
                    "exact_match": "GET"
                   }
                  ],
                  "prefix": "/metrics"
                 },
                 "route": {
                  "cluster": "admin_port_cluster",
                  "prefix_rewrite": "/stats/prometheus"
                 }
                }
               ],
               "domains": [
                "*"
               ],
               "name": "prometheus_host"
              }
             ]
            }
           }
          }
         ]
        }
       ]
      }
     ],
     "clusters": [
      {
       "name": "gloo.gloo-system.svc.cluster.local:9977",
       "type": "STRICT_DNS",
       "connect_timeout": "5s",
       "http2_protocol_options": {},
       "alt_stat_name": "xds_cluster",
       "upstream_connection_options": {
        "tcp_keepalive": {}
       },
       "load_assignment": {
        "cluster_name": "gloo.gloo-system.svc.cluster.local:9977",
        "endpoints": [
         {
          "lb_endpoints": [
           {
            "endpoint": {
             "address": {
              "socket_address": {
               "address": "gloo.gloo-system.svc.cluster.local",
               "port_value": 9977
              }
             }
            }
           }
          ]
         }
        ]
       },
       "respect_dns_ttl": true
      },
      {
       "name": "gloo.gloo-system.svc.cluster.local:9966",
       "type": "STRICT_DNS",
       "connect_timeout": "5s",
       "http2_protocol_options": {},
       "alt_stat_name": "metrics_cluster",
       "load_assignment": {
        "cluster_name": "gloo.gloo-system.svc.cluster.local:9966",
        "endpoints": [
         {
          "lb_endpoints": [
           {
            "endpoint": {
             "address": {
              "socket_address": {
               "address": "gloo.gloo-system.svc.cluster.local",
               "port_value": 9966
              }
             }
            }
           }
          ]
         }
        ]
       }
      },
      {
       "name": "admin_port_cluster",
       "type": "STATIC",
       "connect_timeout": "5s",
       "load_assignment": {
        "cluster_name": "admin_port_cluster",
        "endpoints": [
         {
          "lb_endpoints": [
           {
            "endpoint": {
             "address": {
              "socket_address": {
               "address": "127.0.0.1",
               "port_value": 19000
              }
             }
            }
           }
          ]
         }
        ]
       }
      }
     ]
    },
    "dynamic_resources": {
     "lds_config": {
      "ads": {}
     },
     "cds_config": {
      "ads": {}
     },
     "ads_config": {
      "api_type": "GRPC",
      "grpc_services": [
       {
        "envoy_grpc": {
         "cluster_name": "gloo.gloo-system.svc.cluster.local:9977"
        }
       }
      ],
      "rate_limit_settings": {}
     }
    },
    "stats_sinks": [
     {
      "name": "envoy.metrics_service",
      "config": {
       "grpc_service": {
        "envoy_grpc": {
         "cluster_name": "gloo.gloo-system.svc.cluster.local:9966"
        }
       }
      }
     }
    ],
    "admin": {
     "access_log_path": "/dev/null",
     "address": {
      "socket_address": {
       "address": "127.0.0.1",
       "port_value": 19000
      }
     }
    }
   },
   "last_updated": "2019-10-30T16:20:10.076Z"
  },
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.ClustersConfigDump",
   "version_info": "14000603947059023502",
   "static_clusters": [
    {
     "cluster": {
      "name": "admin_port_cluster",
      "type": "STATIC",
      "connect_timeout": "5s",
      "load_assignment": {
       "cluster_name": "admin_port_cluster",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "127.0.0.1",
              "port_value": 19000
             }
            }
           }
          }
         ]
        }
       ]
      }
     },
     "last_updated": "2019-10-30T16:20:10.078Z"
    },
    {
     "cluster": {
      "name": "gloo.gloo-system.svc.cluster.local:9966",
      "type": "STRICT_DNS",
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "alt_stat_name": "metrics_cluster",
      "load_assignment": {
       "cluster_name": "gloo.gloo-system.svc.cluster.local:9966",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "gloo.gloo-system.svc.cluster.local",
              "port_value": 9966
             }
            }
           }
          }
         ]
        }
       ]
      }
     },
     "last_updated": "2019-10-30T16:20:10.078Z"
    },
    {
     "cluster": {
      "name": "gloo.gloo-system.svc.cluster.local:9977",
      "type": "STRICT_DNS",
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "alt_stat_name": "xds_cluster",
      "upstream_connection_options": {
       "tcp_keepalive": {}
      },
      "load_assignment": {
       "cluster_name": "gloo.gloo-system.svc.cluster.local:9977",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "gloo.gloo-system.svc.cluster.local",
              "port_value": 9977
             }
            }
           }
          }
         ]
        }
       ]
      },
      "respect_dns_ttl": true
     },
     "last_updated": "2019-10-30T16:20:10.078Z"
    }
   ],
   "dynamic_active_clusters": [
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "default-kubernetes-443_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.680Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "extauth_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "health_checks": [
       {
        "timeout": "5s",
        "interval": "60s",
        "unhealthy_threshold": 5,
        "healthy_threshold": 5,
        "grpc_health_check": {
         "service_name": "ext-auth"
        }
       }
      ],
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.665Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-apiserver-ui-8080_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.654Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-apiserver-ui-gloo-8080_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.655Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-extauth-8083_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.669Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-gateway-443_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.656Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-gateway-proxy-v2-443_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.658Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-gateway-proxy-v2-80_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.664Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-gateway-proxy-v2-gateway-proxy-443_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.672Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-gateway-proxy-v2-gateway-proxy-80_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.674Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-gloo-9966_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.664Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-gloo-9977_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.674Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-gloo-9988_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.666Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-glooe-grafana-80_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.684Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-glooe-prometheus-ku-e95ea267dd395e5c7111d7dff3d2dd3_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.681Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-glooe-prometheus-kube-state-metrics-80_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.660Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-glooe-prometheus-server-80_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.670Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-glooe-prometheus-server-prometheus-8-4-1-tiller-80_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.661Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-rate-limit-18081_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.681Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "gloo-system-redis-6379_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.685Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:default-kubernetes-443_default",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.654Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-apiserver-ui-8080_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.678Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-extauth-8083_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.685Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-gateway-443_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.682Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-gateway-proxy-v2-443_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.667Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-gateway-proxy-v2-80_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.668Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-gloo-9966_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.668Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-gloo-9977_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.680Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-gloo-9988_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.683Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-glooe-grafana-80_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.662Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-glooe-prometheus-kube-state-metrics-80_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.683Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-glooe-prometheus-server-80_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.669Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-rate-limit-18081_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.678Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:gloo-system-redis-6379_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.684Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:kube-system-kube-dns-53_kube-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.672Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-svc:kube-system-kube-dns-9153_kube-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.663Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-system-kube-dns-53_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.670Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "kube-system-kube-dns-9153_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.671Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "rate-limit_gloo-system",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "connect_timeout": "5s",
      "health_checks": [
       {
        "timeout": "5s",
        "interval": "60s",
        "unhealthy_threshold": 5,
        "healthy_threshold": 5,
        "grpc_health_check": {
         "service_name": "ratelimit"
        }
       }
      ],
      "http2_protocol_options": {},
      "metadata": {}
     },
     "last_updated": "2019-10-30T16:25:20.665Z"
    },
    {
     "version_info": "14000603947059023502",
     "cluster": {
      "name": "weather_gloo-system",
      "type": "STRICT_DNS",
      "connect_timeout": "5s",
      "dns_lookup_family": "V4_ONLY",
      "metadata": {},
      "load_assignment": {
       "cluster_name": "weather_gloo-system",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "api.openweathermap.org",
              "port_value": 80
             }
            }
           }
          }
         ]
        }
       ]
      }
     },
     "last_updated": "2019-10-30T16:25:20.679Z"
    }
   ]
  },
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.ListenersConfigDump",
   "version_info": "15697531463073637452",
   "static_listeners": [
    {
     "listener": {
      "name": "prometheus_listener",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 8081
       }
      },
      "filter_chains": [
       {
        "filters": [
         {
          "name": "envoy.http_connection_manager",
          "config": {
           "codec_type": "auto",
           "http_filters": [
            {
             "name": "envoy.router",
             "config": {}
            }
           ],
           "stat_prefix": "prometheus",
           "route_config": {
            "name": "prometheus_route",
            "virtual_hosts": [
             {
              "routes": [
               {
                "match": {
                 "path": "/ready",
                 "headers": [
                  {
                   "name": ":method",
                   "exact_match": "GET"
                  }
                 ]
                },
                "route": {
                 "cluster": "admin_port_cluster"
                }
               },
               {
                "route": {
                 "prefix_rewrite": "/stats/prometheus",
                 "cluster": "admin_port_cluster"
                },
                "match": {
                 "prefix": "/metrics",
                 "headers": [
                  {
                   "name": ":method",
                   "exact_match": "GET"
                  }
                 ]
                }
               }
              ],
              "domains": [
               "*"
              ],
              "name": "prometheus_host"
             }
            ]
           }
          }
         }
        ]
       }
      ]
     },
     "last_updated": "2019-10-30T16:20:10.080Z"
    }
   ],
   "dynamic_active_listeners": [
    {
     "version_info": "15697531463073637452",
     "listener": {
      "name": "listener-::-8080",
      "address": {
       "socket_address": {
        "address": "::",
        "port_value": 8080,
        "ipv4_compat": true
       }
      },
      "filter_chains": [
       {
        "filters": [
         {
          "name": "envoy.http_connection_manager",
          "config": {
           "normalize_path": true,
           "stat_prefix": "http",
           "rds": {
            "route_config_name": "listener-::-8080-routes",
            "config_source": {
             "ads": {}
            }
           },
           "upgrade_configs": [
            {
             "upgrade_type": "websocket"
            }
           ],
           "http_filters": [
            {
             "name": "envoy.fault"
            },
            {
             "name": "envoy.cors"
            },
            {
             "name": "io.solo.filters.http.sanitize",
             "config": {
              "headersToRemove": [
               "x-user-id"
              ]
             }
            },
            {
             "name": "envoy.ext_authz",
             "config": {
              "grpcService": {
               "timeout": "0.200s",
               "envoyGrpc": {
                "clusterName": "extauth_gloo-system"
               }
              }
             }
            },
            {
             "name": "io.solo.filters.http.solo_jwt_authn",
             "config": {
              "filterStateRules": {
               "requires": {},
               "name": "filterState"
              },
              "providers": {}
             }
            },
            {
             "name": "envoy.filters.http.rbac"
            },
            {
             "name": "io.solo.transformation"
            },
            {
             "name": "envoy.rate_limit",
             "config": {
              "requestType": "both",
              "domain": "custom",
              "rateLimitService": {
               "grpcService": {
                "envoyGrpc": {
                 "clusterName": "rate-limit_gloo-system"
                }
               }
              },
              "stage": 1,
              "timeout": "0.100s"
             }
            },
            {
             "name": "envoy.rate_limit",
             "config": {
              "timeout": "0.100s",
              "requestType": "both",
              "domain": "ingress",
              "rateLimitService": {
               "grpcService": {
                "envoyGrpc": {
                 "clusterName": "rate-limit_gloo-system"
                }
               }
              }
             }
            },
            {
             "name": "envoy.router"
            }
           ]
          }
         }
        ],
        "use_proxy_proto": false
       }
      ]
     },
     "last_updated": "2019-10-30T16:25:20.687Z"
    }
   ]
  },
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.ScopedRoutesConfigDump"
  },
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.RoutesConfigDump",
   "static_route_configs": [
    {
     "route_config": {
      "name": "prometheus_route",
      "virtual_hosts": [
       {
        "name": "prometheus_host",
        "domains": [
         "*"
        ],
        "routes": [
         {
          "match": {
           "path": "/ready",
           "headers": [
            {
             "name": ":method",
             "exact_match": "GET"
            }
           ]
          },
          "route": {
           "cluster": "admin_port_cluster"
          }
         },
         {
          "match": {
           "prefix": "/metrics",
           "headers": [
            {
             "name": ":method",
             "exact_match": "GET"
            }
           ]
          },
          "route": {
           "cluster": "admin_port_cluster",
           "prefix_rewrite": "/stats/prometheus"
          }
         }
        ]
       }
      ]
     },
     "last_updated": "2019-10-30T16:20:10.080Z"
    }
   ],
   "dynamic_route_configs": [
    {
     "version_info": "6784954065483923945",
     "route_config": {
      "name": "listener-::-8080-routes",
      "virtual_hosts": [
       {
        "name": "gloo-system_weather",
        "domains": [
         "*"
        ],
        "per_filter_config": {
         "envoy.ext_authz": {
          "disabled": true
         }
        }
       }
      ]
     },
     "last_updated": "2019-10-30T16:26:39.663Z"
    }
   ]
  },
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.SecretsConfigDump"
  }
 ]
}

**Comment by ashleywang1** [comment] 2019-12-18 20:20
https://github.com/solo-io/gloo/pull/1925

**Comment by marcogschmidt** [comment] 2020-01-06 14:19
Closing as duplicate of #1245

**Closed by marcogschmidt** 2020-01-06 14:19 UTC
Labels: Impact: M, Size: M, Type: bug
