### ISSUE TITLE
RBAC not getting cleaned up for master CI runs

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#1944] opened 2019-12-13 19:00 UTC
Master leaving RBAC resources on the cluster that don't get cleaned up:

solo-projects on  checks [$!] via 🐹 v1.12.5 at ☸️  gke_solo-public_us-central1-a_kube2e-tests
➜ k delete clusterrolebinding -l app=gloo
clusterrolebinding.rbac.authorization.k8s.io "gloo-role-binding-ingress-test-1d78e48f-5fbf-4532-ad07-d832703296c6" deleted
clusterrolebinding.rbac.authorization.k8s.io "gloo-role-binding-knative-test-1d78e48f-5fbf-4532-ad07-d832703296c6" deleted

solo-projects on  checks [$!] via 🐹 v1.12.5 at ☸️  gke_solo-public_us-central1-a_kube2e-tests
➜ k delete clusterrole -l app=gloo
clusterrole.rbac.authorization.k8s.io "gloo-role-ingress" deleted
clusterrole.rbac.authorization.k8s.io "gloo-role-knative" deleted

**Comment by marcogschmidt** [comment] 2019-12-30 14:11
Closing this as duplicate of #1957

**Closed by marcogschmidt** 2019-12-30 14:11 UTC
Labels: Type: bug
