### ISSUE TITLE
Inja validation of invalid Inja has incorrect behavior 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#7697] opened 2023-01-19 18:16 UTC
### Gloo Edge Version

1.12.x

### Kubernetes Version

None

### Describe the bug

When the Inja is invalid there is the following entry in the gloo pod logs

`{"level":"debug","ts":"2023-01-18T20:01:05.854Z","logger":"gloo-ee.v1.event_loop.gloo.reporter","caller":"reporter/reporter.go:309","msg":"wrote report for name:\"grpc\" namespace:\"gloo-system\" : state:Accepted reported_by:\"gloo\" subresource_statuses:{key:\"*v1.Proxy.gateway-proxy_gloo-system\" value:{state:Rejected reason:\"1 error occurred:\\n\\t* Route Error: ProcessingError. Reason: *transformer.plugin: envoy validation mode output: error initializing configuration '': Failed to parse response template: Failed to parse body template [inja.exception.parser_error] else without matching if\\n, error: exit status 1. Route Name: gloo-system_default-route-3-matcher-0\\n\\n\" reported_by:\"gloo\"}}","version":"1.12.33"} `

but Envoy is updated WITHOUT the transform filter configuration. Also, the gloo log entry above is debug and should be an error or warning. 

### Steps to reproduce the bug

Create a route with valid Inja. 

```
    - matchers:
      - prefix: /postmanecho/
      options:
        prefixRewrite: /
        transformations:
          responseTransformation:
            transformationTemplate:
              body:
                text: '{% if int(header("content-length")) > 2000 %} {"error" : "Too
                  Damn Big!!"} {% else %} {{ body() }} {% endif %}'
              headers:
                :status:
                  text: '{% if int(header("content-length")) > 2000 %}401{% else %}{{header(":status")
                    }}{% endif %}'
              parseBodyBehavior: DontParse
      routeAction:
        single:
          upstream:
            name: postman-echo.com
            namespace: gloo-system
```

All good. VS is accepted and Envoy is correctly updated. VS status is:

```
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system': {}
```

Remove the { at the beginning of the body.text Inja to create invalid Inja:

```
    - matchers:
      - prefix: /postmanecho/
      options:
        prefixRewrite: /
        transformations:
          responseTransformation:
            transformationTemplate:
              body:
                text: '% if int(header("content-length")) > 2000 %} {"error" : "Too
                  Damn Big!!"} {% else %} {{ body() }} {% endif %}'
              headers:
                :status:
                  text: '{% if int(header("content-length")) > 2000 %}401{% else %}{{header(":status")
                    }}{% endif %}'
              parseBodyBehavior: DontParse
      routeAction:
        single:
          upstream:
            name: postman-echo.com
            namespace: gloo-system
```

VS status is:

```
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system':
          reason: "1 error occurred:\n\t* Route Error: ProcessingError. Reason: *transformer.plugin:
            envoy validation mode output: error initializing configuration '': Failed
            to parse response template: Failed to parse body template [inja.exception.parser_error]
            else without matching if\n, error: exit status 1. Route Name: gloo-system_default-route-4-matcher-0\n\n"
          reportedBy: gloo
          state: Rejected
```

This creates the gloo log entry above

### Expected Behavior

Envoy should not be updated when there is invalid config

The gloo log entry should be a warning or error

**Comment by ben-taussig-solo** [comment] 2023-05-11 17:52
Hey! After some research, I believe the behavior described in the issue is not a bug

To address the issue, I recommend disabling the `gateway.validation.alwaysAccept` and `gateway.validation.allowWarnings` options in the settings CR. These options are enabled by default, and you can find more information about them in the reference here: [here](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk/#validationoptions). This will prevent Kubernetes from persisting resources with errors or warnings resulting from invalid configuration.

Unless a major rewrite is made, we do not have the capability to prevent Envoy's configuration from being updated when a virtual service (or any resource) is persisted with invalid config. During the translation process, all Gloo resources present in the cluster are translated into a single Envoy config, which is then sent to Envoy. If part of a resource is invalid, we will translate the valid portion while ignoring the invalid section. This is the behavior you are seeing -- the transformation route option contains invalid configuration, but the rest of the route is valid, so it is translated and sent to Envoy without the transformation. Because the virtual service has been overwritten in this case, we are not able to retain the old (valid) transformation configuration -- the persisted resource is the sole source of truth for the virtual service.

**Comment by ben-taussig-solo** [comment] 2023-05-11 18:09
> To address the issue, I recommend disabling the `gateway.validation.alwaysAccept` and `gateway.validation.allowWarnings` options in the settings CR. These options are enabled by default, and you can find more information about them in the reference here: [here](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk/#validationoptions). This will prevent Kubernetes from persisting resources with errors or warnings resulting from invalid configuration.


Update: Just chatted with @sam-heilbron about this, who mentioned that you may be using an older version of k8s which does not support this validation webhook functionality

**Comment by bdecoste** [comment] 2023-05-11 18:32
That's correct, this use-case has `allowWarnings: false` and `alwaysAccept: false`, but has the webhook disabled. But is taking advantage of the validation API directly from their deployment pipeline

**Comment by ben-taussig-solo** [comment] 2023-05-12 15:04
- There seems to be a discrepancy between the behavior of the validation webhook and the validation API as described in the issue. With the validation webhook enabled, I have confirmed that the VS with the invalid transformation gets rejected. In theory, the validation API and validation webhook should behave the same, so it seems strange that the invalid VS is accepted when using the validation API.
 - Can you go back to your client and confirm that their validation API configuration is working as expected?
 - I am looking to confirm that the validation API is consistent with the webhook myself. Can provide config/steps to replicate the environment from the issue so I can try to reproduce this behavior?

**Comment by ben-taussig-solo** [comment] 2023-05-15 17:57
Update: We have identified the cause of the bug -- In 1.12, we made significant changes to Gloo Edge translation, which result in `proxy` subresources generated from VS definitions not being persisted by default. Some of our `glooctl` functionality (namely, `glooctl get proxies`) was updated with this change in mind, so that it can access non-persisted `proxy` resources. However, `glooctl check` was not. Specifically, `glooctl check` only evaluates persisted resources, which prevents it from identifying errors like the one described in this issue.

I am actively working on a fix for `glooctl check`, which will make it so that `glooctl check` can access non-persisted `proxy` resources and report errors on them. I will update this issue when the fix is ready.

In the meantime, you may be able to work around this issue by setting `persistProxySpec` to true in your `settings` object. This will cause the `proxy` subresource to be persisted, which will allow `glooctl check` to access it and report errors on it. However, it may not be desirable to persist the `proxy` subresource -- I am not sure what the implications of doing so are.

Summary:
 - There is a bug in `glooctl check`
 - I am working on a fix and will update the issue when it is ready
 - In the meantime, you may be able to work around this issue by setting `persistProxySpec` to true in your `settings` object.

**Comment by ben-taussig-solo** [comment] 2023-05-19 18:50
The glooctl fix has been merged into the following Gloo Enterprise versions (some not-yet released at the time of writing this comment):
 - 1.15.0-beta2
 - 1.14.2
 - 1.13.18
 - 1.12.55

**Closed by ben-taussig-solo** 2023-05-19 18:50 UTC
Labels: Type: Bug, release/1.14, release/1.15, release/1.13, release/1.12
