### ISSUE TITLE
support reusing vservice domains to populate sslconfig sniDomains

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2387] opened 2020-02-08 19:43 UTC
currently we require a user to provide SNI Domains manually on an SSL-configured VService in addition to the domains that are already there (except if only one VService is defined which uses SSL).

we should consider providing an option (and/or a default?) which automatically inherits the SNI domains on the ssl config from the top-level VirtualService Domains

**Comment by rickducott** [comment] 2020-02-10 21:05
Closing as a dupe of https://github.com/solo-io/gloo/issues/574

**Closed by rickducott** 2020-02-10 21:05 UTC
