### ISSUE TITLE
broken link to docs root

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2883] opened 2020-04-27 15:55 UTC
Select 1.3.0 in version drop down, start navigating docs, then click on "Gloo" in the left-hand menu. It goes to a 404

**Comment by kdorosh** [comment] 2020-05-04 15:35
Same problem occurs if you put in a bad url and then click "go to homepage", even on the latest version of the docs.

**Comment by kdorosh** [comment] 2020-05-04 15:36
Also the solo.io docs label in the top left corner always redirects to the company site, which seems wrong.

**Comment by kdorosh** [comment] 2020-05-11 15:28
closing as working as intended

**Closed by kdorosh** 2020-05-11 15:28 UTC
Labels: Type: Docs
