### ISSUE TITLE
Glooctl check ignore warning 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#4317] opened 2021-02-18 23:03 UTC
glooctl check stops at the first error, make glooctl scan for all errors then create a report (do not fail on the first error)

**Comment by law10k** [comment] 2021-02-19 15:18
Possible dupe of https://github.com/solo-io/gloo/issues/2952

I also saw another report of failing after first error this week, would be good to confirm the improvements are working as expected (and in which version)

**Closed** 2021-03-05 21:28 UTC
Labels: Type: Enhancement
