### ISSUE TITLE
Helm: Using `gatewayProxies.NAME.*` does not merge in default values

### ISSUE THREAD

**Issue by JoshVee** [solo-io/gloo#3946] opened 2020-12-03 07:38 UTC
**Describe the bug**
The helm deployment supports defining multiple gateway proxies using the `gatewayProxies.NAME.*` values format.

However, when using that approach you need to specify every value manually as the default values are not merged in. Without defining the correct values structure, the chart templates will not render.

https://github.com/solo-io/gloo/blob/master/install/helm/gloo/values-template.yaml#L92

The default values only defines a key of `gatewayProxy` and therefore the values are only merged when using that key.

**To Reproduce**
```
➜  helm template . --set gatewayProxies.test.name=test
Error: template: gloo/templates/9-gateway-proxy-configmap.yaml:21:18: executing "gloo/templates/9-gateway-proxy-configmap.yaml" at <$spec.configMap.data>: nil pointer evaluating interface {}.data

Use --debug flag to render out invalid YAML
```

**Expected behavior**
`gatewayProxies.NAME.*` should be merged with `gatewayProxies.gatewayProxy.*`

**Comment by estahn** [comment] 2020-12-03 22:04
One option could be to use [merge](https://yaml.org/type/merge.html):
```
gatewayProxyDefault: &gatewayProxyDefault
    name: Everyone has same name
    age: 5

foo: &foo
    <<: *gatewayProxyDefault

bar: &gatewayProxyDefault
    <<: *base
    age: 20
   
   
```

**Comment by Sodman** [comment] 2020-12-04 17:09
This is a duplicate of https://github.com/solo-io/gloo/issues/3142, we can continue the discussion there.

**Closed by Sodman** 2020-12-04 17:09 UTC
Labels: Type: Bug
