### ISSUE TITLE
gloo-ee-resource-rollout-check pod crashloops until gloo-ee-resource-rollout finishes

### ISSUE THREAD

**Issue by huzlak** [solo-io/gloo#8809] opened 2023-10-18 16:37 UTC
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.13.27

### Kubernetes Version

v1.24.0

### Describe the bug

When upgrading to 1.13.27, `gloo-ee-resource-rollout-check` pod gets into crashloop  with below error until `gloo-ee-resource-rollout` job finishes
```
Waiting for the enterprise resource rollout job to complete
Error from server (Forbidden): unknown
```
The job and the upgrade eventually finishes fine, but the behavior brakes tilt deployment.

### Expected Behavior

The pod should not crashloop, it should wait in running until the other job is finished and then exit gracefully.

### Steps to reproduce the bug

Run helm upgrade with gloo-ee v1.13.27 and observe the rollout-check job to fail until resource-rollout job finishes.

**Comment by sam-heilbron** [comment] 2023-10-19 15:50
Related to https://github.com/solo-io/solo-projects/issues/5439, so assigning @davidjumani

**Comment by davidjumani** [comment] 2023-10-19 16:06
This is caused by the rollout job role not having the "watch" permission on jobs. This would work on higher versions of Kubernetes but errors out in v1.24.0 as mentioned in the issue
cc @SantoDE 
This will be fixed via https://github.com/solo-io/gloo/pull/8810 when backported to 1.13.x

**Closed** 2023-10-20 23:07 UTC
Labels: Type: Bug, Priority: Blocker, release/1.14, release/1.15, release/1.13, release/1.16
