### ISSUE TITLE
glooctl proxy url not working on kind cluster

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#701] opened 2019-04-27 12:12 UTC
When using the kind (https://github.com/kubernetes-sigs/kind) cluster, glooctl proxy url does not appear to work correctly. Identical deployment on minikube does work.

**Comment by scranton** [comment] 2019-04-27 12:46
Looks like `glooctl proxy url` correctly returns gateway-proxy Pod NodeIP and service http port, but no content is returned from that connection.

**Comment by derrickburns** [comment] 2019-05-31 02:11
Did you get Gloo to work with `kind`.  I did not.

**Comment by ilevine** [comment] 2019-07-16 16:17
duplicate of #730 
this is most likely a Mac issue as gloo is tested to work on kind on linux.

**Closed by ilevine** 2019-07-16 16:17 UTC
Labels: Area: dev, Size: S, Type: bug
