### ISSUE TITLE
zero-downtime rollout of Istio+Gloo with Strict mTLS

### ISSUE THREAD

**Issue by jlewis42lines** [solo-io/gloo#3994] opened 2020-12-16 00:33 UTC
**Is your feature request related to a problem? Please describe.**
I would like to perform a zero-downtime migration to mTLS STRICT mode when using Istio+Gloo. Istio seems to [support this](https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/) with PERMISSIVE mode, but adding `sslConfig` to a gloo Upstream while istio is in PERMISSIVE mode causes the following error.

```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

**Describe the solution you'd like**
I'm opened to suggestions. Having an mTLS PERMISSIVE mode in gloo, similar to what's available in istio, would seem like one possible solution.

**Describe alternatives you've considered**
None of the solutions I've come up with thus far satisfy the requirement for a zero downtime (or near zero downtime) transition.

**Additional context**
None.

**Comment by pwoelfle** [comment] 2021-04-23 07:08
We have the same problem. In our setup we access an application through Gloo Gateway Proxy. The connection between both must be mTLS secured using Istio. Internally, this application must also be accessible without mTLS.
Therefore, we want to use Istio mTLS PERMISSIVE mode.

When we try making a call we receive the following error as well:
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

The problem is that Gloo Gateway Proxy sends its TLS Client Hello with `http/1.1` as ALPN Protocol. But Istio assumes `istio`, `istio-http/1.0`, `istio-http/1.1` or `istio-h2` as ALPN Protocol when mTLS should be used. Consequently, this connection is handled as plain text from Istio's perspective but as mTls from Gloo's perspective.

As stated in [Gloo's documentation (Istio mTLS)](https://docs.solo.io/gloo-edge/latest/guides/integrations/service_mesh/gloo_istio_mtls/#upstream-changes) `istio` should be also set as ALPN protocol on the `Upstream` object:

```
...
  sslConfig:
    alpnProtocols:
    - istio
...
```

<img width="977" alt="Screen Shot 2021-04-23 at 07 50 36" src="https://user-images.githubusercontent.com/24274870/115830243-4fc9f680-a410-11eb-952c-b5836bfa9d69.png">

The reason is that resolving the common ssl config of the SDS missed to set the configured ALPN protocol at following location:
https://github.com/solo-io/gloo/blob/v1.7.2/projects/gloo/pkg/utils/ssl.go#L250

After changing this part to the following it worked as expected:

```go
...
	} else if sslSecrets := cs.GetSds(); sslSecrets != nil {
		tlsContext, err := s.handleSds(sslSecrets, verifySanListToMatchSanList(cs.GetVerifySubjectAltName()))
		if err != nil {
			return nil, err
		}
		tlsContext.AlpnProtocols = cs.GetAlpnProtocols()
		return tlsContext, err
	} else {
...
```

<img width="979" alt="Screen Shot 2021-04-23 at 08 22 11" src="https://user-images.githubusercontent.com/24274870/115832356-18a91480-a413-11eb-8c3b-537873f3904d.png">

**Closed** 2021-04-23 17:02 UTC
Labels: Type: Enhancement
