### ISSUE TITLE
Provide an Operator for installation

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3057] opened 2020-05-22 13:15 UTC
**Is your feature request related to a problem? Please describe.**
The OpenShift community is moving more and more to using [operators ](https://operatorhub.io/what-is-an-operator) for installing Kubernetes applications. Currently Gloo's installation is primarily `helm` based.

**Describe the solution you'd like**
An operator for installing and operating (i.e. upgrading) Gloo

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kdorosh** [comment] 2020-05-22 13:31
closing as duplicate of https://github.com/solo-io/gloo/issues/430

**Closed by kdorosh** 2020-05-22 13:31 UTC
Labels: Type: Enhancement
