### ISSUE TITLE
`glooctl dashboard` 

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#1738] opened 2019-11-18 19:42 UTC
`istioctl` has some nice commands for opening dashboards from the CLI. It would be nice to have something similar for gloo UI, envoy admin UI, and grafana dashboard

**Comment by GrahamGoudeau** [comment] 2019-11-18 20:42
@rickducott is this a duplicate of https://github.com/solo-io/gloo/issues/1706?

**Closed** 2019-12-12 19:53 UTC
