### ISSUE TITLE
Support load balancer setting for Discovered Upstreams?

### ISSUE THREAD

**Issue by mjaow** [solo-io/gloo#3983] opened 2020-12-14 06:12 UTC
**Is your feature request related to a problem? Please describe.**

Now it seems that gloo doesn't have settings to support load balancer policy for Discovered Upstreams. 

**Describe the solution you'd like**

Does it make sense to support? If it does, I'm glad to support it, it seems related to this file projects/gloo/pkg/plugins/kubernetes/uds_convert.go:45,  we can pass the settings here and read it in method createUpstream

**Describe alternatives you've considered**
It seems that we have to create a upstream by myself if I need to set the lb_policy

**Additional context**

**Comment by kdorosh** [comment] 2020-12-18 17:42
closing as a duplicate of https://github.com/solo-io/gloo/issues/3717

reprioritizing on our end, as this feature request continues to come up

**Closed by kdorosh** 2020-12-18 17:42 UTC
Labels: Type: Enhancement
