### ISSUE TITLE
Ability for UDS to add default circuit breaker config

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#4992] opened 2021-07-08 16:39 UTC
**Is your feature request related to a problem? Please describe.**
Add the ability to dynamically apply circuit breaker config to upstreams created by UDS, based on a selector

**Describe the solution you'd like**
Add the ability to dynamically apply circuit breaker config to upstreams created by UDS, based on a selector

**Describe alternatives you've considered**
manually apply circuit breaker config

**Additional context**

**Comment by sam-heilbron** [comment] 2021-07-09 15:27
Dupe of https://github.com/solo-io/gloo/issues/3717?

**Closed** 2021-07-09 15:28 UTC
Labels: Type: Enhancement
