### ISSUE TITLE
flake in rate limiting test - envoy 404

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#1864] opened 2019-12-10 00:44 UTC
Haven't seen this flake before -- envoy 404'd running a rate limit test. Extremely verbose logging in the build report: https://console.cloud.google.com/cloud-build/builds/6c1086b5-1e0c-4955-a6fe-2545fc498490?project=solo-public

**Comment by GrahamGoudeau** [comment] 2019-12-16 16:50
I think this may be a duplicate of https://github.com/solo-io/gloo/issues/1514

**Closed** 2020-02-11 18:19 UTC
Labels: Area: Tech debt, Type: bug
