### ISSUE TITLE
Gloo ingress does not seem to support default backend spec

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#617] opened 2019-03-26 18:49 UTC
Ingress' support a default backend spec where all traffic is to be routed to a service without needing to specify the path in the Ingress object

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petstore-ingress
 annotations:
    kubernetes.io/ingress.class: gloo
spec:
  backend:
    serviceName: petstore
    servicePort: 8080
```

https://kubernetes.io/docs/concepts/services-networking/ingress/#single-service-ingress

It looks like Gloo is NOT configuring an Envoy listener as I'm assuming no route rules are created for this Ingress spec. This Ingress spec should create a wildcard route in Gloo for all traffic.

**Comment by ilevine** [comment] 2019-07-16 14:35
duplicate of #507

**Closed by ilevine** 2019-07-16 14:35 UTC

**Comment by scranton** [comment] 2019-07-16 16:49
Issue #507 is about Gloo being default Ingress controller for cluster, i.e. no extra annotation needed. This is about how Gloo processes a specific Ingress manifest configuration, that is an Ingress with no routes specified is to have the Ingress controller foward all request traffic to specified backend, which Gloo currently does not do.

This issue is about more fully handling common Ingress manifest configurations to make easier for users to migrate to Gloo from other Ingress controller providers.
