### ISSUE TITLE
Malformed WAF SecRule Breaks Envoy Updates

### ISSUE THREAD

**Issue by xbglowx** [solo-io/gloo#5082] opened 2021-07-28 15:24 UTC
**Describe the bug**
While modifying an existing WAF SecRule, I accidentally separated two entries using a `.` instead of `,`. The kubectl apply went fine, but caused problems for gloo/envoy with making any future changes. Eventually, Gloo/Envoy started to serve 404s, as if the VirtualService no longer existed, as if there was no VirtualServicde with a domain entry that matched Host header. Once the typo was fixed, things returned to normal.

**To Reproduce**
1. Create a VirtualService without waf
2. Modify VirtualService to include malformed waf; replace `,` with `.` to separate ip entries:
   * ```
      waf:
        ruleSets:
        - ruleStr: |
            SecRuleEngine On
            SecAuditLogParts AHKZ
            SecAuditLogFormat JSON
            SecDebugLog /dev/stdout
            SecDebugLogLevel 4
            SecDefaultAction "phase:1,log,auditlog,deny,status:403"
            SecRule REMOTE_ADDR "!@ipMatch 173.245.48.0/20.103.21.244.0/22" "phase:1,deny,status:403,id:1,msg:'block ip'"
      ```

**Expected behavior**
Validating webhook should prevent this from being applied

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: 1.6.28
- Kubernetes version: 1.18

**Comment by DuncanDoyle** [comment] 2024-02-05 15:19
Duplicate of #8442

**Comment by davidjumani** [comment] 2024-06-21 20:11
This fix will be in 1.17.0

**Closed by davidjumani** 2024-06-21 20:11 UTC
Labels: Type: Bug, Impact: L, Priority: High, Area: WAF
