### ISSUE TITLE
Validate Upstreams

### ISSUE THREAD

**Issue by snuggie12** [solo-io/gloo#5157] opened 2021-08-12 21:11 UTC
**Is your feature request related to a problem? Please describe.**
It is possible to create a schema-valid upstream but still cause issues. One example would be if you used a `secretRef` but pointed it at a secret that does not exist.

**Describe the solution you'd like**
Just as `VirtualServices` have a validation webhook it'd be nice if `Upstream` did as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by kdorosh** [comment] 2021-08-12 21:21
closing as duplicate of https://github.com/solo-io/gloo/issues/2797

**Closed by kdorosh** 2021-08-12 21:21 UTC
Labels: Type: Enhancement
