### ISSUE TITLE
Add ability to specify deployment metadata for the gloo components via helm

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#6453] opened 2022-05-13 14:44 UTC
### Version

1.11.x (latest stable)

### Is your feature request related to a problem? Please describe.

Gloo current has the ability to specify labels and annotation on the gateway proxy pod

https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/enterprise_helm_chart_values/

gloo.gatewayProxies.NAME.podTemplate.extraGatewayProxyLabels.NAME
gloo.gatewayProxies.NAME.podTemplate.extraAnnotations.NAME

The enhancement would be to allow a similar override for the deployment.

### Describe the solution you'd like

Something similar to the pod:

```
gloo.gatewayProxies.NAME.deployment.extraGatewayProxyLabels.NAME
gloo.gatewayProxies.NAME.deployment.extraAnnotations.NAME
```

**Comment by chrisgaun** [comment] 2022-05-13 15:42
This might be a dupe. cc @GregHanson

**Comment by Bslabe123** [comment] 2023-02-15 20:07
[Confirmed dupe, closing](https://github.com/solo-io/gloo/blob/438d29315843696addb5930b2bad8815cc0daf8a/install/helm/gloo/generate/values.go#L493-L509)

**Closed by Bslabe123** 2023-02-15 20:07 UTC
Labels: Type: Enhancement, Good First Issue
