### ISSUE TITLE
"glooctl debug logs" ignores -f, writes to stdout

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#3604] opened 2020-09-04 18:22 UTC
**Describe the bug**
"glooctl debug logs" ignores the -f flag as an option to redirect output.  Instead, it writes to stdout even when -f is specified.  

**To Reproduce**
1. glooctl debug logs -f gloo-debug.log
2. Observe logs written to stdout instead.

**Expected behavior**
Expected behavior is documented here: glooctl debug logs -h
When -f is specified, logs should be written to specified file instead of stdout.

**Additional context**
% glooctl version
Client: {"version":"1.4.11"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.4.11","Name":"grpcserver-ui","Registry":"quay.io/solo-io"},{"Tag":"1.4.11","Name":"grpcserver-ee","Registry":"quay.io/solo-io"},{"Tag":"1.4.11","Name":"grpcserver-envoy","Registry":"quay.io/solo-io"},{"Tag":"1.4.11","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.4.11","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.4.11","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.4.11","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.4.11","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.4.11","Name":"observability-ee","Registry":"quay.io/solo-io"},{"Tag":"1.4.11","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}

**Comment by kdorosh** [comment] 2020-11-06 18:23
closing as duplicate of https://github.com/solo-io/gloo/issues/3124

**Closed by kdorosh** 2020-11-06 18:23 UTC
Labels: Type: Bug
