### ISSUE TITLE
Add docs for TLS Termination at NLB

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#4549] opened 2021-04-05 22:15 UTC
**Describe the requested changes**

Questions on TLS termination at AWS NLB are asked a lot. A Doc walking through this process could be quite handy.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/latest/...
2. ...

**Browser Information**
If the change isn't related to content, please include your browser version and any other relevant information 
(e.g., browser zoom) to help us reproduce docs-related bugs.

**Additional context**

**Comment by chrisgaun** [comment] 2021-04-08 13:54
We can include this as part of #2102

**Comment by lgadban** [comment] 2021-06-14 22:45
looks to be fixed in https://github.com/solo-io/gloo/pull/4670

**Comment by kevin-shelaga** [comment] 2021-06-14 23:15
Doesn't look like there are any details about implementing tls termination at the LB

https://docs.solo.io/gloo-edge/latest/guides/integrations/aws/

**Comment by lgadban** [comment] 2021-06-14 23:20
That's what initially threw me off.
The problem is that it's only available on the `master` branch of the docs:
https://docs.solo.io/gloo-edge/master/guides/integrations/aws/#tls-termination-at-load-balancer-level

**Comment by lgadban** [comment] 2021-06-14 23:21
Probably warrants a discussion about versioning of the docs, having them live inside the same repo and pipeline as the code, etc

**Comment by kevin-shelaga** [comment] 2021-06-14 23:49
You're right, I didn't think to check master. Thank you 🙏

**Closed** 2021-06-14 23:50 UTC
Labels: Type: Docs
