### ISSUE TITLE
Helm values for nodeSelector and taint tolerations

### ISSUE THREAD

**Issue by mattchrist** [solo-io/gloo#2734] opened 2020-04-06 16:37 UTC
I can specify nodeSelector and taint tolerations for the 'gateway-proxy' pods via helm chart values, but I'm not seeing the same settings for gloo, discovery, gateway pods.

https://docs.solo.io/gloo/latest/reference/helm_chart_values/

Is there a way to deploy these settings with helm?

A workaround is to patch the deployments with tolerations and nodeSelectors after helm deploys.

**Comment by kdorosh** [comment] 2020-04-23 19:52
Another workaround is to leverage kustomize for any helm customizations you'd like to make to our chart until we have a chance to expose every setting that's requested. For more, read here: https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/helm_advanced/

**Comment by kdorosh** [comment] 2020-04-23 20:12
closing as duplicate of https://github.com/solo-io/gloo/issues/1995

**Closed by kdorosh** 2020-04-23 20:12 UTC
Labels: Area: Helm, Type: Enhancement
