### ISSUE TITLE
extauth error log with double version

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#5223] opened 2021-08-24 13:52 UTC
Error logs from extAuth component, showing `version` several times. One being `undefined`

Find following version attribute at the end of the log trace:
```
"version":"1.8.0","version":"undefined"}
```

```
{"level":"info","ts":"2021-08-24T13:41:02.492Z","caller":"runner/xds.go:125","msg":"{\"auth_config_ref_name\":\"upsell-services-modal.auth-gate-rpc-shopkeeper\",\"configs\":[{\"AuthConfig\":{\"PassThroughAuth\":{\"Protocol\":{\"Grpc\":{\"address\":\"auth-gate-rpc.upsell-services-modal.svc.cluster.local:50059\"}}}}}]}","version":"1.8.0","version":"undefined"}
```

**Comment by kevin-shelaga** [comment] 2021-08-24 16:18
https://github.com/solo-io/gloo/issues/4231

**Comment by sam-heilbron** [comment] 2021-08-31 18:07
Closing. Duplicate of https://github.com/solo-io/gloo/issues/4231

**Closed by sam-heilbron** 2021-08-31 18:07 UTC
Labels: Type: Bug, Good First Issue, Priority: Low, Triage: Duplicate
