### ISSUE TITLE
Validation Webhook not rejecting VirtualServices with invalid Upstream

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3104] opened 2020-06-02 22:59 UTC
**Describe the bug**
The validation webhook seems to accept a VirtualService which references a non-existent Upstream.

**To Reproduce**
Set webhook to not always accept (this probably shouldn't matter as even if we are just logging we should see a rejection log for a VS with an invalid US)
```
  gateway:
    validation:
      alwaysAccept: false
      proxyValidationServerAddr: gloo:9988
```

Create a VS that references a bogus US:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - 'domain1'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080-bad
            namespace: gloo-system
```

And watch the debug logs in the webhook
```
{"level":"info","ts":1591137437.4580817,"logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook","caller":"k8sadmisssion/validating_admission_webhook.go:143","msg":"received validation request","version":"1.3.28"}
{"level":"dpanic","ts":1591137437.5080988,"logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook.gateway-validator","caller":"zap@v1.13.0/sugar.go:173","msg":"Ignored key-value pairs with non-string keys.","version":"1.3.28","invalid":[{"position":0,"key":"virtual_host:<domains:\"domain1\" routes:<matchers:<prefix:\"/\" > route_action:<single:<upstream:<name:\"default-petstore-8080-bad\" namespace:\"gloo-system\" > > > > > status:<> metadata:<name:\"petstore\" namespace:\"gloo-system\" annotations:<key:\"kubectl.kubernetes.io/last-applied-configuration\" value:\"{\\\"apiVersion\\\":\\\"gateway.solo.io/v1\\\",\\\"kind\\\":\\\"VirtualService\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"petstore\\\",\\\"namespace\\\":\\\"gloo-system\\\"},\\\"spec\\\":{\\\"virtualHost\\\":{\\\"domains\\\":[\\\"domain1\\\"],\\\"routes\\\":[{\\\"matchers\\\":[{\\\"prefix\\\":\\\"/\\\"}],\\\"routeAction\\\":{\\\"single\\\":{\\\"upstream\\\":{\\\"name\\\":\\\"default-petstore-8080-bad\\\",\\\"namespace\\\":\\\"gloo-system\\\"}}}}]}}}\\n\" > generation:1 > ","value":{"name":"petstore","namespace":"gloo-system"}}],"stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/validation.(*validator).validateSnapshot\n\t/workspace/gloo/projects/gateway/pkg/validation/validator.go:229\ngithub.com/solo-io/gloo/projects/gateway/pkg/validation.(*validator).ValidateVirtualService\n\t/workspace/gloo/projects/gateway/pkg/validation/validator.go:266\ngithub.com/solo-io/gloo/projects/gateway/pkg/services/k8sadmisssion.(*gatewayValidationWebhook).validateVirtualService\n\t/workspace/gloo/projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go:388\ngithub.com/solo-io/gloo/projects/gateway/pkg/services/k8sadmisssion.(*gatewayValidationWebhook).validate\n\t/workspace/gloo/projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go:353\ngithub.com/solo-io/gloo/projects/gateway/pkg/services/k8sadmisssion.(*gatewayValidationWebhook).makeAdmissionResponse\n\t/workspace/gloo/projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go:248\ngithub.com/solo-io/gloo/projects/gateway/pkg/services/k8sadmisssion.(*gatewayValidationWebhook).ServeHTTP\n\t/workspace/gloo/projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go:174\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2387\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.initNPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3365\nnet/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5713"}
{"level":"debug","ts":1591137437.5080535,"logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook.gateway-validator","caller":"validation/validator.go:229","msg":"Accepted %T %v","version":"1.3.28"}
{"level":"debug","ts":1591137437.5109951,"logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook","caller":"k8sadmisssion/validating_admission_webhook.go:254","msg":"Succeeded, alwaysAccept: %v validationErr: %vfalse <nil>","version":"1.3.28"}
{"level":"info","ts":1591137437.5130534,"logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook","caller":"k8sadmisssion/validating_admission_webhook.go:198","msg":"Ready to write response ...","version":"1.3.28"}
{"level":"info","ts":1591137437.5131102,"logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook","caller":"k8sadmisssion/validating_admission_webhook.go:204","msg":"responded with review: {\"response\":{\"uid\":\"9cfbf869-a521-11ea-ab33-42010a800123\",\"allowed\":true}}","version":"1.3.28"}
```

**Expected behavior**
Based on the `alwaysAccept` value either a log stating this VS has an invalid US or rejecting the creation of this VS.

**Additional context**
```
% glooctl version
Client: {"version":"1.3.28"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.3.9","Name":"grpcserver-ui","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"grpcserver-ee","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"grpcserver-envoy","Registry":"quay.io/solo-io"},{"Tag":"1.3.28","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.3.28","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"observability-ee","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```

Also, There are a few debug logs that are not correctly interpolating variables resulting in unhelpful logs:

`Debugw(...)` not working correctly:
https://github.com/solo-io/gloo/blob/38f9985365c1d1411c83129282ecb960f2374443/projects/gateway/pkg/validation/validator.go#L229

Using `Debug(...)`:
https://github.com/solo-io/gloo/blob/38f9985365c1d1411c83129282ecb960f2374443/projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go#L254

**Comment by kdorosh** [comment] 2020-06-19 19:12
@lgadban this should be addressed by exposing the `allowWarnings` validations setting (default true). by setting to false validation should reject this resource.

this change is in v1.4.0-beta15 and v1.3.30 of open source, closed source releases coming in the next couple days

**Comment by kdorosh** [comment] 2020-06-29 20:19
Related to issue https://github.com/solo-io/gloo/issues/3099 and its resolution https://github.com/solo-io/gloo/pull/3155

**Comment by tkukushkin** [comment] 2020-09-16 11:28
@kdorosh `allowWarnings` setting does not help. I can create VirtualService with link to not existing upstream.

**Comment by kdorosh** [comment] 2021-04-01 20:21
Fix has been identified, closing as duplicate of https://github.com/solo-io/gloo/issues/4466#issuecomment-812101643

**Closed by kdorosh** 2021-04-01 20:21 UTC
Labels: Type: Bug
