### ISSUE TITLE
OTEL exporter isn't setting the Status code and Span name is no longer being set to the API path

### ISSUE THREAD

**Issue by sadieleob** [solo-io/gloo#9311] opened 2024-04-02 22:06 UTC
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.3

### Kubernetes Version

1.27

### Describe the bug

The collector is not setting the Status code and Name (name is et to Ingress instead of the API path). 

In the example below, the Span code does not reflect the request with response Codes 200, 404 or 503. 

ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope
Span #0
    Trace ID       : f8ec84b4621ca212283fb21538d20148
    Parent ID      :
    ID             : 9ff651b21612cc51
    Name           : ingress
    Kind           : Server
    Start time     : 2024-04-02 20:04:10.917227 +0000 UTC
    End time       : 2024-04-02 20:04:10.918204 +0000 UTC
    Status code    : Unset
    Status message :
Attributes:
     -> node_id: Str(gateway-proxy-66658d8644-27j5t.gloo-system-new)
     -> zone: Str()
     -> guid:x-request-id: Str(89d85fd0-346c-9381-b38f-3ad4fe78fa80)
     -> http.url: Str(http://localhost:8080/helloworld)
     -> http.method: Str(GET)
     -> downstream_cluster: Str(-)
     -> user_agent: Str(curl/8.4.0)
     -> http.protocol: Str(HTTP/1.1)
     -> peer.address: Str(127.0.0.1)
     -> request_size: Str(0)
     -> response_size: Str(11)
     -> component: Str(proxy)
     -> http.status_code: Str(404)
     -> response_flags: Str(-)
	{"kind": "exporter", "data_type": "traces", "name": "logging"}

### Expected Behavior

Span "Status code" should reflect the Status code in the response (OK or Error when appropriate).
Span "Name" should be set to the API path. 

### Steps to reproduce the bug

Follow the docs: https://docs.solo.io/gloo-edge/latest/guides/observability/tracing/otel/

Deploy Otel and Zipkin, configure VS with directResponseAction and try different statuses: 200, 404, and 503 to confirm that the Span Status code stays as Unset, instead of Ok or Error as per https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status

**Comment by DuncanDoyle** [comment] 2024-08-02 11:28
Dupe of https://github.com/solo-io/gloo/issues/9313 . Closing

**Closed by DuncanDoyle** 2024-08-02 11:28 UTC
Labels: Type: Bug
