### ISSUE TITLE
enhanced access logs

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3272] opened 2020-07-02 12:11 UTC
**Is your feature request related to a problem? Please describe.**
Require more fine grained access logs for flow through data plane

**Describe the solution you'd like**
Add the following timestamps to access logs:
1. Incoming request from consumer to vs
2. Entry when extauth process the request
3. Entry when rateLimit process the request
4. Outgoing request from data plane to upstream
5. Callback response from upstream to data plane.
6. Data plane response back to consumer

**Comment by bdecoste** [comment] 2020-07-02 12:12
Timestamps for 1,4,5,6 higher priority than 2 and 3. Ideally timestamps would be created for before and after each filter in the data plane and also at stages 1,4,5,6.

**Comment by kdorosh** [comment] 2020-07-02 15:48
closing as duplicate of https://github.com/solo-io/gloo/issues/2251

**Closed by kdorosh** 2020-07-02 15:48 UTC
Labels: Enterprise, Type: Enhancement
