### ISSUE TITLE
Masking of sensitive logs in extauth logs

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3699] opened 2020-10-01 20:33 UTC
**Describe the bug**
ExtAuth shouldn't log sensitive data

**To Reproduce**
Watch logs as requests are being sent to extauth

**Expected behavior**
Filtered/masked request attributes

**Comment by lgadban** [comment] 2020-10-01 20:33
Related: https://github.com/solo-io/gloo/issues/2486

**Comment by kdorosh** [comment] 2020-11-06 16:29
closing as duplicate of https://github.com/solo-io/gloo/issues/3105 , which has been resolved

`headersToRedact` is the new field. The headers are still logged, but with a redacted value

**Comment by lgadban** [comment] 2020-11-06 16:48
@kdorosh -- where is this field supposed to be set? there's no documentation I can find for this

**Comment by lgadban** [comment] 2020-11-06 16:51
I see that it is defined here: https://github.com/solo-io/solo-projects/blob/master/install/helm/gloo-ee/templates/_helpers.tpl#L157

But there is no user facing documentation for this setting

**Comment by lgadban** [comment] 2020-11-06 17:02
Also unsure on whether or not the default list contains the `authorization` header

**Closed** 2020-11-06 18:40 UTC
Labels: Enterprise, Type: Bug
