### ISSUE TITLE
gRPC Services

### ISSUE THREAD

**Issue by yoitsro** [solo-io/gloo#2488] opened 2020-02-24 17:35 UTC
I'm trying to simply route a gRPC request to an upstream service in Kubernetes, but it's not working and documentation for routing for gRPC services seems very sparse...

TLS should be terminated with gloo and then the request should be routed to the appropriate service. 

gloo is deployed to the `gloo-system` namespace.

Here's my virtual service configuration:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: grpc
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: wildcard-io
      namespace: gloo-system
    sniDomains:
      - "my.domain.io"
  virtualHost:
    domains:
      - "my.domain.io"
    routes:
      - matchers:
          - prefix: /my.Service/
        routeAction:
          single:
            upstream:
              name: staging-public-myservice-7001
              namespace: gloo-system
```

Here's the detected upstream service (`glooctl get upstream staging-public-myservice-7001 -n gloo-system -o yaml`):

```
discoveryMetadata: {}
kube:
  selector:
    app: myservice
    release: myservice
  serviceName: myservice
  serviceNamespace: staging-public
  servicePort: 7001
metadata:
  annotations:
  name: staging-public-myservice-7001
  namespace: gloo-system
status:
  reportedBy: gloo
  state: Accepted
useHttp2: true
```

I'm using a Node.js gRPC server without reflection support.

I'm getting a gRPC error status code of 12 (unimplemented). Any ideas what I'm missing?!

**Comment by ilackarms** [comment] 2020-03-12 20:12
hey @yoitsro can you retry the request while watching `glooctl proxy logs`? this config looks correct to me at first glance. `useHttp2` is the only field that should be required if both client and server are using grpc.

we can also look at the envoy config dump to make sure gloo is configuring Envoy correctly: `glooctl proxy dump`

please redact any sensitive fields as this will show the logs and configuration of your proxy. thanks for opening the issue!

**Comment by emaincourt** [comment] 2020-03-16 15:26
@yoitsro I could not get anything working without removing all the `sniDomains` part as said here in #2534. Did you eventually make it ?

**Comment by yoitsro** [comment] 2020-03-16 15:30
@ilackarms Thanks for the response.

However, and I'm sorry to be really unhelpful right now @emaincourt, but I gave up and ended up using my own fork of https://github.com/projectcontour/contour with CORS support: https://github.com/desanaio/contour

**Comment by kdorosh** [comment] 2020-05-06 14:12
closing as duplicate of https://github.com/solo-io/gloo/issues/2372

**Closed by kdorosh** 2020-05-06 14:12 UTC
Labels: Size: S, Type: Docs
