### ISSUE TITLE
Discrete control and data plane upgrades 

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4929] opened 2021-06-24 20:07 UTC
**Is your feature request related to a problem? Please describe.**
Ability to perform upgrades to the data plane and control plane separately
Allow data planes to connect to different control plane versions etc.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chrisgaun** [comment] 2021-08-31 20:12
Duplicate of https://github.com/solo-io/gloo/issues/5037

**Closed by chrisgaun** 2021-08-31 20:12 UTC
Labels: Type: Enhancement

**Comment by kdorosh** [comment] 2021-09-17 21:04
another way to accomplish this decoupling of lifecycle: https://docs.solo.io/gloo-edge/master/operations/production_deployment/#xds-relay

**Comment by lgadban** [comment] 2021-09-17 21:23
Not sure where else to add this but for operational control of upgrades it would be useful to be able to install control-plane and data-plane components as separate helm releases.

**Comment by kdorosh** [comment] 2021-09-17 21:24
Makes sense. In the interim, xds relay can play a similar role as control plane and it has its own helm release
