### ISSUE TITLE
Discovery service is consuming massive memory

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2607] opened 2020-03-15 21:29 UTC
<img width="1628" alt="Screen Shot 2020-03-15 at 2 28 53 PM" src="https://user-images.githubusercontent.com/583930/76711031-6b20e900-66c9-11ea-8148-83f62d3c7424.png">

**Comment by derrickburns** [comment] 2020-03-16 02:09
Different cluster:
<img width="1271" alt="Screen Shot 2020-03-15 at 7 08 42 PM" src="https://user-images.githubusercontent.com/583930/76717386-64f23300-66f0-11ea-9aed-acf0f41abc0d.png">

**Comment by derrickburns** [comment] 2020-03-16 02:10
<img width="1165" alt="Screen Shot 2020-03-15 at 7 09 57 PM" src="https://user-images.githubusercontent.com/583930/76717431-91a64a80-66f0-11ea-9014-dbb649a3007d.png">

**Comment by derrickburns** [comment] 2020-03-16 04:09
After only <7 hours:

<img width="1248" alt="Screen Shot 2020-03-15 at 9 08 37 PM" src="https://user-images.githubusercontent.com/583930/76722541-45afd180-6701-11ea-8fad-76f62c8806fe.png">

**Comment by rickducott** [comment] 2020-03-16 15:53
Thanks for the data points. I am escalating this internally and we will investigate.

**Comment by rickducott** [comment] 2020-03-16 19:16
Also reported: https://github.com/solo-io/gloo/issues/2361

**Comment by derrickburns** [comment] 2020-03-16 21:27
@rickducott Thanks.  Limits added!

**Comment by kdorosh** [comment] 2020-04-20 13:24
Closing as duplicate of https://github.com/solo-io/gloo/issues/2361 , which has been addressed in the versions listed at the bottom of the issue.

**Comment by kdorosh** [comment] 2020-04-20 13:25
@derrickburns which version were you running? https://github.com/solo-io/gloo/pull/2493 should have significantly decreased discovery memory usage

**Closed** 2021-07-21 15:15 UTC
Labels: Area: Stability, Type: Bug
