### ISSUE TITLE
`glooctl check` panic

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#5049] opened 2021-07-19 20:50 UTC
**Describe the bug**
glooctl check panic after helm upgrade

```
glooctl check           
                                               
Checking deployments... 4 Errors!
Checking pods... 16 Errors!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x422fcd9]

goroutine 1 [running]:
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/check.getNamespaces(0x4e10d10, 0xc000122008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /workspace/gloo/projects/gloo/cli/pkg/cmd/check/root.go:314 +0x59
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/check.CheckResources(0xc000d16a80, 0x0, 0x0)
        /workspace/gloo/projects/gloo/cli/pkg/cmd/check/root.go:100 +0x627
github.com/solo-io/gloo/projects/gloo/cli/pkg/cmd/check.RootCmd.func1(0xc000d26000, 0x68780b0, 0x0, 0x0, 0x0, 0x0)
        /workspace/gloo/projects/gloo/cli/pkg/cmd/check/root.go:55 +0x45
github.com/spf13/cobra.(*Command).execute(0xc000d26000, 0x68780b0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0xb56
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c72780, 0xc000d26000, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x755
github.com/spf13/cobra.(*Command).Execute(0xc000c72780, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897 +0x3b
main.main()
        /workspace/gloo/projects/gloo/cli/cmd/main.go:11 +0x37
```

**To Reproduce**
1. kube apply '...'
2. curl '....'
3. See error

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version - v1.8.0
- Kubernetes version - 1.20

**Comment by DuncanDoyle** [comment] 2024-06-17 13:11
Closing this one. Outdated and unable to reproduce.

**Closed by DuncanDoyle** 2024-06-17 13:11 UTC
Labels: Type: Bug, Area: Stability, Area: CLI
