### ISSUE TITLE
virtualservice creation on Windows doesn't work

### ISSUE THREAD

**Issue by stevef1uk** [solo-io/gloo#2731] opened 2020-04-04 07:53 UTC
Just trying the Hello World example using a Windows 10 laptop with Git Bash. I followed the tutorial and the output of:  'glooctl get virtualservice --output kube-yaml' gave:
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  creationTimestamp: null
  generation: 3
  name: default
  namespace: gloo-system
  resourceVersion: "1806"
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - exact: C:/Program Files/Git/all-pets
      options:
        prefixRewrite: C:/Program Files/Git/api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
status:
  reported_by: gateway
  state: 1
  subresource_statuses:
    '*v1.Proxy.gloo-system.gateway-proxy':
      reported_by: gloo
      state: 1

This looked odd to me with the 'C:/Programme Files' being included.
 
I then not surprisingly discovered that the ' curl $(glooctl proxy url)/all-pets' failed with 404.

Deleting the virtualservice & creating it on a Mac worked as expected with the tutorial working as expected.

**Comment by rickducott** [comment] 2020-04-17 16:08
We think this is a bug with our CLI, but you should be able to create the VS manually as a workaround @stevef1uk

**Comment by kdorosh** [comment] 2020-06-30 17:50
duplicate of https://github.com/solo-io/gloo/issues/2179

**Comment by jehawley** [comment] 2020-07-02 14:29
This is actually an issue in git bash. It interprets the route parameters in the `glooctl add route` command as Unix filepaths and mangles them. This can be avoided by prefixing the command with `MSYS_NO_PATHCONV=1`. We will update our documentation to note this workaround.

**Closed** 2020-07-06 14:16 UTC
Labels: Type: Bug
