### ISSUE TITLE
`glooctl proxy logs --debug false` doesn't honor debug flag

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1620] opened 2019-11-06 19:56 UTC
**Describe the bug**
`glooctl proxy logs` sets envoy log level to debug by default.

it also documents the `--debug` flag:
```
  -d, --debug    enable debug logging on the proxy as part of this command (default true)
```
This does not appear to be honored, if set to false.

**To Reproduce**
1. install fresh gloo on minikube
1. run `glooctl proxy logs -d false`
1. note debug logs in output

**Expected behavior**
no debug logs

**Additional context**
Relevant code: https://github.com/solo-io/gloo/blob/master/projects/gloo/cli/pkg/cmd/gateway/logs.go#L65

**Comment by kdorosh** [comment] 2020-01-23 14:19
more users being confused by the auto-debug setting logic in the command: https://solo-io.slack.com/archives/C9L6VPAUW/p1579769076130000

**Comment by rickducott** [comment] 2020-02-11 22:21
Closing as a dupe of https://github.com/solo-io/gloo/issues/945

**Closed by rickducott** 2020-02-11 22:21 UTC
Labels: Area: User Experience, Area: glooctl, Impact: M, Size: S, Type: bug, Usability
