### ISSUE TITLE
health checks + TLS secret rotation leads to a loss of cluster endpoints

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5442] opened 2021-10-06 12:41 UTC
Given a custom ExtAuth service configured via `namedExtauth`
And this authZ server is serving over HTTPS
And the Upstream CR representing this custom AuthZ server is configuring with a TLS secret (CA put in a trust store) and with health checks
And the TLS secret used by the Upstream CR and the upstream authZ server is the same (3 fields: tls.crt, tls.key, ca.crt)
And the `gateway-proxy` deployment is scaled to 3

When the TLS secret is rotated with cert-manager, 

Then, one of the 3 replicas of gw-proxy will start failing health checks on the extAuth Upstream because of TLS handshake errors

The full environment is here: https://gist.github.com/bcollard/a2993e57d2c408d237089a202f501991

**Comment by ben-taussig-solo** [comment] 2022-01-11 18:39
After some difficulty reproducing this issue, I reached out to @bcollard, who was also unable to reproduce the issue on v1.9.x and v1.8.9 (the version on which the issue was first reported). He also confirmed that the users who originally experienced the issue have a workaround. For these reasons, I am closing the issue until further notice.

**Closed by ben-taussig-solo** 2022-01-11 18:39 UTC
Labels: Type: Bug, Size: M
