### ISSUE TITLE
[Helm] add optional custom `options` to default gateways

### ISSUE THREAD

**Issue by via-jordan-sokolic** [solo-io/gloo#2535] opened 2020-03-01 08:53 UTC
Allow for adding custom options for the default HTTP and HTTPS gateways as deployed by the Gloo Helm chart.
Useful for adding access logging per the guide: https://docs.solo.io/gloo/latest/gloo_routing/virtual_services/routes/routing_features/transformations/enrich_access_logs

**Comment by via-jordan-sokolic** [comment] 2020-03-01 08:53
PR: https://github.com/solo-io/gloo/pull/2502

**Comment by kdorosh** [comment] 2020-03-03 14:14
Closed as duplicate of `gatewayProxies.NAME.gatewaySettings.customHttpGateway` setting

**Closed** 2020-03-03 16:19 UTC
