### ISSUE TITLE
Verifying Nested JWT Claims

### ISSUE THREAD

**Issue by jameyhammock** [solo-io/gloo#5337] opened 2021-09-16 16:44 UTC
**Is your feature request related to a problem? Please describe.**
With the below JWT payload, we'd be looking to verify something like the nested-permissions.HIGH-LEVEL.MID-LEVEL1 claim is present (in our case, not necessarily matching on a specific value).

{
  "ver": 1,
  "jti": "AT.Kk6aL6ucHE28Fk7taXDxRtz5VW03BsWf8ysguK5UK2s",
  "iss": "https://...",
  "iat": 1624970164,
  "exp": 1624973764,
  "cid": "0oaer3uhipkRrMNGE1t7",
  "uid": "00u2x904fhucm1gtm1t7",
  "scp": [
    "openid",
    "profile",
    "email"
  ],
  "sub": "username",
  "nested-permissions": {
    "HIGH-LEVEL": {
      "MID-LEVEL1": [
        "some-attribute"
      ],
      "MID_LEVEL2": [
        "some-other-attribute"
      ]
    }
  },
}

**Describe the solution you'd like**
Ideally, we'd love a way to refer to a specific part of a JWT claim like above and make use of the existing matching functionality Gloo already supports.  The addition of a new "exists" matcher would also be helpful.

**Describe alternatives you've considered**
We could certainly do these checks in our own custom ext auth implementation

**Additional context**

**Comment by chrisgaun** [comment] 2021-09-23 17:19
Duplicate of https://github.com/solo-io/gloo/issues/5338

**Closed by chrisgaun** 2021-09-23 17:19 UTC
Labels: Type: Enhancement
