### ISSUE TITLE
invalid VS shows error for all VSs in glooctl

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2485] opened 2020-02-22 13:47 UTC
`glooctl get vs` does not identify the individual invalid VS - all VSs show the error

**Comment by arianaw66** [comment] 2020-02-24 14:42
@bdecoste Looks like a duplicate of https://github.com/solo-io/gloo/issues/2228?

**Comment by rickducott** [comment] 2020-02-24 15:12
I think so - going to close this as a dupe

**Closed by rickducott** 2020-02-24 15:12 UTC
Labels: Type: Enhancement
