### ISSUE TITLE
gateway proxy AWS credentials from service account for invoking lambdas become stale

### ISSUE THREAD

**Issue by lilley2412** [solo-io/gloo#5253] opened 2021-08-27 15:34 UTC
**Describe the bug**
When using IAM for service accounts (not using static credentials) on gateway-proxy to invoke lambdas, over time the credentials become stale, resulting in an auth error.  

**To Reproduce**
1. Deploy gloo with IAM for service accounts credentials
2. Create a lambda upstream and route, validate that it works
3. Wait a while ... not sure how long as this happened to me over the weekend, but I'm guessing you may only need to wait for 1 sts token lifetime (60 mins?)
4. Make a request against the route and observe an authorization error in gateway-proxy logs:
```
gateway-proxy-8486f5bf59-mk96q gateway-proxy [2021-08-27 14:58:02.859][18][debug][router] [external/envoy/source/common/router/router.cc:1229] [C0][S5566255096063427617] upstream headers complete: end_stream=false
gateway-proxy-8486f5bf59-mk96q gateway-proxy [2021-08-27 14:58:02.859][18][debug][http] [external/envoy/source/common/http/async_client_impl.cc:104] async http request response headers (end_stream=false):
gateway-proxy-8486f5bf59-mk96q gateway-proxy ':status', '400'
gateway-proxy-8486f5bf59-mk96q gateway-proxy 'x-amzn-requestid', '005d4940-3cfb-4661-9f31-62f2a7ff3637'
gateway-proxy-8486f5bf59-mk96q gateway-proxy 'content-type', 'text/xml'
gateway-proxy-8486f5bf59-mk96q gateway-proxy 'content-length', '346'
gateway-proxy-8486f5bf59-mk96q gateway-proxy 'date', 'Fri, 27 Aug 2021 14:58:02 GMT'
gateway-proxy-8486f5bf59-mk96q gateway-proxy 'connection', 'close'
gateway-proxy-8486f5bf59-mk96q gateway-proxy 'x-envoy-upstream-service-time', '192'
gateway-proxy-8486f5bf59-mk96q gateway-proxy
gateway-proxy-8486f5bf59-mk96q gateway-proxy [2021-08-27 14:58:02.859][18][debug][client] [external/envoy/source/common/http/codec_client.cc:130] [C371] response complete
gateway-proxy-8486f5bf59-mk96q gateway-proxy [2021-08-27 14:58:02.859][18][debug][aws] [external/envoy_gloo/source/extensions/filters/http/aws_lambda/sts_fetcher.cc:107] onSuccess: StatusCode: 400, Body:
gateway-proxy-8486f5bf59-mk96q gateway-proxy  <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
gateway-proxy-8486f5bf59-mk96q gateway-proxy   <Error>
gateway-proxy-8486f5bf59-mk96q gateway-proxy     <Type>Sender</Type>
gateway-proxy-8486f5bf59-mk96q gateway-proxy     <Code>ExpiredTokenException</Code>
gateway-proxy-8486f5bf59-mk96q gateway-proxy     <Message>Token expired: current date/time 1630075982 must be before the expiration date/time1630041736</Message>
gateway-proxy-8486f5bf59-mk96q gateway-proxy   </Error>
gateway-proxy-8486f5bf59-mk96q gateway-proxy   <RequestId>005d4940-3cfb-4661-9f31-62f2a7ff3637</RequestId>
gateway-proxy-8486f5bf59-mk96q gateway-proxy </ErrorResponse>
gateway-proxy-8486f5bf59-mk96q gateway-proxy
gateway-proxy-8486f5bf59-mk96q gateway-proxy [2021-08-27 14:58:02.859][18][debug][http] [external/envoy/source/common/http/filter_manager.cc:883] [C366][S13367004294225297292] Sending local reply with details aws_lambda_credentials_not_found
gateway-proxy-8486f5bf59-mk96q gateway-proxy [2021-08-27 14:58:02.859][18][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1470] [C366][S13367004294225297292] encoding headers via codec (end_stream=false):
gateway-proxy-8486f5bf59-mk96q gateway-proxy ':status', '500'
gateway-proxy-8486f5bf59-mk96q gateway-proxy 'content-length', '39'
gateway-proxy-8486f5bf59-mk96q gateway-proxy 'content-type', 'text/plain'
gateway-proxy-8486f5bf59-mk96q gateway-proxy 'date', 'Fri, 27 Aug 2021 14:58:02 GMT'
gateway-proxy-8486f5bf59-mk96q gateway-proxy 'server', 'envoy'
```
5. Delete the gateway-proxy pod to allow a new pod to be created
6. Make the request again and observe that it works

**Expected behavior**
When using IAM for service accounts, code should either use the default credential chain provider, or if using the webidentitytokenprovider manually, it must be done in a fashion that accounts for token expiry.  I have not looked at the code, but I suspect it may also be related to how gloo caches credentials for lambda invocations.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.8.2
- Kubernetes version 1.21
- Using IAM for service accounts, not static AWS credentials

**Comment by lilley2412** [comment] 2021-08-31 13:19
I did test a gateway-proxy pod that was running for more than 1 hour; after 1 hour the request still worked.  Several hours later it failed, so I suspect it's a token caching issue and not related to how the credential chain is invoked.

**Comment by nrjpoddar** [comment] 2021-10-04 15:32
Reach out to @yuval-k or @EItanya for help as needed when you start working on this issue.

**Comment by nfuden** [comment] 2021-11-22 16:58
@lilley2412  sorry for the slow comments here but due to having an extremely hard time reproducing this I would like to ask for a few more details on the setup you have going so that I can try to reproduce it there.

Namely are you using the eks mutating webhook to make sure that aws is updating the credentials?
Also confirming that this is gloo enterprise (pretty sure given version but just making sure)

**Comment by nfuden** [comment] 2021-11-24 16:45
Locally I have finally managed to reproduce the issue and found a setting that should fix this.

Basically it comes down to how EKS in aws handles providing these credentials.

Can you please try the following:
Anywhere you had added the eks.amazonaws.com/role-arn extra annotation please also add the annotation
`eks.amazonaws.com/token-expiration: 3590`

alternatively you can add the annotations via kubectl. 
For example 
`kubectl annotate \                                                                                            
  sa gateway-proxy  \                                                                                                                               
    "eks.amazonaws.com/token-expiration=3590"`
  You would then also have to cycle the pod for the change to be picked up correctly.
  
  You should then check that 
   ` kubectl get pods --namespace=gloo-system --selector=gloo=gateway-proxy  -ojson| jq -r '.items[].spec.volumes[] | select(.name=="aws-iam-token")'`
Returns an object with  "expirationSeconds": 3600

This should set the refresh to the minimum time (1 hour) and is more likely to work with standard service account session time. 

If that works as expected awesome and I will update our documents accordingly.

**Comment by ZF-fredericvanlinthoudt** [comment] 2021-11-29 10:23
@nfuden We're also facing the same issue so I've tested your workaround, but it doesn't seem to work.
After 1 hour, we receive the following message when executing a web request to a route that has a Lambda upstream:
`no credentials present for AWS upstream`

I can confirm that the `expirationSeconds` object is now set to 3600:
```json
{
  "name": "aws-iam-token",
  "projected": {
    "defaultMode": 420,
    "sources": [
      {
        "serviceAccountToken": {
          "audience": "sts.amazonaws.com",
          "expirationSeconds": 3600,
          "path": "token"
        }
      }
    ]
  }
}
```

I've also exec'ed into a gateway-proxy pod and checked the `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` file which contains the actual secret, and decoded the token to check its validity.
Time of testing: `Mon, 29 Nov 2021 10:13:29 GMT`
![image](https://user-images.githubusercontent.com/74649673/143849578-e9e2c18b-97c0-4a5f-8855-61c2bac5de08.png)
Token validity / expiration time inside pod: `Mon, 29 Nov 2021 10:37:03 GMT`
![image](https://user-images.githubusercontent.com/74649673/143848947-4e2ffe12-7d09-446a-b059-e14f77c26bca.png)

The token should be valid at that time, so it looks like when the token has been refreshed (and thus the content of the mounted token file has been replace), gateway-proxy is not picking up the new token.

I hope this gives you some more insights into the issue.
If you need some additional information, please let me know.

**Comment by nfuden** [comment] 2021-11-30 16:34
@ZF-fredericvanlinthoudt  can you detail a bit of extra context for me? Asking as the annotation seems to have solved the issue in some other environments. 
Namely could you give me your eks verision, and gloo edge version?

**Comment by ZF-fredericvanlinthoudt** [comment] 2021-12-01 09:53
@nfuden 

Below the version info:

| Component             | Version                     |
| --------------------- | ---------------------- |
| AWS EKS                  | v1.20                        |
| AWS EKS node AMI | v1.20.4-eks-6b7464 |
| Gloo Edge               | v1.9.3                       |

**Comment by nfuden** [comment] 2021-12-07 18:01
@ZF-fredericvanlinthoudt can you turn debug logging on for envoy and see if you are seeing that sts is configured?

Something like the logs shown at the top where we see the debug response from aws

**Comment by lilley2412** [comment] 2021-12-09 20:08
@nfuden I tried your suggestion, it doesn't solve the problem - it just results in the problem occurring faster because the token lifetime is shortened.

To answer your prior questions - we're running gloo edge enterprise on EKS 1.21.  We're using the out of the box [iam for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), which in turn uses the mutating webhook you referenced that injects the token volume.  That part is all working correctly.

Here are the steps I used to test your suggestion:
* re-deploy proxy pod with the new annotation
* confirm the token has the new, shorter lifetime
* test my lambda upstream; the response was successful
* wait 1.5 hours
* test the request again, this time I get `no credentials present for AWS upstream`

**Comment by nfuden** [comment] 2021-12-21 15:52
Our newest release will have a catchall featureto ensure credentials dont go stale. Namely this is the new duration option credential_refresh_delay on the aws_lambda filter. This will set a default internal refresher in addition to the default file event watcher to avoid stale credential flakes.

**Comment by lgadban** [comment] 2022-02-08 17:37
related: https://github.com/solo-io/gloo/pull/5851

**Comment by nfuden** [comment] 2022-02-08 17:45
Looks like the auto closing did not work from the changelog. (Changelog should have specified this we added the option mentioned above in 1.10.0) https://github.com/solo-io/gloo/pull/5732 for OSS

**Comment by lilley2412** [comment] 2022-02-11 15:48
@nfuden @lgadban I just re-tested with 1.10.4, I still see the same problem following my steps above (see it work, wait a couple hours, test again and see the credential problem).

**Comment by nfuden** [comment] 2022-02-11 15:49
Any you set the credential_refresh_delay?

**Comment by lilley2412** [comment] 2022-02-11 16:00
@nfuden the token refresh setting is just going to change how long before the token is refreshed, I really think it's a red herring wrt to this problem.

I just exec'd into the gateway-proxy pod and examined the token, it's expiration time is in the future:
![image](https://user-images.githubusercontent.com/450777/153624829-b424fb53-c8ea-442e-80fc-d95f19b462fa.png)

Then did a curl that hits that same pod

```
curl -i  https://*****/demo
HTTP/1.1 500 Internal Server Error
content-length: 39
content-type: text/plain
date: Fri, 11 Feb 2022 15:58:51 GMT
server: envoy

no credentials present for AWS upstream
```

**Comment by lilley2412** [comment] 2022-02-21 21:03
I have confirmed that upgrading to 1.10.6 and using these new settings fixed this problem:

```yaml
gloo:
  settings:
    aws:
      enableServiceAccountCredentials: true
      credential_refresh_delay: "1800s"
      ```

**Closed** 2022-02-21 22:46 UTC
Labels: Type: Bug, Size: L, Priority: Blocker, Size: Undersized
