### ISSUE TITLE
Helm Chart: Invalid YAML document separation in `gloo-custom-resource-config` when configuring multiple gatewayProxies

### ISSUE THREAD

**Issue by jrauschenbusch** [solo-io/gloo#8475] opened 2023-07-18 08:24 UTC
### Gloo Edge Version

1.14.x (latest stable)

### Kubernetes Version

1.25.x

### Describe the bug

When one is configuring multiple gateway proxies in the values.yaml of the Helm Chart then it seems that the document separation is not rendered correctly (at least with Flux HelmController).

Content of gloo-custom-resource-config:

```yaml
apiVersion: v1
data:
  custom-resources: |
    ---
    apiVersion: gateway.solo.io/v1
    kind: Gateway
    metadata:
      name: gateway-proxy
      namespace: gloo
      labels:
        app: gloo
    spec:
      bindAddress: "::"
      bindPort: 8080
      httpGateway:
        options:
          healthCheck:
            path: /healthz
      useProxyProto: false
      ssl: false
      proxyNames:
      - gateway-proxy---
    apiVersion: gateway.solo.io/v1
    kind: Gateway
    metadata:
      name: gateway-proxy-test
      namespace: gloo
      labels:
        app: gloo
    spec:
      bindAddress: "::"
      bindPort: 8080
      httpGateway:
        options:
          healthCheck:
            path: /healthz
      useProxyProto: false
      ssl: false
      proxyNames:
      - gateway-proxy-external
  has-custom-resources: "true"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: gloo
    meta.helm.sh/release-namespace: gloo
  creationTimestamp: "XXX"
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
    gloo: custom-resources
    helm.toolkit.fluxcd.io/name: gloo
    helm.toolkit.fluxcd.io/namespace: gloo
  name: gloo-custom-resource-config
  namespace: gloo
  resourceVersion: "XXX"
  uid: XXX
```

One can see that the document delimiter is not rendered correctly in the ConfigMap.
```yaml
...
proxyNames:
      - gateway-proxy---
...
```

There was already an issue regarding SSL Gateways: https://github.com/solo-io/gloo/issues/8404

I think the solution for this bug will to replace the following line `{{- "---" }}` with `---`.
https://github.com/solo-io/gloo/blob/2fe0de3841c99a0b6a6cf6793e1f07ad24935518/install/helm/gloo/templates/_8-default-gateways.tpl#L157

### Steps to reproduce the bug

Apply the following HelmRelease in Cluster with Flux installed using the Helm Chart from https://storage.googleapis.com/solo-public-helm in version 1.14.12.

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gloo
spec:
  chart:
    spec:
      chart: gloo
      sourceRef:
        kind: HelmRepository
        name: gloo
        namespace: gloo
  values:
    gateway:
      enabled: true # Default, but to make it more expressive
      rolloutJob:
        enabled: true  # Default, but to make it more expressive
    gatewayProxies:
      gatewayProxy:
        gatewaySettings:
          enabled: true  # Default, but to make it more expressive
          disableHttpsGateway: true
          customHttpGateway:
            options:
              healthCheck:
                path: /healthz
        podDisruptionBudget:
          maxUnavailable: 1
        podTemplate:
          terminationGracePeriodSeconds: 12
          gracefulShutdown:
            enabled: true
            sleepTimeSeconds: 10
          probes: true
          customReadinessProbe:
            httpGet:
              scheme: HTTP
              port: 8080
              path: /healthz
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
      gatewayProxyTest:
        gatewaySettings:
          enabled: true
          disableHttpsGateway: true
          customHttpGateway:
            options:
              healthCheck:
                path: /healthz
        podTemplate:
          terminationGracePeriodSeconds: 7
          gracefulShutdown:
            enabled: true
            sleepTimeSeconds: 5
          probes: true
          customReadinessProbe:
            httpGet:
              scheme: HTTP
              port: 8080
              path: /healthz
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
```

### Expected Behavior

ConfigMap data of [gloo-custom-resource-config](https://github.com/solo-io/gloo/blob/2fe0de3841c99a0b6a6cf6793e1f07ad24935518/install/helm/gloo/templates/5-resource-configmap.yaml) should be rendered correctly so that all defined resources like Gateways will be applied by [resource-rollout job](https://github.com/solo-io/gloo/blob/2fe0de3841c99a0b6a6cf6793e1f07ad24935518/install/helm/gloo/templates/5-resource-rollout-job.yaml).

**Comment by jenshu** [comment] 2023-07-21 05:09
closing as duplicate of #8404 since they both have the same fix

**Closed by jenshu** 2023-07-21 05:09 UTC
Labels: Type: Bug
