### ISSUE TITLE
Add allowedUpstreamHeaders response option with overwrite semantics

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#6205] opened 2022-03-31 17:54 UTC
### Version

1.11.x (beta)

### Is your feature request related to a problem? Please describe.

HTTP Passthrough offers a [response option](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#response-1) called `allowedUpstreamHeaders` that supports append semantics. A customer uses this option but needs overwrite semantics, similar to this `allowedUpstreamHeaders` option for HttpService.Response [here](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#response). HttpService offers two similar header options, one with append semantics and the other with overwrite semantics.

### Describe the solution you'd like

Add an option `allowedUpstreamHeadersWithOverwrite` to the PassThroughHttp.Response described [here](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#response-1), with overwrite semantics.

### Describe alternatives you've considered

The user maintains a complex set of transformations to emulate the overwrite semantics.

### Additional Context

Internal Slack thread: https://solo-io.slack.com/archives/G0133U4GUP5/p1648564866608879

**Comment by sam-heilbron** [comment] 2023-08-02 18:24
This issue is very similar to (or an exact duplicate of) https://github.com/solo-io/gloo/issues/8477. We are closing this issue and will track the development of this fix in the linked issue

**Closed by sam-heilbron** 2023-08-02 18:24 UTC
Labels: Type: Enhancement, Area: API, Area: extauth
