### ISSUE TITLE
Adding new gateway proxy requires explicit naming of image

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1696] opened 2019-11-13 21:15 UTC
It seems that I must explicitly name the Docker image if I instantiate a non-default gateway proxy via helm:

```
  gatewayProxies: {
    internalGatewayProxyV2: {
      podTemplate: {
        image: {
          repository: "gloo-envoy-wrapper",
          registry: "quay.io/solo-io",
          tag: "0.20.8",
        },
...
```

The issue, of course, is the tag that I need to manually update.  

This is handled nicely for the default gateway proxy because the image tags are inserted.  However, for non-default gateway proxies, this is not the case.  

Could we find a way to inherit the value from the default gateway proxy configuration if it is not present?

**Comment by kdorosh** [comment] 2019-11-13 21:20
Appears to be a duplicate of https://github.com/solo-io/gloo/issues/1571

**Comment by kdorosh** [comment] 2019-11-13 21:21
closing as duplicate

**Closed by kdorosh** 2019-11-13 21:21 UTC
