### ISSUE TITLE
glooctl install displays warnings

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#3533] opened 2020-08-20 12:59 UTC
**Describe the bug**

```
glooctl install gateway enterprise --license-key $GLOO_LICENSE_KEY --version 1.5.0-beta8
Creating namespace gloo-system... Done.
Starting Gloo Enterprise installation...
2020/08/20 08:56:18 warning: cannot overwrite table with non table for rateLimit (map[])
2020/08/20 08:56:18 warning: cannot overwrite table with non table for rateLimit (map[])
2020/08/20 08:56:18 warning: cannot overwrite table with non table for rateLimit (map[])
2020/08/20 08:56:18 warning: cannot overwrite table with non table for rateLimit (map[])
2020/08/20 08:56:18 warning: cannot overwrite table with non table for rateLimit (map[])
2020/08/20 08:56:18 warning: cannot overwrite table with non table for rateLimit (map[])

Gloo Enterprise was successfully installed!
```

**Expected behavior**

**Additional context**
`glooctl version` output:
```
Client: {"version":"1.5.0-beta19"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.5.0-beta8","Name":"grpcserver-ui","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta8","Name":"grpcserver-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta8","Name":"grpcserver-envoy","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta19","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta8","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta19","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta8","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta8","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta8","Name":"observability-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.0-beta8","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```

**Comment by kdorosh** [comment] 2020-08-20 13:23
closing as duplicate of https://github.com/solo-io/gloo/issues/3467

**Closed by kdorosh** 2020-08-20 13:23 UTC
Labels: Type: Bug
