### ISSUE TITLE
Proxy Operator: manage the service (and deployment) of Gloo Gateway proxies

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2295] opened 2020-01-28 18:33 UTC
the high number of fields that must line up between the  kube svc and the proxy CRD for an instance of Envoy makes user workflows for configuring routing to their proxies difficult, e.g. in situations when configuring an external load balancer to the proxy requires setting health checks to the right listener

gloo (or a gloo operator) should assume control of this behavior; i.e. that the helm chart is no longer responsible for creating `*-proxy` services, but that is left to a controller in Gloo itself.

the same could be (but is not necessarily) applied to proxy Deployment/DaemonSets as well

**Comment by rickducott** [comment] 2020-03-25 21:30
This is a duplicate of #1785, closing in favor of that one.

**Closed by rickducott** 2020-03-25 21:30 UTC
Labels: Area: Usability, Type: Enhancement
