### ISSUE TITLE
Expose max_buffered_{rx/tx}_bytes in the Tap filter

### ISSUE THREAD

**Issue by sadieleob** [solo-io/gloo#9656] opened 2024-06-20 22:40 UTC
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.17

### Is your feature request related to a problem? Please describe.

This is not related to an issue. 

### Describe the solution you'd like

The customer is asking to expose:

- **max_buffered_rx_bytes**
- **max_buffered_tx_bytes** 
- **record_headers_received_time**
- **record_downstream_connection**

The customer stated that without the max_buffered_<rx/tx>_bytes fields set, the maximum body size is 1KiB  that can be sent to the tap filter. Unfortunately, this max body size blocks our integration of the tap filter with their "in-house monetization" project since it requires payloads up to 4KB.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/tap/v3/common.proto#config-tap-v3-outputconfig
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/tap/v3/tap.proto#extensions-filters-http-tap-v3-tap

### Describe alternatives you've considered

There are no alternatives

# Related Issues

- https://github.com/solo-io/solo-projects/issues/5455
- https://github.com/solo-io/gloo/issues/9845

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1208137702093564) by [Unito](https://www.unito.io)

**Comment by nfuden** [comment] 2024-06-21 13:47
https://github.com/solo-io/solo-projects/issues/5455 encompasses this as well. @DuncanDoyle

**Comment by DuncanDoyle** [comment] 2024-08-01 17:20
@nfuden As discussed, removing the "Streaming support" from this requirement an putting this in a separate issue: https://github.com/solo-io/gloo/issues/9845

**Comment by ashishb-solo** [comment] 2024-09-12 21:03
The changes in gloo only expose the protobuf changes, but the translation logic lives in solo-projects and that has not yet merged. Reopening.

**Comment by nfuden** [comment] 2024-09-13 14:18
This also requires a backport to 1.17 and notes on the enterprise releases that it will be released in

**Comment by ashishb-solo** [comment] 2024-09-13 14:45
This is a duplicate of https://github.com/solo-io/solo-projects/issues/5455

**Comment by DuncanDoyle** [comment] 2024-09-19 09:30
Released in Gloo Gateway Enterprise 1.17.2

**Closed by DuncanDoyle** 2024-09-19 09:30 UTC
Labels: Type: Enhancement, zendesk, release/1.17, Prioritized, post-plan/1.18
