### ISSUE TITLE
support upstream validation in webhook

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3654] opened 2020-09-22 19:19 UTC
**Is your feature request related to a problem? Please describe.**
Id like the upstreams to also be validated in the webhook

**Describe the solution you'd like**
support upstream validation in webhook

**Comment by lgadban** [comment] 2020-09-28 15:48
related: https://github.com/solo-io/gloo/issues/2797

**Comment by chrisgaun** [comment] 2021-01-08 20:50
This is a duplicate of https://github.com/solo-io/gloo/issues/2797

**Closed** 2021-01-08 20:51 UTC
Labels: Type: Enhancement
