### ISSUE TITLE
Make number of replicas for rate limit and redis configurable

### ISSUE THREAD

**Issue by snuggie12** [solo-io/gloo#2468] opened 2020-02-19 18:42 UTC
I believe both of these are in the enterprise repo so I can not submit a PR.

I don't know whether this should be one value that applies to both or separate values.

**Comment by kdorosh** [comment] 2020-04-23 20:01
closing as duplicate of https://github.com/solo-io/gloo/issues/2638

**Closed by kdorosh** 2020-04-23 20:01 UTC
Labels: Area: Helm, Enterprise, Impact: S, Type: Enhancement
