### ISSUE TITLE
Update proxy controller guide to use solo-apis

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#5093] opened 2021-07-30 14:19 UTC
**Describe the requested changes**
The proxy controller dev guide is out of date and does not use solo-apis repo

**Link to any relevant existing docs**
https://docs.solo.io/gloo-edge/latest/guides/dev/example-proxy-controller/

**Comment by sam-heilbron** [comment] 2022-01-10 15:06
Duplicate of https://github.com/solo-io/gloo/issues/4190

**Closed by sam-heilbron** 2022-01-10 15:06 UTC
Labels: Type: Docs, Impact: L
