### ISSUE TITLE
Virtual service selector is too restrictive

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1695] opened 2019-11-13 20:39 UTC
I run one gloo gateway for "internal" traffic, i.e. pod to pod. This gateway services multiple virtual services in different namespaces. I pull off this trick by using an `ExternalName` service to map per namespace DNS names to the single gateway proxy.

I would like to select the virtual services using the virtual service selector.  Unfortunately, there is a restriction that disallows me to pull virtual services from different namespaces using the virtual service selector.

My choices are to create separate Gateways objects pointing the same gateway proxy OR to name the virtual services explicitly.  The latter requires the shared gateway to know all the names of the virtual services.  I would like to avoid that.

If I provide separate Gateway objects, one per namespace but all sharing the SAME port and having otherwise identical configurations, will they be merged into a single Proxy object.  Or, will this cause a conflict.

If they cause a conflict, can you fix the code or allow the selector to select virtual services across multiple namespaces?

**Comment by derrickburns** [comment] 2019-11-13 20:39
@ilackarms Thoughts?

**Comment by kdorosh** [comment] 2019-11-13 20:49
Related to, but not a duplicate of https://github.com/solo-io/gloo/issues/1489, which was implemented in https://github.com/solo-io/gloo/pull/1678 (which will go out in our 1.0 release).

Should be a quick fix to add this to our 1.0 release.

Related code: https://github.com/solo-io/gloo/blob/feature-rc1/projects/gateway/pkg/translator/http.go#L175

@GrahamGoudeau

**Comment by derrickburns** [comment] 2019-11-13 21:00
@kdorosh Thx!

**Comment by derrickburns** [comment] 2019-11-21 06:17
@kdorosh I *REALLY* need this fixed ASAP.  It causes me no end of trouble 

Here is why.  

If I list create a gateway listing virtual services BEFORE they exist ... trouble.

If I create a service with Gloo virtual services BEFORE gloo in installed... trouble.

If I install Gloo without my gateways, Gloo wants to install default ones ... trouble.

The dance is painful.

**Comment by kdorosh** [comment] 2019-11-25 03:04
@derrickburns opened https://github.com/solo-io/gloo/pull/1763 to address

**Comment by derrickburns** [comment] 2019-11-25 03:53
@kdorosh  Yayyy.  Thanks. You are awesome!

**Closed** 2019-12-02 14:28 UTC
