### ISSUE TITLE
1.4 custom/2nd dataplane envoy bootstrap configmap contains explicit \n

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3235] opened 2020-06-26 22:14 UTC
**Describe the bug**
Using the same helm overrides (attached)

**1.3**
```
$ kubectl -n gloo-system get configmap custom-proxy-envoy-config -o yaml
apiVersion: v1
data:
  envoy.yaml: |
    node:
      cluster: gateway
      id: "{{.PodName}}.{{.PodNamespace}}"
      metadata:
        # role's value is the key for the in-memory xds cache (projects/gloo/pkg/xds/envoy.go)
        role: "{{.PodNamespace}}~gateway-proxy-bdp"
    stats_sinks:
      - name: envoy.metrics_service
        config:
          grpc_service:
            envoy_grpc: {cluster_name: gloo.gloo-system.svc.cluster.local:9966}
    static_resources:
      listeners: # if or $statsConfig.enabled (or $spec.readConfig $spec.extraListenersHelper) # $spec.extraListenersHelper
        - name: prometheus_listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8081
          filter_chains:
            - filters:
                - name: envoy.http_connection_manager
                  config:
                    codec_type: auto
                    stat_prefix: prometheus
                    route_config:
                      name: prometheus_route
                      virtual_hosts:
                        - name: prometheus_host
                          domains:
                            - "*"
                          routes:
                            - match:
                                path: "/ready"
                                headers:
                                - name: ":method"
                                  exact_match: GET
                              route:
                                cluster: admin_port_cluster
                            - match:
                                prefix: "/metrics"
                                headers:
                                - name: ":method"
                                  exact_match: GET
                              route:
                                prefix_rewrite: "/stats/prometheus"
                                cluster: admin_port_cluster
                    http_filters:
                      - name: envoy.router
                        config: {} # if $statsConfig.enabled
        - name: read_config_listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8082
          filter_chains:
            - filters:
                - name: envoy.http_connection_manager
                  config:
                    codec_type: auto
                    stat_prefix: read_config
                    route_config:
                      name: read_config_route
                      virtual_hosts:
                        - name: read_config_host
                          domains:
                            - "*"
                          routes:
                            - match:
                                path: "/ready"
                                headers:
                                  - name: ":method"
                                    exact_match: GET
                              route:
                                cluster: admin_port_cluster
                            - match:
                                prefix: "/stats"
                                headers:
                                  - name: ":method"
                                    exact_match: GET
                              route:
                                cluster: admin_port_cluster
                            - match:
                                 prefix: "/config_dump"
                                 headers:
                                   - name: ":method"
                                     exact_match: GET
                              route:
                                cluster: admin_port_cluster
                    http_filters:
                      - name: envoy.router
                        config: {} # if $spec.readConfig
      clusters:
      - name: gloo.gloo-system.svc.cluster.local:9977
        alt_stat_name: xds_cluster
        connect_timeout: 5.000s
        load_assignment:
          cluster_name: gloo.gloo-system.svc.cluster.local:9977
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: gloo.gloo-system.svc.cluster.local
                    port_value: 9977
        http2_protocol_options: {}
        upstream_connection_options:
          tcp_keepalive: {}
        type: STRICT_DNS
        respect_dns_ttl: true
      - name: wasm-cache
        connect_timeout: 5.000s
        load_assignment:
          cluster_name: wasm-cache
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: gloo.gloo-system.svc.cluster.local
                    port_value: 9979
        upstream_connection_options:
          tcp_keepalive: {}
        type: STRICT_DNS
        respect_dns_ttl: true
      - name: gloo.gloo-system.svc.cluster.local:9966
        alt_stat_name: metrics_cluster
        connect_timeout: 5.000s
        load_assignment:
            cluster_name: gloo.gloo-system.svc.cluster.local:9966
            endpoints:
            - lb_endpoints:
              - endpoint:
                    address:
                        socket_address:
                            address: gloo.gloo-system.svc.cluster.local
                            port_value: 9966
        http2_protocol_options: {}
        type: STRICT_DNS # if .Values.accessLogger.enabled # if $spec.tracing
      - name: admin_port_cluster
        connect_timeout: 5.000s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: admin_port_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 19000 # if or $statsConfig.enabled ($spec.readConfig) # if $spec.tracing
    dynamic_resources:
      ads_config:
        api_type: GRPC
        rate_limit_settings: {}
        grpc_services:
        - envoy_grpc: {cluster_name: gloo.gloo-system.svc.cluster.local:9977}
      cds_config:
        ads: {}
      lds_config:
        ads: {}
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 19000 # if (empty $spec.configMap.data) ## allows full custom # range $name, $spec := .Values.gatewayProxies# if .Values.gateway.enabled
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: glooe
    meta.helm.sh/release-namespace: gloo-system
  creationTimestamp: "2020-06-26T19:35:29Z"
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
    gateway-proxy-id: gateway-proxy-bdp
    gloo: gateway-proxy
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:envoy.yaml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:gateway-proxy-id: {}
          f:gloo: {}
    manager: Go-http-client
    operation: Update
    time: "2020-06-26T19:35:29Z"
  name: gateway-proxy-bdp-envoy-config
  namespace: gloo-system
  resourceVersion: "1748"
  selfLink: /api/v1/namespaces/gloo-system/configmaps/gateway-proxy-bdp-envoy-config
  uid: a69ebfcb-9221-490a-8fe3-cf93bfc3ec60
```

**1.4**
```
$ kubectl -n gloo-system get configmap custom-proxy-envoy-config -o yaml
apiVersion: v1
data:
  envoy.yaml: "node:\n  cluster: gateway\n  id: \"{{.PodName}}.{{.PodNamespace}}\"\n
    \ metadata:\n    # role's value is the key for the in-memory xds cache (projects/gloo/pkg/xds/envoy.go)\n
    \   role: \"{{.PodNamespace}}~gateway-proxy-bdp\"\nstats_sinks:\n  - name: envoy.metrics_service\n
    \   config:\n      grpc_service:\n        envoy_grpc: {cluster_name: gloo.gloo-system.svc.cluster.local:9966}\nstatic_resources:\n
    \ listeners: # if or $statsConfig.enabled (or $spec.readConfig $spec.extraListenersHelper)
    # $spec.extraListenersHelper\n    - name: prometheus_listener\n      address:\n
    \       socket_address:\n          address: 0.0.0.0\n          port_value: 8081\n
    \     filter_chains:\n        - filters:\n            - name: envoy.http_connection_manager\n
    \             config:\n                codec_type: auto\n                stat_prefix:
    prometheus\n                route_config:\n                  name: prometheus_route\n
    \                 virtual_hosts:\n                    - name: prometheus_host\n
    \                     domains:\n                        - \"*\"\n                      routes:\n
    \                       - match:\n                            path: \"/ready\"\n
    \                           headers:\n                            - name: \":method\"\n
    \                             exact_match: GET\n                          route:\n
    \                           cluster: admin_port_cluster\n                        -
    match:\n                            prefix: \"/metrics\"\n                            headers:\n
    \                           - name: \":method\"\n                              exact_match:
    GET\n                          route:\n                            prefix_rewrite:
    \"/stats/prometheus\"\n                            cluster: admin_port_cluster\n
    \               http_filters:\n                  - name: envoy.router\n                    config:
    {} # if $statsConfig.enabled\n    - name: read_config_listener\n      address:\n
    \       socket_address:\n          address: 0.0.0.0\n          port_value: 8082\n
    \     filter_chains:\n        - filters:\n            - name: envoy.http_connection_manager\n
    \             config:\n                codec_type: auto\n                stat_prefix:
    read_config\n                route_config:\n                  name: read_config_route\n
    \                 virtual_hosts:\n                    - name: read_config_host\n
    \                     domains:\n                        - \"*\"\n                      routes:\n
    \                       - match:\n                            path: \"/ready\"\n
    \                           headers:\n                              - name: \":method\"\n
    \                               exact_match: GET\n                          route:\n
    \                           cluster: admin_port_cluster\n                        -
    match:\n                            prefix: \"/stats\"\n                            headers:\n
    \                             - name: \":method\"\n                                exact_match:
    GET\n                          route:\n                            cluster: admin_port_cluster\n
    \                       - match:\n                             prefix: \"/config_dump\"\n
    \                            headers:\n                               - name:
    \":method\"\n                                 exact_match: GET\n                          route:\n
    \                           cluster: admin_port_cluster\n                http_filters:\n
    \                 - name: envoy.router\n                    config: {} # if $spec.readConfig\n
    \ clusters:\n  - name: gloo.gloo-system.svc.cluster.local:9977\n    alt_stat_name:
    xds_cluster\n    connect_timeout: 5.000s\n    load_assignment:\n      cluster_name:
    gloo.gloo-system.svc.cluster.local:9977\n      endpoints:\n      - lb_endpoints:\n
    \       - endpoint:\n            address:\n              socket_address:\n                address:
    gloo.gloo-system.svc.cluster.local\n                port_value: 9977\n    http2_protocol_options:
    {}\n    upstream_connection_options:\n      tcp_keepalive: {}\n    type: STRICT_DNS\n
    \   respect_dns_ttl: true\n  - name: wasm-cache\n    connect_timeout: 5.000s\n
    \   load_assignment:\n      cluster_name: wasm-cache\n      endpoints:\n      -
    lb_endpoints:\n        - endpoint:\n            address:\n              socket_address:\n
    \               address: gloo.gloo-system.svc.cluster.local\n                port_value:
    9979\n    upstream_connection_options:\n      tcp_keepalive: {}\n    type: STRICT_DNS\n
    \   respect_dns_ttl: true\n  - name: gloo.gloo-system.svc.cluster.local:9966\n
    \   alt_stat_name: metrics_cluster\n    connect_timeout: 5.000s\n    load_assignment:\n
    \       cluster_name: gloo.gloo-system.svc.cluster.local:9966\n        endpoints:\n
    \       - lb_endpoints:\n          - endpoint:\n                address:\n                    socket_address:\n
    \                       address: gloo.gloo-system.svc.cluster.local\n                        port_value:
    9966\n    http2_protocol_options: {}\n    type: STRICT_DNS # if .Values.accessLogger.enabled
    # if $spec.tracing\n  - name: admin_port_cluster\n    connect_timeout: 5.000s\n
    \   type: STATIC\n    lb_policy: ROUND_ROBIN\n    load_assignment:\n      cluster_name:
    admin_port_cluster\n      endpoints:\n      - lb_endpoints:\n        - endpoint:\n
    \           address:\n              socket_address:\n                address:
    \n                port_value: 19000 # if or $statsConfig.enabled ($spec.readConfig)
    # if $spec.tracing\ndynamic_resources:\n  ads_config:\n    api_type: GRPC\n    rate_limit_settings:
    {}\n    grpc_services:\n    - envoy_grpc: {cluster_name: gloo.gloo-system.svc.cluster.local:9977}\n
    \ cds_config:\n    ads: {}\n  lds_config:\n    ads: {}\nadmin:\n  access_log_path:
    /dev/null\n  address:\n    socket_address:\n      address: \n      port_value:
    19000 # if (empty $spec.configMap.data) ## allows full custom # range $name, $spec
    := .Values.gatewayProxies# if .Values.gateway.enabled\n"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: glooe
    meta.helm.sh/release-namespace: gloo-system
  creationTimestamp: "2020-06-26T19:40:55Z"
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
    gateway-proxy-id: gateway-proxy-bdp
    gloo: gateway-proxy
  name: gateway-proxy-bdp-envoy-config
  namespace: gloo-system
  resourceVersion: "10342"
  selfLink: /api/v1/namespaces/gloo-system/configmaps/gateway-proxy-bdp-envoy-config
  uid: f38a0b34-b7e4-11ea-bd25-42010aa80fd7
```

Resulting in envoy failing with:
```
[2020-06-26 19:11:07.401][6][info][main] [external/envoy/source/server/server.cc:674] exiting
Proto constraint validation failed (BootstrapValidationError.StaticResources: ["embedded message failed validation"] | caused by StaticResourcesValidationError.Clusters[i]: ["embedded message failed validation"] | caused by ClusterValidationError.LoadAssignment: ["embedded message failed validation"] | caused by ClusterLoadAssignmentValidationError.Endpoints[i]: ["embedded message failed validation"] | caused by LocalityLbEndpointsValidationError.LbEndpoints[i]: ["embedded message failed validation"] | caused by LbEndpointValidationError.Endpoint: ["embedded message failed validation"] | caused by EndpointValidationError.Address: ["embedded message failed validation"] | caused by AddressValidationError.SocketAddress: ["embedded message failed validation"] | caused by SocketAddressValidationError.Address: ["value length must be at least " '\x01' " bytes"]): node {
```

**To Reproduce**
1. kube apply '...'
2. curl '....'
3. See error

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo version
- Kubernetes version

**Comment by bdecoste** [comment] 2020-06-26 22:16
```
gloo:
  discovery:
    fdsMode: BLACKLIST
  gatewayProxies:
    gatewayProxy:
      readConfig: true
      gatewaySettings:
        customHttpGateway:
          virtualServices:
          - name: standard-vs
            namespace: gloo-system
        customHttpsGateway:
          virtualServices:
          - name: standard-vs
            namespace: gloo-system
      podTemplate:
        disableNetBind: false
        floatingUserId: false
        httpPort: 8080
        httpsPort: 8443
    customProxy:
      gatewaySettings:
        customHttpGateway: 
          virtualServices:
          - name: custom-vs
            namespace: gloo-system
        customHttpsGateway:
          virtualServices:
          - name: custom-vs
            namespace: gloo-system
      readConfig: true
      configMap:
        data: null
      kind:
        deployment:
          antiAffinity: false
          replicas: 1
      podTemplate:
        disableNetBind: false
        floatingUserId: false
        httpPort: 8180
        httpsPort: 8543
        image:
          repository: gloo-ee-envoy-wrapper
          tag: 1.4.0
        probes: false
        runUnprivileged: false
      service:
        httpPort: 80
        httpsPort: 1443
        type: LoadBalancer
        annotations:
          prometheus.io/path: "/metrics"
          prometheus.io/port: "8081"
          prometheus.io/scrape: "true"

```

**Comment by kdorosh** [comment] 2020-06-30 18:04
This worked in GlooE 1.4.0-beta7 (the last beta release) but stopped working in GlooE 1.4.0

**Comment by kdorosh** [comment] 2020-06-30 20:07
Adding the loopback address into the helm values fixes the issue. For example, updated helm values for open source:
```yaml
discovery:
  fdsMode: BLACKLIST
gatewayProxies:
  gatewayProxy:
    loopBackAddress: 127.0.0.1
    readConfig: true
    gatewaySettings:
      customHttpGateway:
        virtualServices:
          - name: standard-vs
            namespace: gloo-system
      customHttpsGateway:
        virtualServices:
          - name: standard-vs
            namespace: gloo-system
    podTemplate:
      disableNetBind: false
      floatingUserId: false
      httpPort: 8080
      httpsPort: 8443
  customProxy:
    loopBackAddress: 127.0.0.1
    gatewaySettings:
      customHttpGateway:
        virtualServices:
          - name: custom-vs
            namespace: gloo-system
      customHttpsGateway:
        virtualServices:
          - name: custom-vs
            namespace: gloo-system
    readConfig: true
    configMap:
      data: null
    kind:
      deployment:
        antiAffinity: false
        replicas: 1
    podTemplate:
      disableNetBind: false
      floatingUserId: false
      httpPort: 8180
      httpsPort: 8543
      image:
        repository: gloo-ee-envoy-wrapper
        tag: 1.4.0
      probes: false
      runUnprivileged: false
    service:
      httpPort: 80
      httpsPort: 1443
      type: LoadBalancer
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"

```

**Comment by kdorosh** [comment] 2020-07-01 14:01
closing as the helm value resolved the issue and the root cause/fix is the same as the one identified in https://github.com/solo-io/gloo/issues/3142

**Closed by kdorosh** 2020-07-01 14:01 UTC
Labels: Type: Bug
