### ISSUE TITLE
Provide examples for Gloo + ExternalDNS 

### ISSUE THREAD

**Issue by linecolumn** [solo-io/gloo#3083] opened 2020-05-28 21:05 UTC
**Describe the requested changes**

Provide examples for Gloo + ExternalDNS usage, covering both updating DNS entries to point to ELB/ALB and external node IP.

Documentation link is below.

**Link to any relevant existing docs**

https://docs.solo.io/gloo/latest/installation/platform_configuration/cluster_setup/#dns-records

```
Kubernetes DNS will take care of the internal DNS for the cluster, but it does not publish public DNS records for services running inside the cluster including Gloo Gateway. Using a tool like external-dns will enable you to set up DNS records for Gloo and make your services publicly accessible.
```

**Comment by kdorosh** [comment] 2020-08-26 19:54
closing as duplicate of https://github.com/solo-io/gloo/issues/2467

**Closed by kdorosh** 2020-08-26 19:54 UTC
Labels: Help Wanted, Type: Docs
