### ISSUE TITLE
Cannot install on Kubernetes with glooctl without Helm chart

### ISSUE THREAD

**Issue by mborho** [solo-io/gloo#508] opened 2019-03-07 10:49 UTC
Following the instructions on https://gloo.solo.io/installation/quick_start/#2a-install-the-gloo-gateway-to-your-kubernetes-cluster-using-glooctl gives me following result:

```sh
$ glooctl install gateway 
Error: installing gloo in gateway mode: you must provide a Gloo Helm chart URI via the 'file' option when running an unreleased version of glooctl
```

Tried it down to v0.8.5. Are the docs incomplete or what version is the last released one?

**Comment by rickducott** [comment] 2019-03-07 11:16
Sorry about that @mborho I am fixing now.

**Comment by rickducott** [comment] 2019-03-07 11:33
I have fixed v0.10.1, so if you grab the CLI off of github or run `curl -sL https://run.solo.io/gloo/install | sh` you can install via `glooctl install gateway` again -- confirmed on my local minikube.

The issue seems to be we are not setting the version (i.e. v0.10.1) when building the artifacts, so the CLI thought it was a dev version. I am looking into why that is now.

**Comment by rickducott** [comment] 2019-03-07 11:46
I confirmed the CLI was being built in the `build-test-assets` build step without the version specified, based on these logs: 
```
CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -ldflags="-X github.com/solo-io/gloo/pkg/version.Version=dev" -gcflags=all="-N -l" -o /workspace/gopath/src/github.com/solo-io/gloo/_output/glooctl-darwin-amd64 projects/gloo/cli/cmd/main.go
CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags="-X github.com/solo-io/gloo/pkg/version.Version=dev" -gcflags=all="-N -l" -o /workspace/gopath/src/github.com/solo-io/gloo/_output/glooctl-linux-amd64 projects/gloo/cli/cmd/main.go
```

I opened a PR that fixes the regression: https://github.com/solo-io/gloo/pull/509.

**Comment by rickducott** [comment] 2019-03-07 13:27
The fix is merged and I released v0.10.2, which seems to behave as expected. I went back and fixed all the releases that were affected by this regression. Thanks @mborho

**Comment by bigeasy** [comment] 2020-01-17 15:34
I'm getting this error from a fresh install (last half-hour) of `glooctl`.

**Comment by kdorosh** [comment] 2020-01-20 19:34
@bigeasy PR with fix is open here https://github.com/solo-io/gloo/pull/2237 , hoping to release soon. For now, I would recommend using Gloo 1.3.1 as 1.3.2 has been downgraded to a pre-release.

**Closed** 2020-01-20 20:25 UTC

**Comment by bigeasy** [comment] 2020-01-26 07:36
FYI. I did use 1.3.1 when I hit this issue, since the 1.3.2 release was 21 hours old or so, I figured it was a regression. Gloo installed easily. I've been very successful using it. Thank you.
