### ISSUE TITLE
Over allocation of upstream ref in gloo

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#4084] opened 2021-01-09 15:42 UTC
**Describe the bug**
Since the gogo -> golang proto change the number of allocations has gone way up, as golang proto does not support struct values, only pointers. An example of this can be found [here](https://github.com/solo-io/gloo/blob/01d04751f72c168e304977c4f67fdbcbf30232a9/projects/gloo/pkg/translator/endpoints.go#L94).

This is having a number of unintended consequences.
1. Longer sync times at high load
2. Running out of memory

**Comment by kdorosh** [comment] 2021-01-18 15:26
closing as duplicate of https://github.com/solo-io/gloo/issues/4078#issuecomment-762317934

**Closed by kdorosh** 2021-01-18 15:26 UTC
Labels: Type: Bug
