### ISSUE TITLE
Envoy::Http::Http1::ClientConnectionImpl::onBody()  Caught Segmentation fault, suspect faulting 

### ISSUE THREAD

**Issue by willise** [solo-io/gloo#1014] opened 2019-08-12 02:42 UTC
Gloo version: v0.18.15

K8s version:  v1.15.0

Reproduce Step:
1. Run`glooctl install gateway` and edit "gateway-proxy-v2" to use nodeport.
1. Use `kubectl proxy` to expose apiserver insecure port "8080".
2. Create a service with name "clustera" without selector.
3. Create a endpoint with name "clustera" whose subsets is apiserver "<masterIP>:8080" in same namespace with service "clustera".
4. Create a vitualservice directing "/clustera" to apiserver 8080 port.
5. Run `curl <gateway-proxy-v2>:<nodeport>/clustera/api/v1/watch/nodes`

Problem:
After `curl` exits with "curl: (18) transfer closed with outstanding read data remaining", pod "gateway-proxy-v2-<xxx>-<ooo>" also exits with error, like:
```
[2019-08-12 02:41:33.765][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:81] Caught Segmentation fault, suspect faulting address 0x20
[2019-08-12 02:41:33.765][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:69] Backtrace (use tools/stack_decode.py to get line numbers):
[2019-08-12 02:41:33.766][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: [0x7f4444ce94b0]
[2019-08-12 02:41:33.769][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #1: Envoy::Http::StreamDecoderWrapper::decodeData() [0xa020ec]
[2019-08-12 02:41:33.772][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #2: Envoy::Http::Http1::ClientConnectionImpl::onMessageComplete() [0xad44ae]
[2019-08-12 02:41:33.775][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #3: Envoy::Http::Http1::ConnectionImpl::onMessageCompleteBase() [0xad1f39]
[2019-08-12 02:41:33.778][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #4: Envoy::Http::Http1::ConnectionImpl::$_7::__invoke() [0xad586d]
[2019-08-12 02:41:33.781][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #5: http_parser_execute [0xc8a9a0]
[2019-08-12 02:41:33.784][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #6: Envoy::Http::Http1::ConnectionImpl::dispatchSlice() [0xad17d5]
[2019-08-12 02:41:33.787][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #7: Envoy::Http::Http1::ConnectionImpl::dispatch() [0xad15bf]
[2019-08-12 02:41:33.790][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #8: Envoy::Http::CodecClient::onData() [0xa5d3c6]
[2019-08-12 02:41:33.793][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #9: Envoy::Http::CodecClient::CodecReadFilter::onData() [0xa5de4d]
[2019-08-12 02:41:33.796][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #10: Envoy::Network::FilterManagerImpl::onRead() [0x8c0f89]
[2019-08-12 02:41:33.799][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #11: Envoy::Network::ConnectionImpl::onReadReady() [0x8bd95c]
[2019-08-12 02:41:33.802][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #12: Envoy::Network::ConnectionImpl::onFileEvent() [0x8bd421]
[2019-08-12 02:41:33.804][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #13: Envoy::Event::FileEventImpl::assignEvents()::$_0::__invoke() [0x8b82d5]
[2019-08-12 02:41:33.807][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #14: event_process_active_single_queue [0xc7bb9d]
[2019-08-12 02:41:33.811][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #15: event_base_loop [0xc7a150]
[2019-08-12 02:41:33.814][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #16: Envoy::Event::DispatcherImpl::run() [0x8b712d]
[2019-08-12 02:41:33.819][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #17: Envoy::Server::WorkerImpl::threadRoutine() [0x8b0f92]
[2019-08-12 02:41:33.824][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:73] #18: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0xe11385]
[2019-08-12 02:41:33.824][46][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #19: [0x7f4444cdecf8]
```

Expect:
Pod runs without error.

**Comment by yuval-k** [comment] 2019-08-12 20:20
Hi @willise ! thank you for this report!

I was not able to reproduce this issue based on the description you provided.
Can you please attach all the relevant yaml manifests that you used?
that would help in quickly reproducing this issue.

I resolved the crash symbol you provided , but it is hard to tell where this issue originates from the stack trace, hence the need to reproduce it.

Thanks!

**Comment by willise** [comment] 2019-08-13 07:10
@yuval-k The yaml manifest I use to install gloo is generated by command `glooctl install gateway --dry-run`.
The `curl` command described above establishes a http long connection with k8s apiserver. In fact, it requestes a "watch" api.  In my program, I gets the info as:
![image](https://user-images.githubusercontent.com/8471187/62921822-5fd8a880-bddc-11e9-9920-3bccf7d1857e.png)
Hope this helps.

**Comment by yuval-k** [comment] 2019-08-14 11:41
I'm not clear on how steps 2-4 work together? is clustera pointing the kueb api server in step 2?
If you could attach the manifests for steps 3, 4 it would help me re-create your setup

**Comment by willise** [comment] 2019-08-15 02:34
step2:
I have a k8s cluster installed, apiserver listen on secure port 6443. Assuming that IP of apiserver is "10.10.10.10". To expose apiserver to client on other machines, I use `kubectl proxy --accept-hosts=^.*$ --address=10.10.10.10 --port=8080` to expose unsecure port 8080.

step3-4:
Use
```
kind: "Service"
apiVersion: "v1"
metadata:
  name: "clustera"
spec:
  ports:
    - name: "apiserver"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "clustera"
subsets:
  - addresses:
      - ip: "10.10.10.10"
    ports:
      - port: 8080
        name: "apiserver"
```
to create a headless service.

step5:
Use
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: test
spec:
  virtualHost:
    domains:
    - '*'
    name: test.default
    routes:
    - matcher:
        prefix: /clustera/
      routeAction:
        single:
          upstream:
            name: test-clustera-8080
            namespace: gloo-system
      routePlugins:
        prefixRewrite:
          prefixRewrite: /
    - matcher:
        prefix: /clustera
      routeAction:
        single:
          upstream:
            name: test-clustera-8080
            namespace: gloo-system
      routePlugins:
        prefixRewrite:
          prefixRewrite: /
```
to create vs.

**Comment by yuval-k** [comment] 2019-08-15 16:05
thanks! i was able to reproduce this; will update when i have more info

**Comment by yuval-k** [comment] 2019-08-15 16:14
This bugs seems to be an upstream envoy bug that was since fixed. Please used latest version of gloo (we released one recently, with updated envoy for the security release), and your issue should be resolved.
Closing. please re-open if needed!

**Closed by yuval-k** 2019-08-15 16:14 UTC
Labels: Area: envoy
