### ISSUE TITLE
Expose loadBalancerSourceRanges as value in gloo helm chart

### ISSUE THREAD

**Issue by devkws** [solo-io/gloo#2813] opened 2020-04-17 12:27 UTC
Adding loadBalancerSourceRanges as a value for the helm chart would save the need to patch the load balancer after the deployment. It would also allow traffic to be pre-filtered before it hits gloo.

```
 loadBalancerSourceRanges:
  - 1.1.1.1/32
  - 2.2.2.2/20
```

**Comment by kdorosh** [comment] 2020-04-23 20:02
closing as duplicate of https://github.com/solo-io/gloo/issues/2813

**Comment by kdorosh** [comment] 2020-04-23 20:03
Another workaround is to leverage kustomize for any helm customizations you'd like to make to our chart until we have a chance to expose every setting that's requested. For more, read here: https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/helm_advanced/

**Closed by kdorosh** 2020-04-23 20:02 UTC
Labels: Area: Helm, Type: Enhancement
