### ISSUE TITLE
Allow log level to be set before startup

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2115] opened 2020-01-03 21:07 UTC
Allow log level to be set before startup.

Also make it easier to change (without the port forward & curl/UI click).

Update the `glooctl` command to allow setting the log level, rather than just forcing users onto debug when you call `glooctl proxy logs`

**Comment by rickducott** [comment] 2020-02-11 22:21
Closing as a dupe of https://github.com/solo-io/gloo/issues/945 (tracking all the logging improvements on a single issue)

**Closed by rickducott** 2020-02-11 22:21 UTC
Labels: Area: User Experience, Area: glooctl, Impact: M, Size: S, Usability
