### ISSUE TITLE
glooctl '--version' not honored when also using '--with-admin-console' flag

### ISSUE THREAD

**Issue by asaintsever** [solo-io/gloo#3403] opened 2020-07-24 16:54 UTC
**Describe the bug**

Version asked for is not the one installed:

![Capture d’écran de 2020-07-24 18-44-40](https://user-images.githubusercontent.com/43777839/88414872-d6986700-cddd-11ea-8933-dd9fd46bad59.png)

**To Reproduce**
1. glooctl install gateway --version 1.4.5 --with-admin-console
2. glooctl version -o table
3. gloo, discovery, gateway and gloo-envoy-wrapper components are in version 1.4.6. Only UI components are in 1.4.5

I know UI components lag behind Gloo OSS releases but here we clearly expect to have version 1.4.5 of Gloo installed.

Deploying without the Dashboard does not exhibit this behavior:
1. glooctl install gateway --version 1.4.5
2. glooctl version -o table
3. gloo, discovery, gateway and gloo-envoy-wrapper components are in version 1.4.5

**Expected behavior**
Honor glooctl version flag's value.

**Additional context**
Add any other context about the problem here, e.g.
- Glooctl version 1.4.5 and 1.4.6
- Kubernetes version 1.18.3

**Comment by kdorosh** [comment] 2020-07-31 17:01
As I see, this is confusing but expected behavior. The cause here is that Gloo with the read-only UI is actually Gloo Enterprise with some features disabled, so installing gloo with `glooctl install gateway --version 1.4.5 --with-admin-console` installs the modified version of the GlooE chart.

Since we are effectively installing GlooE 1.4.5 (with just the apiserver components), we need to ensure we install core Gloo containers that work with their respective GlooE components (in this case, Gloo 1.4.6).

Closing as working as intended. Please reopen if we have some concrete action to take here to make the behavior here clearer

**Closed by kdorosh** 2020-07-31 17:01 UTC
Labels: Type: Bug
