### ISSUE TITLE
Client IP matching in Virtual Services

### ISSUE THREAD

**Issue by guydc** [solo-io/gloo#5324] opened 2021-09-14 15:15 UTC
**Describe the solution you'd like**
Virtual Services should also support Client IP matching. Some use cases include:
- Different TLS and routing configurations for the same domain, depending on Client IP
- Exposing Virtual Services to specific Client IPs

**Comment by chrisgaun** [comment] 2021-09-17 15:07
Relates to https://github.com/envoyproxy/envoy/issues/11690

**Comment by sam-heilbron** [comment] 2021-10-12 22:15
The open question is whether these VirtualServices will be on the same listener, or different listeners (https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listeners#listeners)

Scenario A: Virtual Services are on separate Listeners
Then we only need to expose the envoy config for [Filter Chain matchers](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-msg-config-listener-v3-filterchain) as @bcollard pointed out.

Scenario B: Virtual Services are on the same Listener
Currently, Gloo only supports a single Filter chain per listener (it was designed when Envoy only supported a single filter chain per listener). We would need to update the Gloo API to expose multiple HttpConnectionManagers (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html?highlight=hcm). Envoy supports this functionality, but we would need to bring Gloo Edge to feature parity.

**Comment by bewebi** [comment] 2021-12-23 18:04
A new "Hybrid" Gateway type has been added that allows for the matching requests to sub-Gateways based on Client IP
This will be released, along with a guide in public docs, in 1.11.0-beta2 and backported to 1.10 as well

**Comment by sam-heilbron** [comment] 2021-12-27 19:34
Remaining work:
- [ ] Release Gloo Edge Enterprise with this feature
- [ ] Backport to 1.10

**Comment by sam-heilbron** [comment] 2022-01-03 14:32
@bewebi  There is a validation that two virtual services under the same gateway do not share the same domain. With this feature, this requirement should be relaxed: two VS may share the same domain, as long as they have additional matchers (e.g. source ip). Is this implemented?

**Comment by bewebi** [comment] 2022-01-03 18:27
This is already the case because each matched gateway within a given hybrid gateway is evaluated in isolation
In [these lines](https://github.com/solo-io/gloo/blob/master/projects/gateway/pkg/translator/hybrid.go#L58-L60) we retrieve the virtual services for a given matched HTTP gateway and pass them to `validateVirtualServiceDomains()` which is where the collision will be detected and an error emitted
Neighbor matched gateways are out of scope when the validate function is called, so domains that collide from different matched gateways will not be considered

The requirement that matchers must be unique for a given matched gateway is enforced [here](https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/translator/listener.go#L44)

I have manually verified this behavior as well

**Closed** 2022-01-07 19:32 UTC
Labels: Type: Enhancement, Size: M, Roadmap: NOW
