### ISSUE TITLE
glooctl check stack dumps

### ISSUE THREAD

**Issue by totallyGreg** [solo-io/gloo#5061] opened 2021-07-21 16:06 UTC
**Describe the bug**
Error messages led client to run glooctl check which failed with: 

```
Checking deployments... OK
Checking pods... OK
OK
"Thu, 08 Jul 2021 10:43:50 EDT: /workspace/gloo/projects/gloo/cli/pkg/helpers/clients.go:246"	failed to create upstream group client: &errors.withStack{
  error: &errors.withMessage{
    cause: &errors.withStack{
      error: &errors.withMessage{
        cause: &errors.withStack{
          error: &errors.withMessage{
            cause: &url.Error{
              Op:  "Get",
              URL: "https://<REDACTED>.gr7.us-east-1.eks.amazonaws.com/apis/gloo.solo.io/v1/namespaces/lean-fnx-reference-servicetest-e79360c2/upstreamgroups",
              Err: &net.OpError{
                Op:     "dial",
                Net:    "tcp",
                Source: nil,
                Addr:   nil,
                Err:    &net.DNSError{
                  Err:         "no such host",
                  Name:        "<REDACTED>.gr7.us-east-1.eks.amazonaws.com",
                  Server:      "127.0.0.53:53",
                  IsTimeout:   false,
                  IsTemporary: false,
                  IsNotFound:  true,
                },
              },
            },
            msg: "list check failed",
          },
          stack: &errors.stack{
            0x1c6a0b2,
            0x1d53683,
            0x1d5483a,
            0x25a3045,
            0x25a2e55,
            0x3042360,
            0x3041d85,
            0x3041ca4,
            0x38d1481,
            0x38cadac,
            0x38d81f3,
            0x671af1,
            0x67286f,
            0x67211b,
            0x39d39e4,
            0x43bfa8,
            0x46cdd1,
          },
        },
        msg: "creating base UpstreamGroup resource client",
      },
      stack: &errors.stack{
        0x1c6a0b2,
        0x25a30fe,
        0x25a2e55,
        0x3042360,
        0x3041d85,
        0x3041ca4,
        0x38d1481,
        0x38cadac,
        0x38d81f3,
        0x671af1,
        0x67286f,
        0x67211b,
        0x39d39e4,
        0x43bfa8,
        0x46cdd1,
      },
    },
    msg: "creating upstream groups client",
  },
  stack: &errors.stack{
    0x1c6a0b2,
    0x3042422,
    0x3041d85,
    0x3041ca4,
    0x38d1481,
    0x38cadac,
    0x38d81f3,
    0x671af1,
    0x67286f,
    0x67211b,
    0x39d39e4,
    0x43bfa8,
    0x46cdd1,
  },
}
```

**To Reproduce**
1. Have AWS EKS cluster with IAM authenticator throwing errors
2. Run glooctl check 
3. See stack dump

**Expected behavior**
Glooctl should either indicate everything is okay, or provide a useful description of what went wrong.  

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: client/server version 1.7.6
- Kubernetes version: AWS EKS unknown version

There seems to be an issue with AWS IAM authenticator precipitating this issue with lots of error messages saying 
`W0719 15:10:09.019596   27410 exec.go:271] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 2248 clients constructed calling "aws"`

- This is being run locally on a linux machine
- 127.00.53 is configured as the nameserver in resolv.conf
- The REDACTED.gr7.us-east-1.eks.amazonaws.com hostname is resolvable and they are able to connect to it via kubectl.  
- other glooctl commands work fine
- They do not have any upstreamgroups deployed
- Underlying issue is likely a problem with local name resolution

**Comment by pmichna** [comment] 2021-08-05 10:05
I'm getting a very similar error for `glooctl check` which makes debugging difficult. It always fails at `Checking auth configs`.
- AWS EKS version 1.19
```
$ glooctl version
Client: {"version":"1.8.3"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.8.0","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.8.0","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.8.0","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.8.0","Name":"gloo-ee","Registry":"quay.io/solo-io"}],"namespace":"gloo-system"}}

$ glooctl check

Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... "Thu, 05 Aug 2021 11:48:21 CEST: /private/tmp/glooctl-20210724-68352-1kk57ph/projects/gloo/cli/pkg/helpers/clients.go:594"	failed to create auth config client: &errors.withStack{
  error: &errors.withMessage{
    cause: &errors.withStack{
      error: &errors.withMessage{
        cause: &errors.withStack{
          error: &errors.withMessage{
            cause: &url.Error{
              Op:  "Get",
              URL: "https://<REDACTED>.gr7.us-east-1.eks.amazonaws.com/apis/enterprise.gloo.solo.io/v1/namespaces/pr-27315-ns/authconfigs",
              Err: &net.OpError{
                Op:     "dial",
                Net:    "tcp",
                Source: nil,
                Addr:   nil,
                Err:    &net.DNSError{
                  Err:         "no such host",
                  Name:        "<REDACTED>.gr7.us-east-1.eks.amazonaws.com",
                  Server:      "",
                  IsTimeout:   false,
                  IsTemporary: false,
                  IsNotFound:  true,
                },
              },
            },
            msg: "list check failed",
          },
          stack: &errors.stack{
            0x10359ec6c,
            0x103659554,
            0x10365a21c,
            0x1038fca54,
            0x1038fc8f4,
            0x104381ac0,
            0x104381684,
            0x1043815ec,
            0x104a1772c,
            0x104a11e28,
            0x104a1d984,
            0x1023c43a8,
            0x1023c4e80,
            0x1023c48f0,
            0x104a53980,
            0x1021e3da4,
            0x102217f84,
          },
        },
        msg: "creating base AuthConfig resource client",
      },
      stack: &errors.stack{
        0x10359ec6c,
        0x1038fcad0,
        0x1038fc8f4,
        0x104381ac0,
        0x104381684,
        0x1043815ec,
        0x104a1772c,
        0x104a11e28,
        0x104a1d984,
        0x1023c43a8,
        0x1023c4e80,
        0x1023c48f0,
        0x104a53980,
        0x1021e3da4,
        0x102217f84,
      },
    },
    msg: "creating auth config client",
  },
  stack: &errors.stack{
    0x10359ec6c,
    0x104381b3c,
    0x104381684,
    0x1043815ec,
    0x104a1772c,
    0x104a11e28,
    0x104a1d984,
    0x1023c43a8,
    0x1023c4e80,
    0x1023c48f0,
    0x104a53980,
    0x1021e3da4,
    0x102217f84,
  },
}
```

**Comment by pmichna** [comment] 2021-09-16 13:35
@totallyGreg @chrisgaun 
Any news about this issue? Kind of important functionality not working - I wouldn't like to have Gloo in production with this error.

**Comment by bewebi** [comment] 2021-11-01 18:10
I'm struggling to reproduce the circumstance where IAM throws errors
@totallyGreg or @pmichna, are there reproducible steps I can take to trigger these theres?
If I'm unable to reproduce the original behavior, I'll proceed by hard-coding an error return at the point in code where the reported error is coming and ensure that at the very least glooctl recovers cleanly

**Comment by bewebi** [comment] 2021-11-01 19:24
I have a solution that turns this stack dump behavior:
```
$ glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... "Mon, 01 Nov 2021 15:03:57 EDT: github.com/solo-io/gloo/projects/gloo/cli/pkg/helpers/clients.go:212"	failed to create upstream client: &errors.withStack{
  error: &errors.withMessage{
    cause: &errors.withStack{
      error: &errors.withMessage{
        cause: &errors.errorString{
          s: "rcFactory error",
        },
        msg: "fake error creating upstream resource client",
      },
      stack: &errors.stack{
        0x28a3d85,
        0x3188397,
        0x3188015,
        0x3acea4c,
        0x3ace435,
        0x3ace33f,
        0x40cc42e,
        0x40c5f3f,
        0x40d82be,
        0x12807d6,
        0x12815f5,
        0x1280e5b,
        0x411d777,
        0x1042883,
        0x107aa61,
      },
    },
    msg: "creating upstreams client",
  },
  stack: &errors.stack{
    0x28a3d85,
    0x3aceb0e,
    0x3ace435,
    0x3ace33f,
    0x40cc42e,
    0x40c5f3f,
    0x40d82be,
    0x12807d6,
    0x12815f5,
    0x1280e5b,
    0x411d777,
    0x1042883,
    0x107aa61,
  },
}
```
into this:
```
$ glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... 1 Errors!
Checking upstream groups... OK
Checking auth configs... OK
Checking rate limit configs... OK
Checking VirtualHostOptions... OK
Checking RouteOptions... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... OK
Checking rate limit server... OK
Error: 1 error occurred:
	* creating upstreams client: fake error creating upstream resource client: rcFactory error
```
Is this essentially what's desired?

**Comment by bewebi** [comment] 2021-11-01 21:50
As far as the underlying errors, they may be stemming from [this issue](https://github.com/kubernetes/kubernetes/issues/91913) which, according to the conversation there, is resolved as of kubernetes 1.21

**Comment by pmichna** [comment] 2021-11-02 13:33
@bewebi 

> are there reproducible steps I can take to trigger these theres?

I'm not sure how to reproduce the error on a new cluster. We have Gloo Edge installed in two clusters. One always yields the error, the other works fine. The problematic cluster is our staging cluster - the bigger one and with more dynamic nodes and containers (test environments are created and deleted often). Both clusters have the same setup and run on EKS 1.19.

> Is this essentially what's desired?

My desire is to have `glooctl check` working for both clusters. :) I understand your fix limits the problem so that `glooctl check` continues to verify whatever it can even if there's an error for one of the resources, right?

**Comment by bewebi** [comment] 2021-11-02 20:15
Thanks for the response

As far as the behavior you're seeing, I'd like to clarify:
Does the error in `glooctl check` always occur at the same point (ie while checking auth configs)? or does it vary from run to run or when state is changed?

I do think there's been some fuzziness as to whether we're trying to fix the `glooctl` tool (so that it doesn't crash in the case where we run into this error) or whether we're trying to address the underlying issue/bug that's leading to the errors themselves. The former I'd characterize as getting `glootcl check` _working_ and the latter as getting `glooctl check` _passing_.

I think we can get `glooctl check` _working_ relatively easily as laid out [above](https://github.com/solo-io/gloo/issues/5061#issuecomment-956521525) but _passing_ will be a larger piece of work if it does require a bump to kubernetes 1.21.

We haven't been able to reproduce the `no such host` error so far, so can't pinpoint the cause or solution with a high degree of certainty. That said, the fact that the larger scale cluster is the one that's having issues fits the theory that it's a result of the previously linked issue and would be resolved by bumping to kubernetes 1.21.

**Comment by sam-heilbron** [comment] 2021-11-08 14:37
We have opened an issue to upgrade our libraries that we expect to resolve this issue. Please follow the progress of https://github.com/solo-io/gloo/issues/5543 to track that work.

**Comment by sam-heilbron** [comment] 2021-12-28 15:08
Hi @pmichna we recently released an upgrade to our k8s libraries that we expect to resolve this issue for you. Can you confirm?

**Comment by pmichna** [comment] 2021-12-29 17:12
@sam-heilbron Nope, the problem still exists. In which version have you released the fixes?

```
$ glooctl version

Client: {"version":"1.9.7"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.9.6","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.9.7","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.9.7","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.9.7","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.9.7","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"6.2.4","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}

**Comment by sam-heilbron** [comment] 2021-12-30 05:34
Hi @pmichna, the work to upgrade kube versions was completed here: https://github.com/solo-io/gloo/pull/5702/files. It was introduced in 1.10.0-beta12

**Comment by pmichna** [comment] 2021-12-30 09:20
I will wait until 1.10 is stable then. :)

**Comment by kevin-shelaga** [comment] 2022-01-19 13:30
Looks like this is still an issue with client version 1.10.2

**Comment by kcbabo** [comment] 2022-02-04 13:37
I suggest we address this issue in two phases:

1. Clean up the error message as Bernie described in an earlier comment.
2. Continue to investigate a way to consistently reproduce this behavior and address the root cause.

Let's get (1) in quickly as we continue to see users hit this issue and it's annoying.

**Comment by MitchAman** [comment] 2022-02-15 14:07
> @cdancy thanks for the quick feedback! I will investigate this tomorrow and prepare a fix to go out Monday morning.

I've had no luck in reproducing this using glooctl v1.10.8

**Closed** 2022-02-16 15:01 UTC
Labels: Type: Bug, Size: M, Priority: High, zendesk
