### ISSUE TITLE
VirtualService, RouteTables, and Gateway CRDs not processing after upgrading to 1.11.x

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#6322] opened 2022-04-14 18:16 UTC
### Gloo Edge Version

1.11.x (latest stable)

### Describe the bug

Gateway pod is not processing VirtualService after upgrading from 1.10.7 to 1.11.3.  The logs from the `gateway` pod shows the following error:

```{"level":"info","ts":"2022-04-14T18:05:20.935Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:69","msg":"begin sync 11440180875848162361 (2 virtual services, 2 gateways, 0 route tables)","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:05:20.936Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:99","msg":"desired proxy name:\"gateway-proxy\" namespace:\"gloo-system\"","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:05:20.973Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:81","msg":"end sync 11440180875848162361","version":"1.11.4"}
{"level":"error","ts":"2022-04-14T18:05:20.974Z","logger":"gateway.v1.event_loop.gateway","caller":"syncer/setup_syncer.go:335","msg":"error: event_loop: 1 error occurred:\n\t* reconciling resource gateway-proxy: updating kube resource gateway-proxy: (want 2774): proxies.gloo.solo.io \"gateway-proxy\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update\n\n","version":"1.11.4","stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/syncer.RunGateway.func1\n\t/workspace/gloo/projects/gateway/pkg/syncer/setup_syncer.go:335"}
```

### Steps to reproduce the bug

1. Install 1.11.0-RC1
2. Deploy a httpbin and sample VirtualService:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin-11-rc
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'foo'
    routes:
      - matchers:
          - prefix: /api/httpbin
        routeAction:
          single:
            upstream:
              name: default-httpbin-8000
              namespace: gloo-system
        options:
          prefixRewrite: /

```
3. The VS will be in the process state:
```
status:
  statuses:
    gloo-system:
      reportedBy: gateway
      state: 1
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system':
          reportedBy: gloo
          state: 1
```
4. Upgrade to 1.11.3 and apply the new CRDs.
```
helm pull glooe/gloo-ee --version 1.11.3 --untar
k delete crd graphqlapis.graphql.gloo.solo.io
k  apply -f gloo-ee/charts/gloo/crds
```
5. Create a new VS:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin-11-4
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'foo-4'
    routes:
      - matchers:
          - prefix: /api/httpbin
        routeAction:
          single:
            upstream:
              name: default-httpbin-8000
              namespace: gloo-system
        options:
          prefixRewrite: /
```

The gateway pod will have an error and the reconcile of the VirtualService won't be processed.

### Expected Behavior

After upgrading, newly created VirtualServices should be processed.

**Comment by pszeto** [comment] 2022-04-14 18:28
Workaround is to delete the proxy object `k delete -n gloo-system proxies.gloo.solo.io gateway-proxy`.

The `gateway` logs will show it reconciling correctly:
```
{"level":"error","ts":"2022-04-14T18:04:51.972Z","logger":"gateway.v1.event_loop.gateway","caller":"syncer/setup_syncer.go:335","msg":"error: event_loop: 1 error occurred:\n\t* reconciling resource gateway-proxy: updating kube resource gateway-proxy: (want 2774): proxies.gloo.solo.io \"gateway-proxy\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update\n\n","version":"1.11.4","stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/syncer.RunGateway.func1\n\t/workspace/gloo/projects/gateway/pkg/syncer/setup_syncer.go:335"}
{"level":"info","ts":"2022-04-14T18:05:19.309Z","logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook","caller":"k8sadmission/validating_admission_webhook.go:195","msg":"received validation request","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:05:19.330Z","logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook","caller":"k8sadmission/validating_admission_webhook.go:263","msg":"Ready to write response ...","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:05:20.935Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:69","msg":"begin sync 11440180875848162361 (2 virtual services, 2 gateways, 0 route tables)","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:05:20.936Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:99","msg":"desired proxy name:\"gateway-proxy\" namespace:\"gloo-system\"","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:05:20.973Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:81","msg":"end sync 11440180875848162361","version":"1.11.4"}
{"level":"error","ts":"2022-04-14T18:05:20.974Z","logger":"gateway.v1.event_loop.gateway","caller":"syncer/setup_syncer.go:335","msg":"error: event_loop: 1 error occurred:\n\t* reconciling resource gateway-proxy: updating kube resource gateway-proxy: (want 2774): proxies.gloo.solo.io \"gateway-proxy\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update\n\n","version":"1.11.4","stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/syncer.RunGateway.func1\n\t/workspace/gloo/projects/gateway/pkg/syncer/setup_syncer.go:335"}
{"level":"info","ts":"2022-04-14T18:23:39.528Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:69","msg":"begin sync 11440180875848162361 (2 virtual services, 2 gateways, 0 route tables)","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:23:39.529Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:99","msg":"desired proxy name:\"gateway-proxy\" namespace:\"gloo-system\"","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:23:39.564Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:81","msg":"end sync 11440180875848162361","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:23:39.598Z","logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook","caller":"k8sadmission/validating_admission_webhook.go:195","msg":"received validation request","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:23:39.612Z","logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook","caller":"k8sadmission/validating_admission_webhook.go:263","msg":"Ready to write response ...","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:23:40.600Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:69","msg":"begin sync 11440180875848162361 (2 virtual services, 2 gateways, 0 route tables)","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:23:40.600Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:99","msg":"desired proxy name:\"gateway-proxy\" namespace:\"gloo-system\"","version":"1.11.4"}
{"level":"info","ts":"2022-04-14T18:23:40.637Z","logger":"gateway.v1.event_loop.gateway.v1.event_loop.translatorSyncer","caller":"syncer/translator_syncer.go:81","msg":"end sync 11440180875848162361","version":"1.11.4"
```

and the status will be updated on the newly deployed VirtualService:
```
status:
  statuses:
    gloo-system:
      reportedBy: gateway
      state: 1
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system':
          reportedBy: gloo
          state: 1
```

**Comment by kevinjom** [comment] 2022-04-21 08:03
we are seeing this issue in `1.11.2` and `1.11.4` too, we are upgrading from `1.9.x`, could someone please point out what is the latest version that doesn't have this issue?

**Comment by chrisgaun** [comment] 2022-04-22 13:20
@kevinjom we are working on issue that should solve this.

**Comment by kevinjom** [comment] 2022-05-06 03:14
hi folks, just to share that we were using helm to manage gloo deployment, we uninstalled the helm release, then performed a new install which caused this issue, the reason is the CRDs were not uninstalled and when we reinstall, the old CRDs were not updated. More see <https://helm.sh/docs/topics/charts/#limitations-on-crds>

**Comment by sam-heilbron** [comment] 2022-05-18 11:37
This is a duplicate of https://github.com/solo-io/gloo/issues/6406, which has now been resolved. For more details, please refer to: https://github.com/solo-io/gloo/issues/6406#issuecomment-1129899366

**Closed by sam-heilbron** 2022-05-18 11:37 UTC
Labels: Type: Bug, zendesk
