### ISSUE TITLE
Expose Envoy's append_x_forwarded_host through the Gloo API

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8506] opened 2023-07-25 00:08 UTC
### Version

1.14.x (latest stable)

### Is your feature request related to a problem? Please describe.

Some applications require the original host header value to be appended to the `x-forwarded-host` header. This is supported in Envoy via `append_x_forwarded_host`:

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-append-x-forwarded-host

But not exposed in the Gloo API:

https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk/#routeoptions

### Describe the solution you'd like

Expose Envoy's `append_x_forwarded_host` through the Gloo API

**Comment by sam-heilbron** [comment] 2023-07-25 00:35
This is available in RouteOptions: https://github.com/solo-io/gloo/blob/main/projects/gloo/api/v1/options.proto#L369

**Comment by bdecoste** [comment] 2023-07-25 00:44
Looks like this was added in 1.15 only so may need to be backported ...

**Comment by SantoDE** [comment] 2023-07-26 09:18
Duplicate of #7683. Closing

**Closed by SantoDE** 2023-07-26 09:18 UTC
Labels: Type: Enhancement
