### ISSUE TITLE
K8S 1.25 support 

### ISSUE THREAD

**Issue by TomerJLevy** [solo-io/gloo#7853] opened 2023-02-14 16:09 UTC
### Version

1.12.x

### Is your feature request related to a problem? Please describe.

Several changes are needed in order to upgrade to K8S v1.25.
Some of them I noticed are:
- The `policy/v1beta1` API version of `PodDisruptionBudget` is no longer served as of v1.25
  - use the policy/v1 API version, available since v1.21.
- `PodSecurityPolicy` in the `policy/v1beta1` API version is no longer served as of v1.25
  - Migrate to [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/) or a [3rd party admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/)

The most important thing for us would be the first one since it's being used not only in `Grafana` or `Prometheus`, so it's blocking us from upgrading the system even after disabling them

### Describe the solution you'd like

Follow the [Deprecation Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/) and migrate manifests and API clients to use the supportקג API version.

**Comment by SantoDE** [comment] 2023-02-23 08:53
Duplicate of #6833. Closed.

**Closed by SantoDE** 2023-02-23 08:53 UTC
Labels: Type: Enhancement
