### ISSUE TITLE
append: false not working for headerManipulation

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#8525] opened 2023-07-28 14:03 UTC
### Gloo Edge Version

1.15.x (beta)

### Kubernetes Version

None

### Describe the bug

It seems that [append](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-field-config-core-v3-headervalueoption-append) field is deprecated in envoy, I have a headerManipulation in my VirtualService and the same headerManipulation in my child RouteTable with append false, but they are getting appended any way, the header never gets overwritten, so it seems with the deprecation of this field this stopped working.

### Steps to reproduce the bug

Steps to reproduce:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      headerManipulation:
        responseHeadersToAdd:
        - header:
            key: X-Frame-Options
            value: SAMEORIGIN
    routes:
    - delegateAction:
        selector:
          labels:
            delegate: true
      matchers:
      - prefix: /
 --------
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  labels:
    delegate: true
  name: child
  namespace: gloo-system
spec:
  routes:
  - matchers:
    - prefix: /get
    options:
      headerManipulation:
        responseHeadersToAdd:
        - append: false
          header:
            key: X-Frame-Options
            value: NEWORIGIN
    routeAction:
      single:
        upstream:
          name: default-httpbin-8000
          namespace: gloo-system
```

### Expected Behavior

Regarding the above VS and RT, X-Frame-Options header should be overwritten with value NEWORIGIN as I have append: true in the RouteTable, however it gets added to the previous header so in the response I am able to see both NEWORIGIN and SAMEORIGIN.

**Comment by edubonifs** [comment] 2023-08-07 11:02
Might be related to https://github.com/solo-io/gloo/issues/8477

**Comment by SantoDE** [comment] 2023-08-14 09:45
It's also happening on 1.14.9. Its based on potentially https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-field-config-core-v3-headervalueoption-append

**Comment by Jimmmz** [comment] 2023-08-31 08:37
From Crealogix 
```
We have upgraded to Gloo Edge 1.15.1 and were running into the issue https://github.com/solo-io/gloo/issues/8525
This is a blocker for us for the upgrade. We need to support Kubernetes 1.26 (a customer is waiting for it) and therefore need to upgrade to the latest 1.15 version as only 1.15.x support Kubernetes > 1.25
```
[Slack thread](https://solo-io.slack.com/archives/GTDP41M09/p1693468096781079)

**Comment by sam-heilbron** [comment] 2023-09-01 11:37
This field was deprecated in https://github.com/envoyproxy/envoy/pull/22723, though I haven't found the PR yet where this field was removed from the implementation (if that is the case). This is called out in the 1.24 deprecation notes: https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.24/v1.24.0#deprecated.

@Jimmmz what version was being run before 1.15.1? That will help us narrow down when this behavior stopped working and alert others of the change.


Internally I think we should explore https://github.com/envoyproxy/envoy/blob/main//CONTRIBUTING.md#breaking-change-policy and consider leveraging:
```
If the runtime key envoy.features.fail_on_any_deprecated_feature is enabled, use of deprecated fields will trigger a configuration load failure rather than a logged warning.
```
as this will help us more proactively identify these changes

**Comment by nfuden** [comment] 2023-09-01 12:11
Envoy 1.24 single changelog to both deprecated and fully remove functionality.

**Comment by marckamerbeek** [comment] 2023-09-06 12:12
Blocking for us as well. Teams start to move around Gloo Edge to get things done.

**Comment by inFocus7** [comment] 2023-09-12 21:19
After some more digging, I'm not sure the issue is due to the field being deprecated. I have [some local work](https://github.com/solo-io/gloo/pull/8678/files) which translates our `append` field to Envoy's `append_action` (which is their new preferred field), but seeing the same issue.

When adding `append: false` to the VirtualService itself, that's when the overwriting works... but it overwrites the route's header instead of the vs header (so we have `SAMEORIGIN`, not `NEWORIGIN`).

(Still investigating, just providing updates on findings 👍🏼)

**Comment by inFocus7** [comment] 2023-09-18 15:05
# Update

From testing multiple releases (**main**, **1.15.1**, **1.14.0-beta1**, **1.12.58** , and **1.11.38**), I found that there hasn't been any change in behavior of the `append`. In all, the VHost header manipulations could overwrite the Route's but not the reverse.

Note: Our docs do mistakenly say that the behavior is the opposite (what users here expect), but they are being updated with the correct information.

---

From the [Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#custom-request-response-headers), the behavior outlined in the issue as a bug is actually expected.
> Headers are appended to requests/responses in the following order: weighted cluster level headers, route level headers, virtual host level headers and finally global level headers.

Because the Route-level header is processed **before** the VHost, the route's `append: false` has no affect to the VHost.

## Workaround / Possible Solution

Envoy has a [most_specific_header_mutations_wins](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#config-route-v3-routeconfiguration) field which 
I have created #8690 and I'm working on exposing it. From local testing, it does what users here are expecting (route to overwrite vhost)
> ([bool](https://developers.google.com/protocol-buffers/docs/proto#scalar)) By default, headers that should be added/removed are evaluated from most to least specific:
> * route level
> * virtual host level
> * connection manager level
>
> To allow setting overrides at the route or virtual host level, this order can be reversed by setting this option to true. Defaults to false.

**Comment by inFocus7** [comment] 2023-09-21 20:11
# Release Information

Updating as code gets merged and released. Check-marking when released.

## OSS
- [ ] v1.16.0-beta10
- [ ] v1.15.6
- [ ] v1.14.20

## Enterprise
- [ ] v1.16.0-beta?
- [ ] v1.15.?
- [ ] v1.14.?

**Comment by inFocus7** [comment] 2023-09-22 15:17
Closing, as the code has been merged. Will be updating the [release information](https://github.com/solo-io/gloo/issues/8690#issuecomment-1730232613) comment above as merge + releases roll out.

**Closed by inFocus7** 2023-09-22 15:17 UTC
Labels: Type: Bug, Priority: Blocker, release/1.14, release/1.15, release/1.16
