### ISSUE TITLE
Rejected RouteTable prevents updates for other RouteTables on same tree

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#5502] opened 2021-10-25 21:49 UTC
**Describe the bug**
When delegating control for a given prefix to route tables via selection, if a selected RT contains a prefix mismatch, any other routes defined in selected RTs will not be processed. In other words, if a single route anywhere in the tree for a given prefix is `Rejected`, users can not update existing routes or add new routes to that node. This may prevent all updates to the VS (?) -- I haven't tested this piece, which could be even more impactful

**To Reproduce**
1. Create VS
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
       - prefix: '/foo'
      delegateAction:
        selector:
          labels:
            routes: petstore
          namespaces:
          - gloo-system
```

2. Create RT for /foo
```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-routes-foo
  namespace: gloo-system
  labels:
    routes: petstore
spec:
  routes:
  - matchers:
    - prefix: /foo
    routeAction:
      single:
        upstream:
          name: default-petstore-8080
          namespace: gloo-system
```

3. Create RT with incorrect prefix
```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-routes
  namespace: gloo-system
  labels:
    routes: petstore
spec:
  routes:
  - matchers:
    - prefix: /
    routeAction:
      single:
        upstream:
          name: default-petstore-8080
          namespace: gloo-system
```

4. Modify existing good RT to use a directResponse
```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-routes-foo
  namespace: gloo-system
  labels:
    routes: petstore
spec:
  routes:
  - matchers:
    - prefix: /foo
    directResponseAction:
      status: 200
      body: "Hello, world!"
```

curl against /foo:
```
% curl localhost:8080/foo/
{"code":404,"message":"path /foo/ was not found"}
```

Should be direct response, but get routed to petstore still.

**Expected behavior**
The rejected RT should be sanitized/removed and other updates from other RTs should work fine.

**Additional context**
GlooE 1.8.15

**Comment by sam-heilbron** [comment] 2021-11-12 14:53
Duplicate of: https://github.com/solo-io/gloo/issues/5154

**Comment by jenshu** [comment] 2021-11-22 13:18
There are a couple of issues:
1. The gateway validation webhook was not properly rejecting the bad route table. This is because the validation webhook is only checking delegate chains that use direct references (not selectors) so it wasn't properly verifying that the bad route table's prefix was valid with respect to its parent prefix. A PR to fix this is [here](https://github.com/solo-io/gloo/pull/5607)
2. The gateway proxy reconciler [strips invalid virtual hosts](https://github.com/solo-io/gloo/blob/8149aaeabe60d26a507badeaa1656792622ed5dd/projects/gateway/pkg/reconciler/proxy_reconciler.go#L172) from the proxy, thus causing further updates to not reach the proxy. I haven't determined the best solution to this yet. Perhaps we need to perform route sanitizing earlier (in gateway instead of gloo)

**Comment by jenshu** [comment] 2021-12-07 20:22
need to backport to 1.8 and 1.9

**Comment by kdorosh** [comment] 2021-12-09 16:59
reopening for backports

**Comment by jenshu** [comment] 2021-12-09 22:20
backports are merged, fix will be available in the next releases

**Closed by jenshu** 2021-12-09 22:20 UTC
Labels: Type: Bug, Size: M
