### ISSUE TITLE
inja transformation can cause proxy pod to crash and restart

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2160] opened 2020-01-10 15:13 UTC
```
$ kubectl -n gloo-system get vs default -o yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  creationTimestamp: "2020-01-10T14:36:09Z"
  generation: 5
  name: default
  namespace: gloo-system
  resourceVersion: "591286"
  selfLink: /apis/gateway.solo.io/v1/namespaces/gloo-system/virtualservices/default
  uid: 8aeb71c5-33b6-11ea-9ba8-42010aa80059
spec:
  virtualHost:
    domains:
    - '*'
    options:
      transformations:
        responseTransformation:
          transformationTemplate:
            headers:
              :status:
                text: '{% if header(":status") == "404" %}200{% endif %}'
    routes:
    - matchers:
      - prefix: /auth
      routeAction:
        single:
          upstream:
            name: default-keycloak-8080
            namespace: gloo-system
    - matchers:
      - prefix: /api
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
status:
  reported_by: gateway
  state: 1
  subresource_statuses:
    '*v1.Proxy.gloo-system.gateway-proxy':
      reported_by: gloo
      state: 1

```

**Comment by bdecoste** [comment] 2020-01-10 15:15
This works as expected:

```
$ curl -w "%{http_code}" $(glooctl proxy url)/api/blah
{"code":404,"message":"path /api/blah was not found"}200
```

**Comment by bdecoste** [comment] 2020-01-10 15:16
This causes the proxy pod to crash:

```
$ curl $(glooctl proxy url)/api/pets
curl: (52) Empty reply from server
```

**Comment by bdecoste** [comment] 2020-01-10 15:16
```
[2020-01-10 14:52:53.798][21][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1246] [C7][S2834596312551612103] request end stream
[2020-01-10 14:52:53.798][21][debug][router] [external/envoy/source/common/router/router.cc:440] [C7][S2834596312551612103] cluster 'admin_port_cluster' match for URL '/metrics'
[2020-01-10 14:52:53.799][21][debug][router] [external/envoy/source/common/router/router.cc:555] [C7][S2834596312551612103] router decoding headers:
':authority', '10.64.0.40:8081'
':path', '/stats/prometheus'
':method', 'GET'
':scheme', 'http'
'user-agent', 'Prometheus/2.13.1'
'accept', 'application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1'
'accept-encoding', 'gzip'
'x-prometheus-scrape-timeout-seconds', '10.000000'
'x-forwarded-proto', 'http'
'x-request-id', '7f29936a-9567-4e8f-9ad5-df3ed6113141'
'x-envoy-expected-rq-timeout-ms', '15000'
'x-envoy-original-path', '/metrics'

[2020-01-10 14:52:53.799][21][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:104] [C8] using existing connection
[2020-01-10 14:52:53.799][21][debug][router] [external/envoy/source/common/router/router.cc:1614] [C7][S2834596312551612103] pool ready
[2020-01-10 14:52:53.800][6][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:259] [C9] new stream
[2020-01-10 14:52:53.804][6][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:695] [C9][S3203813315464740107] request headers complete (end_stream=true):
':authority', '10.64.0.40:8081'
':path', '/stats/prometheus'
':method', 'GET'
'user-agent', 'Prometheus/2.13.1'
'accept', 'application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1'
'accept-encoding', 'gzip'
'x-prometheus-scrape-timeout-seconds', '10.000000'
'x-forwarded-proto', 'http'
'x-request-id', '7f29936a-9567-4e8f-9ad5-df3ed6113141'
'x-envoy-expected-rq-timeout-ms', '15000'
'x-envoy-original-path', '/metrics'
'content-length', '0'

[2020-01-10 14:52:53.818][6][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1246] [C9][S3203813315464740107] request end stream
[2020-01-10 14:52:53.827][6][debug][admin] [external/envoy/source/server/http/admin.cc:1192] [C9][S3203813315464740107] request complete: path: /stats/prometheus
[2020-01-10 14:52:53.925][6][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1567] [C9][S3203813315464740107] encoding headers via codec (end_stream=false):
':status', '200'
'content-type', 'text/plain; charset=UTF-8'
'cache-control', 'no-cache, max-age=0'
'x-content-type-options', 'nosniff'
'date', 'Fri, 10 Jan 2020 14:52:53 GMT'
'server', 'envoy'

[2020-01-10 14:52:53.927][21][debug][router] [external/envoy/source/common/router/router.cc:1041] [C7][S2834596312551612103] upstream headers complete: end_stream=false
[2020-01-10 14:52:53.927][21][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1567] [C7][S2834596312551612103] encoding headers via codec (end_stream=false):
':status', '200'
'content-type', 'text/plain; charset=UTF-8'
'cache-control', 'no-cache, max-age=0'
'x-content-type-options', 'nosniff'
'date', 'Fri, 10 Jan 2020 14:52:53 GMT'
'server', 'envoy'
'x-envoy-upstream-service-time', '127'

[2020-01-10 14:52:53.927][21][debug][connection] [external/envoy/source/common/network/connection_impl.cc:441] [C7] onAboveWriteBufferHighWatermark
[2020-01-10 14:52:53.930][21][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1812] [C7][S2834596312551612103] Disabling upstream stream due to downstream stream watermark.
[2020-01-10 14:52:53.932][21][debug][connection] [external/envoy/source/common/network/connection_impl.cc:432] [C7] onBelowWriteBufferLowWatermark
[2020-01-10 14:52:53.932][21][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1817] [C7][S2834596312551612103] Enabling upstream stream due to downstream stream watermark.
[2020-01-10 14:52:53.933][21][debug][client] [external/envoy/source/common/http/codec_client.cc:104] [C8] response complete
[2020-01-10 14:52:53.934][21][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:206] [C8] response complete
[2020-01-10 14:52:53.934][21][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:244] [C8] moving to ready
[2020-01-10 14:52:55.751][6][debug][upstream] [external/envoy/source/common/upstream/upstream_impl.cc:250] transport socket match, socket default selected for host with address 10.126.2.183:9966
[2020-01-10 14:52:57.017][6][debug][main] [external/envoy/source/server/server.cc:174] flushing stats
[2020-01-10 14:52:57.021][6][debug][router] [external/envoy/source/common/router/router.cc:440] [C0][S295780254997843152] cluster 'gloo.gloo-system.svc.cluster.local:9966' match for URL '/envoy.service.metrics.v2.MetricsService/StreamMetrics'
[2020-01-10 14:52:57.021][6][debug][router] [external/envoy/source/common/router/router.cc:555] [C0][S295780254997843152] router decoding headers:
':method', 'POST'
':path', '/envoy.service.metrics.v2.MetricsService/StreamMetrics'
':authority', 'gloo.gloo-system.svc.cluster.local:9966'
':scheme', 'http'
'te', 'trailers'
'content-type', 'application/grpc'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.64.0.40'

[2020-01-10 14:52:57.021][6][debug][pool] [external/envoy/source/common/http/http2/conn_pool.cc:98] [C6] creating stream
[2020-01-10 14:52:57.021][6][debug][router] [external/envoy/source/common/router/router.cc:1614] [C0][S295780254997843152] pool ready
[2020-01-10 14:52:57.044][6][debug][client] [external/envoy/source/common/http/codec_client.cc:104] [C6] response complete
[2020-01-10 14:52:57.048][6][debug][pool] [external/envoy/source/common/http/http2/conn_pool.cc:236] [C6] destroying stream: 0 remaining
[2020-01-10 14:52:57.048][6][debug][router] [external/envoy/source/common/router/router.cc:1041] [C0][S295780254997843152] upstream headers complete: end_stream=true
[2020-01-10 14:52:57.048][6][debug][router] [external/envoy/source/common/router/router.cc:1560] [C0][S295780254997843152] resetting pool request
[2020-01-10 14:52:57.048][6][debug][http] [external/envoy/source/common/http/async_client_impl.cc:93] async http request response headers (end_stream=true):
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '0'
'grpc-message', ''

[2020-01-10 14:52:57.049][6][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:732] [C6] stream closed: 0
[2020-01-10 14:52:57.054][6][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:615] [C6] sent reset code=0
[2020-01-10 14:52:57.115][23][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:259] [C3] new stream
[2020-01-10 14:52:57.115][23][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:695] [C3][S12206734060403850131] request headers complete (end_stream=true):
':authority', '10.64.0.40:8081'
':path', '/metrics'
':method', 'GET'
'user-agent', 'Prometheus/2.13.1'
'accept', 'application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1'
'accept-encoding', 'gzip'
'x-prometheus-scrape-timeout-seconds', '10.000000'

[2020-01-10 14:52:57.115][23][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1246] [C3][S12206734060403850131] request end stream
[2020-01-10 14:52:57.115][23][debug][router] [external/envoy/source/common/router/router.cc:440] [C3][S12206734060403850131] cluster 'admin_port_cluster' match for URL '/metrics'
[2020-01-10 14:52:57.115][23][debug][router] [external/envoy/source/common/router/router.cc:555] [C3][S12206734060403850131] router decoding headers:
':authority', '10.64.0.40:8081'
':path', '/stats/prometheus'
':method', 'GET'
':scheme', 'http'
'user-agent', 'Prometheus/2.13.1'
'accept', 'application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1'
'accept-encoding', 'gzip'
'x-prometheus-scrape-timeout-seconds', '10.000000'
'x-forwarded-proto', 'http'
'x-request-id', 'ceacf5c6-4789-4626-b317-0730f1ae7c4b'
'x-envoy-expected-rq-timeout-ms', '15000'
'x-envoy-original-path', '/metrics'

[2020-01-10 14:52:57.115][23][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:104] [C4] using existing connection
[2020-01-10 14:52:57.115][23][debug][router] [external/envoy/source/common/router/router.cc:1614] [C3][S12206734060403850131] pool ready
[2020-01-10 14:52:57.121][6][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:259] [C5] new stream
[2020-01-10 14:52:57.125][6][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:695] [C5][S8575386835320409887] request headers complete (end_stream=true):
':authority', '10.64.0.40:8081'
':path', '/stats/prometheus'
':method', 'GET'
'user-agent', 'Prometheus/2.13.1'
'accept', 'application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1'
'accept-encoding', 'gzip'
'x-prometheus-scrape-timeout-seconds', '10.000000'
'x-forwarded-proto', 'http'
'x-request-id', 'ceacf5c6-4789-4626-b317-0730f1ae7c4b'
'x-envoy-expected-rq-timeout-ms', '15000'
'x-envoy-original-path', '/metrics'
'content-length', '0'

[2020-01-10 14:52:57.129][6][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1246] [C5][S8575386835320409887] request end stream
[2020-01-10 14:52:57.130][6][debug][admin] [external/envoy/source/server/http/admin.cc:1192] [C5][S8575386835320409887] request complete: path: /stats/prometheus
[2020-01-10 14:52:57.214][6][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1567] [C5][S8575386835320409887] encoding headers via codec (end_stream=false):
':status', '200'
'content-type', 'text/plain; charset=UTF-8'
'cache-control', 'no-cache, max-age=0'
'x-content-type-options', 'nosniff'
'date', 'Fri, 10 Jan 2020 14:52:57 GMT'
'server', 'envoy'

[2020-01-10 14:52:57.215][23][debug][router] [external/envoy/source/common/router/router.cc:1041] [C3][S12206734060403850131] upstream headers complete: end_stream=false
[2020-01-10 14:52:57.215][23][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1567] [C3][S12206734060403850131] encoding headers via codec (end_stream=false):
':status', '200'
'content-type', 'text/plain; charset=UTF-8'
'cache-control', 'no-cache, max-age=0'
'x-content-type-options', 'nosniff'
'date', 'Fri, 10 Jan 2020 14:52:56 GMT'
'server', 'envoy'
'x-envoy-upstream-service-time', '99'

[2020-01-10 14:52:57.224][23][debug][client] [external/envoy/source/common/http/codec_client.cc:104] [C4] response complete
[2020-01-10 14:52:57.224][23][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:206] [C4] response complete
[2020-01-10 14:52:57.224][23][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:244] [C4] moving to ready
[2020-01-10 14:52:58.688][21][debug][conn_handler] [external/envoy/source/server/connection_handler_impl.cc:335] [C19] new connection
[2020-01-10 14:52:58.693][21][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:259] [C19] new stream
[2020-01-10 14:52:58.696][21][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:695] [C19][S17801744379907743748] request headers complete (end_stream=true):
':authority', '35.236.84.29'
':path', '/api/pets'
':method', 'GET'
'user-agent', 'curl/7.64.1'
'accept', '*/*'

[2020-01-10 14:52:58.700][21][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1246] [C19][S17801744379907743748] request end stream
[2020-01-10 14:52:58.704][21][debug][jwt] [external/envoy/source/extensions/filters/http/jwt_authn/filter.cc:124] Called Filter : setDecoderFilterCallbacks
[2020-01-10 14:52:58.708][21][debug][jwt] [external/envoy/source/extensions/filters/http/jwt_authn/filter.cc:46] Called Filter : decodeHeaders
[2020-01-10 14:52:58.712][21][debug][jwt] [external/envoy/source/extensions/filters/http/jwt_authn/filter.cc:84] Called Filter : check complete OK
[2020-01-10 14:52:58.712][21][debug][rbac] [external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:67] checking request: remoteAddress: 10.64.0.1:60924, localAddress: 10.64.0.40:8080, ssl: none, headers: ':authority', '35.236.84.29'
':path', '/api/pets'
':method', 'GET'
'user-agent', 'curl/7.64.1'
'accept', '*/*'
'x-forwarded-proto', 'http'
'x-request-id', 'cb3a5aa0-e7cb-4c12-80b5-0df257c046d0'
, dynamicMetadata: 
[2020-01-10 14:52:58.712][21][debug][rbac] [external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:118] no engine, allowed by default
[2020-01-10 14:52:58.712][21][debug][router] [external/envoy/source/common/router/router.cc:440] [C19][S17801744379907743748] cluster 'default-petstore-8080_gloo-system' match for URL '/api/pets'
[2020-01-10 14:52:58.713][21][debug][router] [external/envoy/source/common/router/router.cc:555] [C19][S17801744379907743748] router decoding headers:
':authority', '35.236.84.29'
':path', '/api/pets'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/7.64.1'
'accept', '*/*'
'x-forwarded-proto', 'http'
'x-request-id', 'cb3a5aa0-e7cb-4c12-80b5-0df257c046d0'
'x-envoy-expected-rq-timeout-ms', '15000'

[2020-01-10 14:52:58.713][21][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:95] creating a new connection
[2020-01-10 14:52:58.713][21][debug][client] [external/envoy/source/common/http/codec_client.cc:34] [C20] connecting
[2020-01-10 14:52:58.713][21][debug][connection] [external/envoy/source/common/network/connection_impl.cc:675] [C20] connecting to 10.64.0.28:8080
[2020-01-10 14:52:58.714][21][debug][connection] [external/envoy/source/common/network/connection_impl.cc:684] [C20] connection in progress
[2020-01-10 14:52:58.714][21][debug][pool] [external/envoy/source/common/http/conn_pool_base.cc:20] queueing request due to no available connections
[2020-01-10 14:52:58.714][21][debug][connection] [external/envoy/source/common/network/connection_impl.cc:547] [C20] connected
[2020-01-10 14:52:58.714][21][debug][client] [external/envoy/source/common/http/codec_client.cc:72] [C20] connected
[2020-01-10 14:52:58.714][21][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:249] [C20] attaching to next request
[2020-01-10 14:52:58.714][21][debug][router] [external/envoy/source/common/router/router.cc:1614] [C19][S17801744379907743748] pool ready
[2020-01-10 14:52:58.716][21][debug][router] [external/envoy/source/common/router/router.cc:1041] [C19][S17801744379907743748] upstream headers complete: end_stream=false
[2020-01-10 14:52:58.719][21][debug][client] [external/envoy/source/common/http/codec_client.cc:104] [C20] response complete
[2020-01-10 14:52:58.719][21][critical][main] [external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
[2020-01-10 14:52:58.720][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[2020-01-10 14:52:58.720][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 1499af2db71f283aa49466aabf49ceca81bfb8c5/1.13.0-dev/Distribution/RELEASE/BoringSSL
[2020-01-10 14:52:58.720][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #0: [0x563f045597fe]
[2020-01-10 14:52:58.720][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #1: [0x563f04559709]
[2020-01-10 14:52:58.720][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #2: [0x563f048be903]
[2020-01-10 14:52:58.720][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #3: [0x563f042d63d2]
[2020-01-10 14:52:58.721][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #4: [0x563f042dac6f]
[2020-01-10 14:52:58.721][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #5: [0x563f042dc8ee]
[2020-01-10 14:52:58.721][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #6: [0x563f042d93a1]
[2020-01-10 14:52:58.721][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #7: [0x563f042db7bc]
[2020-01-10 14:52:58.721][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #8: [0x563f04287fe7]
[2020-01-10 14:52:58.721][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #9: [0x563f04206e1c]
[2020-01-10 14:52:58.721][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #10: [0x563f04206e1c]
[2020-01-10 14:52:58.721][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #11: [0x563f042ebcde]
[2020-01-10 14:52:58.722][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #12: [0x563f042e96d8]
[2020-01-10 14:52:58.722][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #13: [0x563f042ed12d]
[2020-01-10 14:52:58.722][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #14: [0x563f043e881a]
[2020-01-10 14:52:58.722][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #15: [0x563f042e89aa]
[2020-01-10 14:52:58.722][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #16: [0x563f042e878f]
[2020-01-10 14:52:58.722][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #17: [0x563f04268ef8]
[2020-01-10 14:52:58.722][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #18: [0x563f04269c4d]
[2020-01-10 14:52:58.723][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #19: [0x563f0409f91b]
[2020-01-10 14:52:58.723][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #20: [0x563f0409bf77]
[2020-01-10 14:52:58.723][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #21: [0x563f0409ba4d]
[2020-01-10 14:52:58.723][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #22: [0x563f040967c0]
[2020-01-10 14:52:58.723][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #23: [0x563f043e251b]
[2020-01-10 14:52:58.723][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #24: [0x563f043e0dae]
[2020-01-10 14:52:58.723][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #25: [0x563f0408d008]
[2020-01-10 14:52:58.723][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #26: [0x563f0455a193]
[2020-01-10 14:52:58.730][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #27: [0x7f1ad9c19f30]
[2020-01-10 14:52:58.730][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Aborted, suspect faulting address 0x6
[2020-01-10 14:52:58.730][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[2020-01-10 14:52:58.730][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 1499af2db71f283aa49466aabf49ceca81bfb8c5/1.13.0-dev/Distribution/RELEASE/BoringSSL
[2020-01-10 14:52:58.730][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #0: [0x7f1ad9c25420]
[2020-01-10 14:52:58.730][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #1: [0x563f04559709]
[2020-01-10 14:52:58.730][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #2: [0x563f048be903]
[2020-01-10 14:52:58.731][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #3: [0x563f042d63d2]
[2020-01-10 14:52:58.731][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #4: [0x563f042dac6f]
[2020-01-10 14:52:58.731][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #5: [0x563f042dc8ee]
[2020-01-10 14:52:58.734][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #6: [0x563f042d93a1]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #7: [0x563f042db7bc]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #8: [0x563f04287fe7]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #9: [0x563f04206e1c]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #10: [0x563f04206e1c]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #11: [0x563f042ebcde]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #12: [0x563f042e96d8]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #13: [0x563f042ed12d]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #14: [0x563f043e881a]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #15: [0x563f042e89aa]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #16: [0x563f042e878f]
[2020-01-10 14:52:58.736][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #17: [0x563f04268ef8]
[2020-01-10 14:52:58.738][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #18: [0x563f04269c4d]
[2020-01-10 14:52:58.738][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #19: [0x563f0409f91b]
[2020-01-10 14:52:58.738][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #20: [0x563f0409bf77]
[2020-01-10 14:52:58.738][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #21: [0x563f0409ba4d]
[2020-01-10 14:52:58.738][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #22: [0x563f040967c0]
[2020-01-10 14:52:58.738][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #23: [0x563f043e251b]
[2020-01-10 14:52:58.738][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #24: [0x563f043e0dae]
[2020-01-10 14:52:58.738][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #25: [0x563f0408d008]
[2020-01-10 14:52:58.739][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #26: [0x563f0455a193]
[2020-01-10 14:52:58.739][21][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #27: [0x7f1ad9c19f30]
ActiveStream 0x563f0a5ae480, stream_id_: 17801744379907743748, has_continue_headers_: 0, is_head_request_: 0, decoding_headers_only_: 0, encoding_headers_only_: 0
request_headers_: 
  ':authority', '35.236.84.29'
  ':path', '/api/pets'
  ':method', 'GET'
  ':scheme', 'http'
  'user-agent', 'curl/7.64.1'
  'accept', '*/*'
  'x-forwarded-proto', 'http'
  'x-request-id', 'cb3a5aa0-e7cb-4c12-80b5-0df257c046d0'
  'x-envoy-expected-rq-timeout-ms', '15000'
request_trailers_: null
response_headers_: 
  'content-type', 'application/xml'
  'date', 'Fri, 10 Jan 2020 14:52:58 GMT'
  'content-length', '86'
  'x-envoy-upstream-service-time', '4'
  'server', 'envoy'
response_trailers_: null
&stream_info_: 
  StreamInfoImpl 0x563f0a5ae5b8, protocol_: 1, response_code_: null, response_code_details_: via_upstream, health_check_request_: 0, route_name_: 

```

**Comment by yuval-k** [comment] 2020-01-10 17:05
the issue is that if the response code is not 404, this transformations sets the status header to an empty string.
this should never happen in envoy, hence the crash.
to solve this, the template can be changed like so:
```
text: '{% if header(":status") == "404" %}200{% else %}{{header(":status")}}{% endif %}'
```

**Comment by rickducott** [comment] 2020-02-11 03:22
Given the answer here, I'm going to close the issue. We have other issues tracking possible enhancements to help detect invalid transformations prior to applying to Kube.

**Closed by rickducott** 2020-02-11 03:22 UTC
Labels: Type: bug
