### ISSUE TITLE
Switch to distroless images

### ISSUE THREAD

**Issue by gunnar-solo** [solo-io/gloo#6084] opened 2022-03-14 17:22 UTC
When implementing a solution for [Gateway-proxy is crashing during startup](https://github.com/solo-io/gloo/issues/5980), I found that the root cause was that [alpine-glibc](https://hub.docker.com/r/frolvlad/alpine-glibc/) had changed its `:latest` underneath of us.  Not a huge deal--pinning the version resolved the issue.  **But**, it did reveal that envoy [no longer supports building alpine images](https://github.com/envoyproxy/envoy/issues/19781).  This now is a point of tech drift between `gloo` and `envoy` that we want to close.

Envoy is using [distroless images](https://github.com/GoogleContainerTools/distroless) and has for some time, now.  More or less, this issue is to...
- [ ] Use distroless images as an envoy base: ([envoy-gloo](https://github.com/solo-io/envoy-gloo/blob/master/ci/Dockerfile#L4), [envoy-gloo-ee](https://github.com/solo-io/envoy-gloo-ee/blob/master/ci/Dockerfile#L4))
- [ ] Investigate/document the possibility of using distroless images for our other containers (`gloo`, `gateway`, ...)
- [ ] Add debugging capabilities as-needed.  @EItanya brought up a [concern in a private channel](https://solo-io-corp.slack.com/archives/C011H3TU17T/p1647272158512559) about distroless images not having shells to debug with.  Fair--this _is_ by design on their part

While this isn't an _immediately pressing_ issue, it has the potential to become dangerous, as we drift further and further from `envoy`.  Not addressing it could result in us needing to patch more of our own CVEs, as well as introduce increasingly difficult compatibility issues between `gloo` and `envoy`

**Comment by sam-heilbron** [comment] 2023-12-12 20:48
This is a duplicate of https://github.com/solo-io/gloo/issues/8849. Closing.

**Closed by sam-heilbron** 2023-12-12 20:48 UTC
Labels: Type: Bug, Area: Envoy, Type: Tech Debt, Triage: Duplicate
