### ISSUE TITLE
better query parameter matching for REST-to-gRPC transformation

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1327] opened 2019-10-02 20:53 UTC
currently gloo supports header and path extraction during REST-to-gRPC translation

A primitive, order-sensitive, form of query parameter extraction is supported

Since query parameter ordering is arbitrary, Gloo should should not care about parameter ordering when extracting values

**Comment by mitchdraft** [comment] 2019-10-03 11:37
parent issue: https://github.com/solo-io/gloo/issues/845

**Comment by rickducott** [comment] 2020-02-10 21:41
Dupe of parent issue

**Closed by rickducott** 2020-02-10 21:41 UTC
Labels: Size: S, Type: Enhancement
