### ISSUE TITLE
CI Test Flake: Kube2e - Could not determine gloo server

### ISSUE THREAD

**Issue by inFocus7** [solo-io/gloo#6253] opened 2022-04-06 19:13 UTC
### Gloo Edge Version

1.11.x (beta)

### Describe the bug

Test flake in `k8s regression tests (glooctl, false)`. Looks like it's due to gloo versioning(?)

[flake logs](https://github.com/solo-io/gloo/runs/5855099038?check_suite_focus=true)

```
• Failure in Spec Teardown (AfterEach) [8.560 seconds]
Kube2e: glooctl environment with Istio and Gloo pre-installed [AfterEach] istio uninject succeeds when no upstreams contain sds configuration 
/home/runner/work/gloo/gloo/test/kube2e/glooctl/glooctl_test.go:154

  should be able to remove gloo route to petstore
  Unexpected error:
      <*errors.withStack | 0xc001ffa2e8>: {
          error: <*errors.withMessage | 0xc001f92fc0>{
              cause: <*exec.ExitError | 0xc001f92fa0>{
                  ProcessState: {
                      pid: 55049,
                      status: 256,
                      rusage: {
                          Utime: {Sec: 0, Usec: 127686},
                          Stime: {Sec: 0, Usec: 21281},
                          Maxrss: 386040,
                          Ixrss: 0,
                          Idrss: 0,
                          Isrss: 0,
                          Minflt: 2304,
                          Majflt: 2,
                          Nswap: 0,
                          Inblock: 48,
                          Oublock: 0,
                          Msgsnd: 0,
                          Msgrcv: 0,
                          Nsignals: 0,
                          Nvcsw: 521,
                          Nivcsw: 496,
                      },
                  },
                  Stderr: nil,
              },
              msg: "[_output/glooctl-linux-amd64 remove route --name petstore --namespace gloo-system] failed: Warning: Could not determine gloo server versions (is Gloo running outside of kubernetes?): Version v0.0.0-kind is not greater than or equal to v0.0.0\nError: writing updated vs: invalid resource version gloo-system.petstore given , expected 3455\n",
          },
          stack: [0x4cb94d6, 0x4cb90a9, 0x4cb9050, 0x4cc8d45, 0x4cca2c5, 0x227737d, 0x2276d85, 0x227749a, 0x2283e93, 0x22815e0, 0x2280a28, 0x22bff7c, 0x22bf976, 0x22becc6, 0x22c28ba, 0x22da2d8, 0x22d9eeb, 0x4cc772d, 0x1739823, 0x15f4861],
      }
      [_output/glooctl-linux-amd64 remove route --name petstore --namespace gloo-system] failed: Warning: Could not determine gloo server versions (is Gloo running outside of kubernetes?): Version v0.0.0-kind is not greater than or equal to v0.0.0
      Error: writing updated vs: invalid resource version gloo-system.petstore given , expected 3455
      : exit status 1
  occurred
```

### Steps to reproduce the bug

CI test flake

### Expected Behavior

Test should pass

**Comment by jenshu** [comment] 2022-04-21 01:57
https://github.com/solo-io/gloo/runs/6105009973?check_suite_focus=true

**Comment by jenshu** [comment] 2022-05-09 18:59
another failure in glooctl test, although might be a different error https://github.com/solo-io/gloo/runs/6357424358?check_suite_focus=true

**Comment by ashishb-solo** [comment] 2022-07-20 16:06
another similar, but not exactly the same:

https://github.com/solo-io/gloo/runs/7415789614?check_suite_focus=true

```
• Failure in Spec Setup (BeforeEach) [7.056 seconds]
Kube2e: glooctl environment with Istio and Gloo pre-installed [BeforeEach] istio uninject fails when upstreams contain sds configuration and --include-upstreams=false 
/home/runner/work/gloo/gloo/test/kube2e/glooctl/glooctl_test.go:172
  should be able to add gloo route to petstore
  Unexpected error:
      <*errors.withStack | 0xc001f9b848>: {
          error: <*errors.withMessage | 0xc0020b8700>{
              cause: <*exec.ExitError | 0xc0020b86e0>{
                  ProcessState: {
                      pid: 58622,
                      status: 256,
                      rusage: {
                          Utime: {Sec: 0, Usec: 135899},
                          Stime: {Sec: 0, Usec: 41524},
                          Maxrss: 380272,
                          Ixrss: 0,
                          Idrss: 0,
                          Isrss: 0,
                          Minflt: 2171,
                          Majflt: 0,
                          Nswap: 0,
                          Inblock: 0,
                          Oublock: 0,
                          Msgsnd: 0,
                          Msgrcv: 0,
                          Nsignals: 0,
                          Nvcsw: 566,
                          Nivcsw: 431,
                      },
                  },
                  Stderr: nil,
              },
              msg: "[_output/glooctl-linux-amd64 add route --name petstore --namespace gloo-system --path-prefix / --dest-name default-petstore-8080 --dest-namespace gloo-system] failed: Warning: Could not determine gloo server versions (is Gloo running outside of kubernetes?): Version v0.0.0-kind is not greater than or equal to v0.0.0\nError: invalid resource version gloo-system.petstore given , expected 4022\n",
          },
          stack: [0x481ea45, 0x481e3f9, 0x481e3c9, 0x4834b30, 0x483441a, 0x22df796, 0x22dee98, 0x22dfc15, 0x22e8009, 0x22e74ec, 0x231d05b, 0x231cc56, 0x231beb7, 0x231f636, 0x2335273, 0x2334fd8, 0x482e4fe, 0x17d6914, 0x1672001],
      }
      [_output/glooctl-linux-amd64 add route --name petstore --namespace gloo-system --path-prefix / --dest-name default-petstore-8080 --dest-namespace gloo-system] failed: Warning: Could not determine gloo server versions (is Gloo running outside of kubernetes?): Version v0.0.0-kind is not greater than or equal to v0.0.0
      Error: invalid resource version gloo-system.petstore given , expected 4022
      : exit status 1
  occurred
  /home/runner/work/gloo/gloo/test/kube2e/glooctl/glooctl_test.go:38
```

**Comment by sam-heilbron** [comment] 2023-02-22 22:32
Duplicate of https://github.com/solo-io/gloo/issues/4428

**Closed by sam-heilbron** 2023-02-22 22:32 UTC
Labels: Type: Bug, Type: CI Test Flake
