### ISSUE TITLE
The fatal error when installing gloo with read-only ui

### ISSUE THREAD

**Issue by GitHub-Bryce** [solo-io/gloo#3010] opened 2020-05-14 03:13 UTC
1、Installation command
 glooctl --kubeconfig  kube.conf  install  gateway --with-admin-console -n gloo-test

2、pod status
NAME                             READY   STATUS             RESTARTS   AGE
api-server-688944574-jxm7v       3/3     Running            0          70s
discovery-6ddf7dbbc9-xj254       1/1     Running            0          70s
gateway-8576df8f4d-dpwbz         0/1     CrashLoopBackOff   3          70s
gateway-proxy-5666b6c785-vwjsb   1/1     Running            0          70s
gloo-7d5c8864bd-9ctrb            1/1     Running            0          70s

3、the error log
{"level":"info","ts":1589371524.4169405,"logger":"gateway.v1.event_loop","caller":"v1/setup_event_loop.sk.go:57","msg":"event loop started","version":"1.3.26"}
{"level":"fatal","ts":1589371524.5198936,"logger":"gateway","caller":"setuputils/main_setup.go:89","msg":"error in setup: VALIDATION_MUST_START was set to true, but no validation configuration was provided in the settings. Ensure the v1.Settings {default gloo-system} contains the spec.gateway.validation config","version":"1.3.26","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:89\ngithub.com/solo-io/gloo/projects/gateway/pkg/setup.Main\n\t/workspace/gloo/projects/gateway/pkg/setup/setup.go:13\nmain.main\n\t/workspace/gloo/projects/gateway/cmd/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

I operated according to official documents, I don’t know what is this？

**Comment by RichiCoder1** [comment] 2020-05-26 15:41
Unfortunately a known issue with some workarounds: https://github.com/solo-io/gloo/issues/2127

**Comment by arianaw66** [comment] 2020-05-27 22:13
Closing as duplicate of https://github.com/solo-io/gloo/issues/2127

**Closed by arianaw66** 2020-05-27 22:13 UTC
Labels: Type: Question
