### ISSUE TITLE
FDS should always run for AWS/Azure upstreams unless blacklisted

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#1847] opened 2019-12-09 03:27 UTC
After encountering #1844 and looking at discovery with @ilackarms, we agreed we should not require explicit whitelisting of AWS/Azure upstreams as they are hard to use without FDS. Instead they should default to blacklist. The others make sense to default to whitelist due to the potential cost of polling.

**Comment by EItanya** [comment] 2019-12-12 19:48
dupe of https://github.com/solo-io/gloo/issues/1878

**Closed by EItanya** 2019-12-12 19:48 UTC
Labels: Type: bug
