### ISSUE TITLE
failover.policy.overprovisioningFactor is ignored

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8720] opened 2023-09-27 13:45 UTC
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.13.24

### Kubernetes Version

1.23

### Describe the bug

Upstream `failover.policy.overprovisioningFactor` is ignored

### Expected Behavior

Upstream `failover.policy.overprovisioningFactor` should result in Envoy config with `cluster.load_assignment.policy.overprovisioning_factor`

### Steps to reproduce the bug

Upstream:

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: failover
  namespace: gloo-system
spec:
  failover:
    policy:
      overprovisioningFactor: 600
    prioritizedLocalities:
    - localityEndpoints:
      - lbEndpoints:
        - address: echo-service.default.svc.cluster.local
          healthCheckConfig:
            path: /status/200
          port: 8080
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      expectedStatuses:
      - end: 201
        start: 200
      path: /status/200
    interval: 10s
    timeout: 5s
    unhealthyThreshold: 1
  loadBalancerConfig:
    healthyPanicThreshold: 50
  static:
    hosts:
    - addr: httpbin.default.svc.cluster.local
      healthCheckConfig:
        path: /status/500
      port: 8000

```
Route in VirtualService:

```
    - matchers:
      - prefix: /failover/
      options:
        prefixRewrite: /
      routeAction:
        single:
          upstream:
            name: failover
            namespace: gloo-system
```

Resulting Envoy Cluster config:

```
    {
     "version_info": "8162297227039708371",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "failover_gloo-system",
      "type": "STRICT_DNS",
      "connect_timeout": "5s",
      "health_checks": [
       {
        "timeout": "5s",
        "interval": "10s",
        "unhealthy_threshold": 1,
        "healthy_threshold": 1,
        "custom_health_check": {
         "name": "io.solo.health_checkers.advanced_http",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.config.health_checker.advanced_http.v2.AdvancedHttp",
          "http_health_check": {
           "path": "/status/500",
           "expected_statuses": [
            {
             "start": "200",
             "end": "201"
            }
           ]
          }
         }
        }
       }
      ],
      "dns_lookup_family": "V4_ONLY",
      "metadata": {},
      "common_lb_config": {
       "healthy_panic_threshold": {
        "value": 50
       }
      },
      "load_assignment": {
       "cluster_name": "failover_gloo-system",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "httpbin.default.svc.cluster.local",
              "port_value": 8000
             }
            },
            "health_check_config": {
             "hostname": "httpbin.default.svc.cluster.local"
            },
            "hostname": "httpbin.default.svc.cluster.local"
           },
           "metadata": {
            "filter_metadata": {
             "envoy.transport_socket_match": {
              "httpbin.default.svc.cluster.local;httpbin.default.svc.cluster.local:8000": true
             },
             "io.solo.health_checkers.advanced_http": {
              "path": "/status/500"
             }
            }
           }
          }
         ]
        },
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "echo-service.default.svc.cluster.local",
              "port_value": 8080
             }
            },
            "health_check_config": {},
            "hostname": "echo-service.default.svc.cluster.local"
           },
           "metadata": {
            "filter_metadata": {
             "io.solo.health_checkers.advanced_http": {
              "path": "/status/200"
             }
            }
           }
          }
         ],
         "priority": 1
        }
       ]
      }
     },
     "last_updated": "2023-09-27T13:17:26.234Z"
    },
```

**Comment by sam-heilbron** [comment] 2023-10-02 17:53
## What is overprovisioningFactor?
The `overprovisioningFactor` was introduced into the Gloo Edge API, to allow Gateway maintainers to control failover behavior. Without this enabled, if an Upstream contains multiple hosts, failover will occur as soon as one of those hosts is unhealthy. This feature allows you to configure the percentage of hosts that must be unhealthy before failover endpoints are relied on (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/overprovisioning#arch-overview-load-balancing-overprovisioning-factor) 

There are two different, mutually exclusive approaches to configure load balancing on a cluster: 
- Locality weighted load balancing (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight: Where the control plane supplies endpoints and weights explicitly via EDS
-  Zone aware load balancing (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/zone_aware#arch-overview-load-balancing-zone-aware-routing): Where the data plane determines load balancing, by trying to optimize for requests to be sent to a local zone as much as possible

## How was it implemented?
This feature was implemented in tandem with locality weighted load balancing. Since that form of load balancing is only supported for Envoy clusters of type EDS, this configuration is only applied if the Upstream is configured for EDS as well.


## Why does the current example not work?
In the current example, the cluster is of type STRICT_DNS (Static Upstreams map to this, https://github.com/solo-io/gloo/blob/main/projects/gloo/pkg/plugins/static/plugin.go#L81) , meaning that endpoint resolution is up to the data plane, and not the control plane. As a result, the failover policy is never applied to the configuration, since that is only done during endpoint discovery (EDS)


## Next steps
1. What is the use case that we are trying to solve? Independent of the expected Control Plane or Data Plane APIs, what is the behavior that is desired?
2. Will the overprovisioningFactor even behave appropriately if we configure it for non-eds clusters? From reading the Envoy documentation, it appears that this API is only used by locality weighted load balancing (and that is how we implemented it originally). If this assumption is correct, then there is no code  that can be changed. If this assumption was wrong, then we can configure this field here: https://github.com/solo-io/solo-projects/blob/main/projects/gloo/pkg/plugins/failover/plugin.go#L140

**Comment by sam-heilbron** [comment] 2023-10-05 16:16
Gloo Edge Enterprise 1.13.26 has been released with a fix for this. I have confirmed that I can apply the resources defined in the issue and it produces a cluster load assignment, where the overprovisioningFactor is respected:
```
"load_assignment": {
       "cluster_name": "failover_gloo-system",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "httpbin.default.svc.cluster.local",
              "port_value": 8000
             }
            },
            "health_check_config": {
             "hostname": "httpbin.default.svc.cluster.local"
            },
            "hostname": "httpbin.default.svc.cluster.local"
           },
           "metadata": {
            "filter_metadata": {
             "envoy.transport_socket_match": {
              "httpbin.default.svc.cluster.local;httpbin.default.svc.cluster.local:8000": true
             },
             "io.solo.health_checkers.advanced_http": {
              "path": "/status/500"
             }
            }
           }
          }
         ]
        },
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "echo-service.default.svc.cluster.local",
              "port_value": 8080
             }
            },
            "health_check_config": {},
            "hostname": "echo-service.default.svc.cluster.local"
           },
           "metadata": {
            "filter_metadata": {
             "io.solo.health_checkers.advanced_http": {
              "path": "/status/200"
             }
            }
           }
          }
         ],
         "priority": 1
        }
       ],
       "policy": {
        "overprovisioning_factor": 600
       }
      }
     },

```

**Comment by sam-heilbron** [comment] 2023-10-09 15:11
This fix is/will be available in the following versions of Gloo Edge Enterprise:
- 1.13.26
- 1.14.11
- 1.15.5
- 1.16.0-beta1

**Closed** 2023-10-09 15:48 UTC
Labels: Type: Bug, release/1.13
